export const chapter_3 = {
	header: 'III',
	text: `Die schwere Verletzung Gregors, an der er über einen Monat litt – der Apfel, den niemand zu entfernen wagte, blieb als sichtbares Andenken in seinem Fleisch stecken –, schien selbst den Vater daran erinnert zu haben, dass Gregor trotz seiner gegenwärtigen traurigen und abstoßenden Gestalt ein Familienmitglied war, das man nicht wie einen Feind behandeln durfte. Stattdessen war es die Pflicht der Familie, den Widerwillen zu überwinden und ihn zu ertragen, einfach nur zu ertragen.

Und obwohl Gregor durch seine Wunde wahrscheinlich für immer an Beweglichkeit verloren hatte und vorläufig für die Durchquerung seines Zimmers wie ein alter Invalide lange, lange Minuten brauchte – an das Kriechen in der Höhe war nicht zu denken –, bekam er für diese Verschlechterung seines Zustandes einen seiner Meinung nach völlig ausreichenden Ersatz. Denn jeden Abend wurde die Wohnzimmertür, die er schon ein bis zwei Stunden vorher genau beobachtete, geöffnet. So konnte er, im Dunkel seines Zimmers liegend und vom Wohnzimmer aus unsichtbar, die ganze Familie am beleuchteten Tisch sehen und ihren Gesprächen, gewissermaßen mit allgemeiner Erlaubnis, also ganz anders als früher, zuhören.

Natürlich waren es nicht mehr die lebhaften Unterhaltungen früherer Zeiten, an die Gregor in den kleinen Hotelzimmern immer mit einer gewissen Sehnsucht gedacht hatte, wenn er sich müde ins feuchte Bettzeug hatte werfen müssen. Jetzt ging es meistens sehr still zu. Der Vater schlief bald nach dem Abendessen in seinem Sessel ein; die Mutter und die Schwester ermahnten sich gegenseitig zur Stille. Die Mutter nähte, weit über das Licht vorgebeugt, feine Wäsche für ein Modegeschäft. Die Schwester, die eine Stelle als Verkäuferin angenommen hatte, lern.te am Abend Stenografie und Französisch, um vielleicht später eine bessere Position zu erreichen. Manchmal wachte der Vater auf und, als wüsste er gar nicht, dass er geschlafen hatte, sagte er zur Mutter: »Wie lange du heute schon wieder nähst!« und schlief sofort wieder ein, während Mutter und Schwester sich müde zulächelten.

Mit einer Art Eigensinn weigerte sich der Vater, auch zu Hause seine Uniform auszuziehen. Und während der Morgenmantel ungenutzt am Kleiderhaken hing, schlummerte der Vater vollständig angezogen auf seinem Platz, als sei er immer zu seinem Dienst bereit und warte auch hier auf die Stimme seines Vorgesetzten. Infolgedessen verlor die Uniform, die schon anfangs nicht neu war, trotz aller Sorgfalt von Mutter und Schwester an Sauberkeit, und Gregor sah oft ganze Abende lang auf dieses über und über fleckige Kleidungsstück mit seinen stets geputzten Goldknöpfen, in dem der alte Mann höchst unbequem und doch ruhig schlief.

Sobald die Uhr zehn schlug, versuchte die Mutter mit leisen Worten, den Vater zu wecken und ihn dann zu überreden, ins Bett zu gehen, denn hier war es kein richtiger Schlaf. Diesen Schlaf brauchte der Vater, der um sechs Uhr seinen Dienst antreten musste, äußerst dringend. Aber in dem Eigensinn, der ihn ergriffen hatte, seit er Diener war, bestand er immer darauf, noch länger am Tisch zu bleiben, obwohl er regelmäßig einschlief. Danach war er nur mit größter Mühe dazu zu bewegen, den Sessel mit dem Bett zu tauschen. Da konnten Mutter und Schwester noch so sehr mit kleinen Ermahnungen auf ihn einreden, viertelstundenlang schüttelte er langsam den Kopf, hielt die Augen geschlossen und stand nicht auf. Die Mutter zupfte ihn am Ärmel, flüsterte ihm Schmeicheleien ins Ohr, die Schwester ließ ihre Aufgabe liegen, um der Mutter zu helfen, aber beim Vater half das nichts. Er versank nur noch tiefer in seinen Sessel. Erst als ihn die Frauen unter den Achseln fassten, schlug er die Augen auf, sah abwechselnd die Mutter und die Schwester an und sagte gewöhnlich: »Das ist ein Leben. Das ist die Ruhe meiner alten Tage.« Und auf die beiden Frauen gestützt, erhob er sich umständlich, als sei er für sich selbst die größte Last, ließ sich von den Frauen bis zur Tür führen, winkte ihnen dort ab und ging nun selbstständig weiter, während die Mutter ihr Nähzeug und die Schwester ihre Feder eiligst hinwarfen, um hinter dem Vater zu laufen und ihm weiter zu helfen.

Wer hatte in dieser abgearbeiteten und übermüdeten Familie Zeit, sich mehr um Gregor zu kümmern, als unbedingt nötig war? Der Haushalt wurde immer weiter eingeschränkt; das Dienstmädchen wurde nun doch entlassen. Eine riesige, knochige Haushälterin mit weißem, den Kopf umflatterndem Haar kam morgens und abends, um die schwerste Arbeit zu verrichten; alles andere erledigte die Mutter neben ihrer vielen Näharbeit. Es geschah sogar, dass verschiedene Familienschmuckstücke, die früher Mutter und Schwester bei gesellschaftlichen Anlässen voller Stolz getragen hatten, verkauft wurden, wie Gregor am Abend aus der allgemeinen Besprechung der erzielten Preise erfuhr. Die größte Klage war aber stets, dass man diese für die gegenwärtigen Verhältnisse viel zu große Wohnung nicht verlassen konnte, da es unvorstellbar war, wie man Gregor umziehen sollte. Aber Gregor verstand wohl, dass es nicht nur die Rücksicht auf ihn war, die einen Umzug verhinderte, denn ihn hätte man ja in einer passenden Kiste mit ein paar Luftlöchern leicht transportieren können. Was die Familie hauptsächlich vom Wohnungswechsel abhielt, war vielmehr die völlige Hoffnungslosigkeit und der Gedanke, dass sie von einem Unglück getroffen worden waren, wie niemand sonst im ganzen Verwandten- und Bekanntenkreis. Was die Welt von armen Leuten verlangt, erfüllten sie bis zum Äußersten: Der Vater holte den Bankangestellten das Frühstück, die Mutter opferte sich für die Wäsche fremder Leute auf, die Schwester lief auf Befehl der Kunden hinter dem Verkaufstresen hin und her, aber zu mehr reichten die Kräfte der Familie nicht. Und die Wunde im Rücken begann Gregor wie neu zu schmerzen, wenn Mutter und Schwester, nachdem sie den Vater ins Bett gebracht hatten, zurückkamen, die Arbeit liegen ließen, nahe zusammenrückten und Wange an Wange saßen; wenn dann die Mutter auf Gregors Zimmer zeigte und sagte: »Mach dort die Tür zu, Grete«, und wenn Gregor dann wieder im Dunkeln war, während nebenan die Frauen leise miteinander redeten.

Die Nächte und Tage verbrachte Gregor fast ganz ohne Schlaf. Manchmal dachte er daran, beim nächsten Öffnen der Tür die Angelegenheiten der Familie wieder wie früher in die Hand zu nehmen. In seinen Gedanken erschienen nach langer Zeit wieder der Chef und der Prokurist, die Verkäufer und die Auszubildenden, der schwer von Begriff seiende Hausmeister, zwei, drei Freunde aus anderen Geschäften, ein Zimmermädchen aus einem Hotel in der Provinz, eine liebe, flüchtige Erinnerung, eine Verkäuferin aus einem Hutgeschäft, um die er sich ernsthaft, aber zu langsam bemüht hatte – sie alle erschienen vermischt mit Fremden oder schon Vergessenen. Aber statt ihm und seiner Familie zu helfen, waren sie alle unzugänglich, und er war froh, wenn sie verschwanden. Dann aber war er wieder gar nicht in der Stimmung, sich um seine Familie zu sorgen. Nur Wut über die schlechte Pflege erfüllte ihn, und obwohl er sich nichts vorstellen konnte, worauf er Appetit gehabt hätte, machte er Pläne, wie er in die Vorratskammer gelangen könnte, um sich dort zu nehmen, was ihm, auch wenn er keinen Hunger hatte, zustand. Ohne jetzt noch groß darüber nachzudenken, womit man Gregor eine besondere Freude machen könnte, schob die Schwester eilig, bevor sie morgens und mittags ins Geschäft lief, mit dem Fuß irgendein beliebiges Essen in Gregors Zimmer. Am Abend kehrte sie es mit einem Schwung des Besens hinaus, gleichgültig, ob das Essen vielleicht nur probiert oder – was am häufigsten der Fall war – gänzlich unberührt geblieben war. Das Aufräumen des Zimmers, das sie nun immer abends erledigte, konnte gar nicht schneller gehen. Schmutzstreifen zogen sich die Wände entlang, hier und da lagen Knäuel von Staub und Dreck. Am Anfang stellte sich Gregor bei der Ankunft der Schwester in besonders auffällige Ecken, um ihr durch diese Haltung gewissermaßen einen Vorwurf zu machen. Aber er hätte wohl wochenlang dort bleiben können, ohne dass sich die Schwester gebessert hätte; sie sah den Schmutz genauso wie er, aber sie hatte sich entschlossen, ihn einfach zu lassen.

Aber selbst wenn die Schwester, erschöpft von ihrer Arbeit, es leid geworden war, sich wie früher um Gregor zu kümmern, hätte die Mutter nicht für sie einspringen müssen, und Gregor hätte nicht vernachlässigt werden müssen. Denn nun war die Haushälterin da. Diese alte Witwe, die in ihrem langen Leben mit Hilfe ihres starken Knochenbaus das Schlimmste überstanden haben mochte, hatte keinen wirklichen Abscheu vor Gregor. Ohne irgendwie neugierig zu sein, hatte sie zufällig einmal die Tür zu Gregors Zimmer geöffnet und war beim Anblick Gregors, der, völlig überrascht, obwohl ihn niemand jagte, hin- und herzulaufen begann, mit im Schoß gefalteten Händen staunend stehen geblieben. Seitdem versäumte sie nicht, morgens und abends kurz die Tür einen Spalt zu öffnen und zu Gregor hineinzuschauen. Anfangs rief sie ihn auch zu sich, mit Worten, die sie wahrscheinlich für freundlich hielt, wie: »Komm mal her, alter Mistkäfer!« oder »Seht mal den alten Mistkäfer an!« Auf solche Ansprachen antwortete Gregor mit nichts, sondern blieb unbeweglich auf seinem Platz, als wäre die Tür gar nicht geöffnet worden. Hätte man dieser Haushälterin doch lieber den Befehl gegeben, sein Zimmer täglich zu reinigen, anstatt sie ihn nach ihrer Laune sinnlos stören zu lassen! Eines frühen Morgens – ein heftiger Regen, vielleicht schon ein Zeichen des kommenden Frühlings, schlug an die Scheiben – war Gregor, als die Haushälterin wieder mit ihren Sprüchen anfing, derartig verärgert, dass er sich, wie zum Angriff, wenn auch langsam und gebrechlich, zu ihr umdrehte. Die Haushälterin aber, anstatt sich zu fürchten, hob nur einen Stuhl hoch, der in der Nähe der Tür stand. Wie sie mit weit geöffnetem Mund da stand, war ihre Absicht klar: den Mund erst zu schließen, wenn der Stuhl in ihrer Hand auf Gregors Rücken niedersausen würde. »Also, weiter geht es nicht?«, fragte sie, als Gregor sich wieder umdrehte, und stellte den Stuhl ruhig in die Ecke zurück.

Gregor aß nun fast gar nichts mehr. Nur wenn er zufällig am vorbereiteten Essen vorbeikam, nahm er zum Spiel einen Bissen in den Mund, hielt ihn dort stundenlang und spuckte ihn dann meist wieder aus. Zuerst dachte er, es sei die Traurigkeit über den Zustand seines Zimmers, die ihn vom Essen abhielt, aber mit den Veränderungen des Zimmers gewöhnte er sich sehr bald an. Man hatte sich angewöhnt, Dinge, die man anderswo nicht unterbringen konnte, in dieses Zimmer zu stellen, und davon gab es nun viele, da man ein Zimmer der Wohnung an drei Untermieter vermietet hatte. Diese ernsten Herren – alle drei hatten Vollbärte, wie Gregor einmal durch einen Türspalt feststellte – waren penibel auf Ordnung bedacht, nicht nur in ihrem Zimmer, sondern, da sie sich nun einmal hier eingemietet hatten, im ganzen Haushalt, also insbesondere in der Küche. Unnützes oder gar schmutziges Zeug duldeten sie nicht. Außerdem hatten sie größtenteils ihre eigenen Möbel mitgebracht. Aus diesem Grund waren viele Dinge überflüssig geworden, die zwar nicht verkäuflich waren, die man aber auch nicht wegwerfen wollte. All diese Dinge wanderten in Gregors Zimmer. Ebenso der Aschenbecher und der Mülleimer aus der Küche. Was im Augenblick unbrauchbar war, warf die Haushälterin, die es immer sehr eilig hatte, einfach in Gregors Zimmer. Gregor sah glücklicherweise meist nur den betreffenden Gegenstand und die Hand, die ihn hielt. Die Haushälterin hatte vielleicht die Absicht, bei Gelegenheit die Dinge wiederzuholen oder alles auf einmal hinauszuwerfen, aber tatsächlich blieben sie dort liegen, wo sie durch den ersten Wurf gelandet waren, es sei denn, Gregor bewegte sich durch das Gerümpel und brachte es in Bewegung. Zuerst gezwungen, weil kein anderer Platz zum Kriechen frei war, später aber mit wachsendem Vergnügen, obwohl er nach solchen Wanderungen, zum Sterben müde und traurig, wieder stundenlang regungslos blieb.

Da die Untermieter manchmal auch ihr Abendessen zu Hause im gemeinsamen Wohnzimmer einnahmen, blieb die Wohnzimmertür an manchen Abenden geschlossen. Aber Gregor verzichtete leichten Herzens auf das Öffnen der Tür; er hatte ja schon manche Abende, an denen sie geöffnet war, nicht genutzt und stattdessen, ohne dass die Familie es merkte, im dunkelsten Winkel seines Zimmers gelegen. Einmal aber hatte die Haushälterin die Tür zum Wohnzimmer einen Spalt offen gelassen, und sie blieb auch offen, als die Untermieter am Abend eintraten und Licht gemacht wurde. Sie setzten sich oben an den Tisch, wo früher der Vater, die Mutter und Gregor gesessen hatten, entfalteten die Servietten und nahmen Messer und Gabel in die Hand. Sofort erschien in der Tür die Mutter mit einer Schüssel Fleisch und knapp hinter ihr die Schwester mit einer Schüssel hoch aufgetürmter Kartoffeln. Das Essen dampfte stark. Die Untermieter beugten sich über die vor sie hingestellten Schüsseln, als wollten sie sie vor dem Essen prüfen. Tatsächlich zerschnitt derjenige, der in der Mitte saß und für die anderen beiden als Autorität galt, ein Stück Fleisch noch auf der Schüssel, offenbar um festzustellen, ob es mürbe genug sei und ob es nicht vielleicht in die Küche zurückgeschickt werden sollte. Er war zufrieden, und Mutter und Schwester, die gespannt zugesehen hatten, begannen aufatmend zu lächeln.

Die Familie selbst aß in der Küche. Trotzdem kam der Vater, bevor er in die Küche ging, in dieses Zimmer, machte mit einer einzigen Verbeugung, die Kappe in der Hand, einen Rundgang um den Tisch. Die Untermieter erhoben sich alle und murmelten etwas in ihre Bärte. Als sie dann allein waren, aßen sie fast in vollkommenem Schweigen. Seltsam schien es Gregor, dass man aus all den vielfältigen Geräuschen des Essens immer wieder ihre kauenden Zähne heraushörte, als ob damit Gregor gezeigt werden sollte, dass man Zähne braucht, um zu essen, und dass man auch mit den schönsten zahnlosen Kiefern nichts ausrichten könne. »Ich habe ja Appetit«, sagte sich Gregor sorgenvoll, »aber nicht auf diese Dinge. Wie sich diese Untermieter ernähren, und ich komme um!«

Genau an diesem Abend – Gregor erinnerte sich nicht, während der ganzen Zeit die Violine gehört zu haben – ertönte sie aus der Küche. Die Untermieter hatten schon ihr Abendessen beendet, der mittlere hatte eine Zeitung hervorgezogen, den beiden anderen je ein Blatt gegeben, und nun lasen sie zurückgelehnt und rauchten. Als die Violine zu spielen begann, wurden sie aufmerksam, erhoben sich und gingen auf Zehenspitzen zur Wohnzimmertür, in der sie zusammengedrängt stehen blieben. Man musste sie von der Küche aus gehört haben, denn der Vater rief: »Ist den Herren das Spiel vielleicht unangenehm? Es kann sofort aufhören.« »Im Gegenteil«, sagte der mittlere der Herren, »möchte die junge Dame nicht zu uns hereinkommen und hier im Zimmer spielen, wo es doch viel bequemer und gemütlicher ist?« »Oh bitte«, rief der Vater, als wäre er der Geiger. Die Herren traten ins Zimmer zurück und warteten. Bald kam der Vater mit dem Notenständer, die Mutter mit den Noten und die Schwester mit der Violine. Die Schwester bereitete alles in Ruhe zum Spielen vor. Die Eltern, die niemals zuvor Zimmer vermietet hatten und deshalb ihre Höflichkeit gegenüber den Untermietern übertrieben, wagten nicht, sich auf ihre eigenen Sessel zu setzen. Der Vater lehnte an der Tür, die rechte Hand zwischen zwei Knöpfe seiner geschlossenen Jacke gesteckt. Die Mutter aber bekam von einem Herrn einen Sessel angeboten und saß, da sie den Sessel dort ließ, wohin ihn der Herr zufällig gestellt hatte, abseits in einer Ecke.

Die Schwester begann zu spielen; Vater und Mutter verfolgten, jeder von seiner Seite, aufmerksam die Bewegungen ihrer Hände. Gregor, vom Spiel angezogen, hatte sich ein wenig weiter vorgewagt und war schon mit dem Kopf im Wohnzimmer. Er wunderte sich kaum darüber, dass er in letzter Zeit so wenig Rücksicht auf die anderen nahm; früher war diese Rücksichtnahme sein Stolz gewesen. Und dabei hätte er gerade jetzt mehr Grund gehabt, sich zu verstecken, denn infolge des Staubes, der in seinem Zimmer überall lag und bei der kleinsten Bewegung umherflog, war auch er ganz staubbedeckt. Fäden, Haare, Essensreste schleppte er auf seinem Rücken und an den Seiten mit sich herum. Seine Gleichgültigkeit gegen alles war viel zu groß, als dass er sich, wie früher mehrmals am Tag, auf den Rücken gelegt und am Teppich gerieben hätte. Und trotz dieses Zustandes hatte er keine Scheu, ein Stück auf dem makellosen Fußboden des Wohnzimmers vorzurücken.

Allerdings achtete auch niemand auf ihn. Die Familie war ganz vom Violinspiel in Anspruch genommen. Die Untermieter dagegen, die sich zunächst, die Hände in den Hosentaschen, viel zu nahe hinter dem Notenständer der Schwester aufgestellt hatten, sodass sie alle in die Noten hätten sehen können, was die Schwester sicher stören musste, zogen sich bald unter halblauten Gesprächen mit gesenkten Köpfen zum Fenster zurück, wo sie, vom Vater besorgt beobachtet, auch blieben. Es hatte nun wirklich den überdeutlichen Anschein, als wären sie in ihrer Annahme, ein schönes oder unterhaltsames Violinspiel zu hören, enttäuscht, hätten die ganze Vorführung satt und ließen sich nur aus Höflichkeit noch in ihrer Ruhe stören. Besonders die Art, wie sie alle aus Nase und Mund den Rauch ihrer Zigarren in die Höhe bliesen, ließ auf große Nervosität schließen. Und doch spielte die Schwester so schön. Ihr Gesicht war zur Seite geneigt, prüfend und traurig folgten ihre Blicke den Notenzeilen. Gregor kroch noch ein Stück vorwärts und hielt den Kopf eng an den Boden, um möglicherweise ihren Blicken begegnen zu können. War er ein Tier, dass ihn Musik so ergriff? Ihm war, als zeige sich ihm der Weg zu der ersehnten unbekannten Nahrung. Er war entschlossen, bis zur Schwester vorzudringen, sie am Rock zu zupfen und ihr dadurch anzudeuten, sie möge doch mit ihrer Violine in sein Zimmer kommen, denn niemand hier würdigte das Spiel so, wie er es würdigen wollte. Er wollte sie nicht mehr aus seinem Zimmer lassen, wenigstens nicht, solange er lebte. Seine schreckliche Gestalt sollte ihm zum ersten Mal nützlich sein. An allen Türen seines Zimmers wollte er gleichzeitig sein und den Angreifern entgegenfauchen. Die Schwester aber sollte nicht gezwungen, sondern freiwillig bei ihm bleiben. Sie sollte neben ihm auf dem Sofa sitzen, das Ohr zu ihm herabneigen, und er wollte ihr dann anvertrauen, dass er die feste Absicht gehabt hatte, sie aufs Konservatorium zu schicken, und dass er dies, wenn nicht das Unglück dazwischen gekommen wäre, letztes Weihnachten – Weihnachten war doch wohl schon vorüber? – allen gesagt hätte, ohne sich um Einwände zu kümmern. Nach dieser Mitteilung würde die Schwester in Tränen der Rührung ausbrechen, und Gregor würde sich bis zu ihrer Achsel erheben und ihren Hals küssen, den sie, seit sie ins Geschäft ging, frei von Band oder Kragen trug.

»Herr Samsa!«, rief der mittlere Herr dem Vater zu und zeigte, ohne ein weiteres Wort zu verlieren, mit dem Zeigefinger auf den sich langsam vorwärtsbewegenden Gregor. Die Violine verstummte, der mittlere Untermieter lächelte erst einmal kopfschüttelnd seinen Freunden zu und sah dann wieder auf Gregor. Der Vater schien es für nötiger zu halten, anstatt Gregor zu vertreiben, vorerst die Untermieter zu beruhigen, obwohl diese gar nicht aufgeregt waren und Gregor sie mehr als das Violinspiel zu unterhalten schien. Er eilte zu ihnen und versuchte, sie mit ausgebreiteten Armen in ihr Zimmer zu drängen und gleichzeitig mit seinem Körper ihnen den Blick auf Gregor zu versperren. Sie wurden nun tatsächlich ein wenig böse, man wusste nicht mehr, ob über das Verhalten des Vaters oder über die ihnen jetzt dämmernde Erkenntnis, ohne es zu wissen, einen solchen Zimmernachbarn wie Gregor gehabt zu haben. Sie verlangten vom Vater Erklärungen, hoben ihrerseits die Arme, zupften unruhig an ihren Bärten und wichen nur langsam in Richtung ihres Zimmers zurück. Inzwischen hatte die Schwester die Fassungslosigkeit, in die sie nach dem plötzlich abgebrochenen Spiel gefallen war, überwunden. Nachdem sie eine Zeitlang Violine und Bogen in den lässig hängenden Händen gehalten und weiter in die Noten geschaut hatte, als spiele sie noch, raffte sie sich mit einem Mal auf, legte das Instrument auf den Schoß der Mutter, die mit Atembeschwerden und heftig arbeitenden Lungen noch auf ihrem Sessel saß, und lief ins Nebenzimmer, dem sich die Untermieter unter dem Drängen des Vaters schon schneller näherten. Man sah, wie unter den geübten Händen der Schwester die Decken und Kissen in den Betten in die Höhe flogen und sich ordneten. Noch ehe die Herren das Zimmer erreicht hatten, war sie mit dem Bettenmachen fertig und schlüpfte heraus. Der Vater schien wieder so von seinem Eigensinn ergriffen zu sein, dass er jeden Respekt vergaß, den er seinen Mietern immerhin schuldete. Er drängte nur und drängte.

Der Vater wankte mit tastenden Händen zu seinem Sessel und ließ sich hineinfallen; es sah aus, als strecke er sich zu seinem gewöhnlichen Abendschläfchen, aber das starke Nicken seines wie haltlosen Kopfes zeigte, dass er ganz und gar nicht schlief. Gregor war die ganze Zeit still auf dem Platz gelegen, auf dem ihn die Untermieter ertappt hatten. Die Enttäuschung über das Misslingen seines Plans, vielleicht aber auch die durch den vielen Hunger verursachte Schwäche machten es ihm unmöglich, sich zu bewegen. Er fürchtete mit einer gewissen Bestimmtheit schon für den nächsten Augenblick einen allgemeinen Zusammenbruch, der sich über ihm entladen würde, und wartete. Nicht einmal die Violine schreckte ihn auf, die unter den zitternden Fingern der Mutter hervor von ihrem Schoß fiel und einen hallenden Ton von sich gab.

»Liebe Eltern«, sagte die Schwester und schlug zur Einleitung mit der Hand auf den Tisch, »so geht es nicht weiter. Wenn ihr das vielleicht nicht einseht, ich sehe es ein. Ich will vor diesem Ungeheuer nicht den Namen meines Bruders aussprechen und sage daher nur: Wir müssen versuchen, es loszuwerden. Wir haben das Menschenmögliche versucht, es zu pflegen und zu dulden, ich glaube, es kann uns niemand den geringsten Vorwurf machen.«

»Sie hat tausendmal recht«, sagte der Vater leise. Die Mutter, die immer noch nicht genug Luft bekam, fing mit einem irren Ausdruck in den Augen dumpf in die vorgehaltene Hand zu husten an.

Die Schwester eilte zur Mutter und hielt ihr die Stirn. Die Worte der Schwester schienen den Vater auf bestimmtere Gedanken gebracht zu haben. Er hatte sich aufgerichtet, spielte mit seiner Dienstmütze zwischen den Tellern, die noch vom Abendessen der Untermieter auf dem Tisch standen, und sah bisweilen auf den stillen Gregor.

»Wir müssen versuchen, es loszuwerden«, sagte die Schwester nun ausschließlich zum Vater, denn die Mutter hörte in ihrem Husten nichts. »Es bringt euch noch beide um, ich sehe es kommen. Wenn man schon so schwer arbeiten muss, wie wir alle, kann man nicht auch noch zu Hause diese ewige Quälerei ertragen. Ich kann es auch nicht mehr.« Und sie brach so heftig in Weinen aus, dass ihre Tränen auf das Gesicht der Mutter flossen, von dem sie sie mit mechanischen Handbewegungen wischte.

»Kind«, sagte der Vater mitleidig und mit auffallendem Verständnis, »was sollen wir aber tun?«

Die Schwester zuckte nur mit den Achseln, ein Zeichen der Ratlosigkeit, die sie nun während des Weinens im Gegensatz zu ihrer früheren Sicherheit ergriffen hatte.

»Wenn er uns verstehen würde«, sagte der Vater halb fragend. Die Schwester schüttelte im Weinen heftig die Hand, um zu zeigen, dass daran nicht zu denken sei.

»Wenn er uns verstehen würde«, wiederholte der Vater und schloss die Augen, um die Überzeugung der Schwester von der Unmöglichkeit dessen zu akzeptieren, »dann wäre vielleicht eine Vereinbarung mit ihm möglich. Aber so –«

»Es muss weg«, rief die Schwester, »das ist das einzige Mittel, Vater. Du musst nur den Gedanken loswerden, dass es Gregor ist. Dass wir das so lange geglaubt haben, das ist ja unser eigentliches Unglück. Aber wie kann es denn Gregor sein? Wenn es Gregor wäre, hätte er längst eingesehen, dass ein Zusammenleben von Menschen mit einem solchen Tier nicht möglich ist, und wäre freiwillig gegangen. Wir hätten dann keinen Bruder, aber könnten weiterleben und sein Andenken in Ehren halten. So aber verfolgt uns dieses Tier, vertreibt die Untermieter, will offenbar die ganze Wohnung für sich haben und uns auf der Straße übernachten lassen. Sieh nur, Vater«, schrie sie plötzlich auf, »er fängt schon wieder an!« Und in einem für Gregor völlig unverständlichen Schrecken verließ die Schwester sogar die Mutter, stieß sich förmlich von ihrem Sessel ab, als wollte sie lieber die Mutter opfern, als in Gregors Nähe zu bleiben, und eilte hinter den Vater, der, nur durch ihr Verhalten aufgeregt, auch aufstand und die Arme wie zum Schutz der Schwester vor ihr halb erhob.

Aber Gregor fiel es gar nicht ein, irgendjemandem und schon gar nicht seiner Schwester Angst machen zu wollen. Er hatte nur angefangen, sich umzudrehen, um in sein Zimmer zurückzukriechen, und das sah allerdings auffällig aus, da er infolge seines leidenden Zustandes bei den schwierigen Drehungen mit dem Kopf nachhelfen musste, den er dabei viele Male hob und gegen den Boden schlug. Er hielt inne und sah sich um. Seine gute Absicht schien erkannt worden zu sein; es war nur ein kurzer Schrecken gewesen. Nun sahen ihn alle schweigend und traurig an. Die Mutter lag, die Beine ausgestreckt und aneinandergedrückt, in ihrem Sessel, die Augen fielen ihr vor Erschöpfung fast zu. Vater und Schwester saßen nebeneinander, die Schwester hatte ihre Hand um den Hals des Vaters gelegt.

»Nun darf ich mich vielleicht umdrehen«, dachte Gregor und begann seine Arbeit wieder. Er konnte das Keuchen der Anstrengung nicht unterdrücken und musste auch hier und da eine Pause machen. Im Übrigen drängte ihn auch niemand, es war alles ihm selbst überlassen. Als er die Drehung vollendet hatte, begann er sofort, geradeaus zurückzukriechen. Er staunte über die große Entfernung, die ihn von seinem Zimmer trennte, und begriff gar nicht, wie er bei seiner Schwäche vor kurzer Zeit den gleichen Weg fast ohne es zu merken zurückgelegt hatte. Immer nur auf schnelles Kriechen bedacht, achtete er kaum darauf, dass kein Wort, kein Ausruf seiner Familie ihn störte. Erst als er schon in der Tür war, drehte er den Kopf, nicht vollständig, denn er fühlte den Hals steif werden, aber er sah noch, dass sich hinter ihm nichts verändert hatte, nur die Schwester war aufgestanden. Sein letzter Blick streifte die Mutter, die nun völlig eingeschlafen war.

Kaum war er in seinem Zimmer, wurde die Tür eilig zugedrückt, verriegelt und versperrt. Der plötzliche Lärm hinter ihm erschreckte Gregor so, dass ihm die Beinchen einknickten. Es war die Schwester, die sich so beeilt hatte. Aufrecht war sie schon dagestanden und hatte gewartet, leichtfüßig war sie dann vorwärtsgesprungen, Gregor hatte sie gar nicht kommen hören, und ein »Endlich!« rief sie den Eltern zu, während sie den Schlüssel im Schloss umdrehte.

»Und jetzt?«, fragte sich Gregor und sah sich im Dunkeln um. Er machte bald die Entdeckung, dass er sich nun überhaupt nicht mehr rühren konnte. Er wunderte sich darüber nicht, eher kam es ihm unnatürlich vor, dass er sich bis jetzt tatsächlich mit diesen dünnen Beinchen hatte fortbewegen können. Im Übrigen fühlte er sich verhältnismäßig wohl. Er hatte zwar Schmerzen am ganzen Körper, aber ihm war, als würden sie allmählich schwächer und schließlich ganz vergehen. Den verfaulten Apfel in seinem Rücken und die entzündete Umgebung, die ganz von weichem Staub bedeckt war, spürte er schon kaum noch. An seine Familie dachte er mit Rührung und Liebe zurück. Seine Meinung, dass er verschwinden müsse, war womöglich noch entschiedener als die seiner Schwester. In diesem Zustand leeren und friedlichen Nachdenkens blieb er, bis die Turmuhr die dritte Morgenstunde schlug. Den Beginn des allgemeinen Hellwerdens draußen vor dem Fenster erlebte er noch. Dann sank sein Kopf ohne seinen Willen ganz nach unten, und aus seinen Nüstern strömte sein letzter Atem schwach hervor.

Als am frühen Morgen die Haushälterin kam – vor lauter Kraft und Eile schlug sie, wie oft man sie auch schon gebeten hatte, das zu vermeiden, alle Türen so zu, dass in der ganzen Wohnung von ihrem Kommen an kein ruhiger Schlaf mehr möglich war –, fand sie bei ihrem gewöhnlichen kurzen Besuch bei Gregor zuerst nichts Besonderes. Sie dachte, er liege absichtlich so unbeweglich da und spiele beleidigt; sie traute ihm allen möglichen Verstand zu. Weil sie zufällig den langen Besen in der Hand hielt, versuchte sie, Gregor damit von der Tür aus zu kitzeln. Als sich auch da kein Erfolg zeigte, wurde sie ärgerlich und stieß ein wenig gegen Gregor. Erst als sie ihn ohne jeden Widerstand von seinem Platz geschoben hatte, wurde sie aufmerksam. Als sie bald die wahre Sachlage erkannte, machte sie große Augen, pfiff vor sich hin, hielt sich aber nicht lange auf, sondern riss die Tür des Schlafzimmers auf und rief mit lauter Stimme ins Dunkel: »Sehen Sie sich das an, es ist verendet; da liegt es, ganz und gar verendet!«

Das Ehepaar Samsa saß aufrecht im Ehebett und musste erst den Schrecken über die Haushälterin verwinden, bevor es ihre Meldung auffassen konnte. Dann aber stiegen Herr und Frau Samsa, jeder auf seiner Seite, eilig aus dem Bett. Herr Samsa warf die Decke über seine Schultern, Frau Samsa kam nur im Nachthemd hervor; so traten sie in Gregors Zimmer. Inzwischen hatte sich auch die Tür des Wohnzimmers geöffnet, in dem Grete seit dem Einzug der Untermieter schlief; sie war vollständig angezogen, als hätte sie gar nicht geschlafen, auch ihr bleiches Gesicht schien das zu beweisen. »Tot?«, sagte Frau Samsa und sah fragend zur Haushälterin auf, obwohl sie doch alles selbst prüfen und sogar ohne Prüfung erkennen konnte. »Das will ich meinen«, sagte die Haushälterin und stieß zum Beweis Gregors Leiche mit dem Besen noch ein großes Stück zur Seite. Frau Samsa machte eine Bewegung, als wolle sie den Besen zurückhalten, tat es aber nicht. »Nun«, sagte Herr Samsa, »jetzt können wir Gott danken.« Er bekreuzte sich, und die drei Frauen folgten seinem Beispiel. Grete, die kein Auge von der Leiche wandte, sagte: »Seht nur, wie mager er war. Er hat ja auch schon so lange nichts mehr gegessen. So wie das Essen hereinkam, ist es wieder hinausgekommen.« Tatsächlich war Gregors Körper vollständig flach und trocken. Man erkannte das eigentlich erst jetzt, da er nicht mehr von den Beinchen gehoben wurde und auch sonst nichts den Blick ablenkte.

»Komm, Grete, auf einen Moment zu uns herein«, sagte Frau Samsa mit einem wehmütigen Lächeln, und Grete ging, nicht ohne nach der Leiche zurückzusehen, hinter den Eltern ins Schlafzimmer. Die Haushälterin schloss die Tür und öffnete das Fenster ganz. Trotz des frühen Morgens war der frischen Luft schon eine gewisse Wärme beigemischt. Es war eben schon Ende März.

Aus ihrem Zimmer traten die drei Untermieter und sahen sich erstaunt nach ihrem Frühstück um; man hatte sie vergessen. »Wo ist das Frühstück?«, fragte der mittlere der Herren mürrisch die Haushälterin. Diese aber legte den Finger an den Mund und winkte dann hastig und schweigend den Herren zu, sie möchten in Gregors Zimmer kommen. Sie kamen auch und standen dann, die Hände in den Taschen ihrer etwas abgenutzten Mäntel, in dem nun schon ganz hellen Zimmer um Gregors Leiche herum.

Da öffnete sich die Tür des Schlafzimmers, und Herr Samsa erschien in seiner Uniform, an einem Arm seine Frau, am anderen seine Tochter. Alle waren ein wenig verweint; Grete drückte bisweilen ihr Gesicht an den Arm des Vaters.

»Verlassen Sie sofort meine Wohnung!«, sagte Herr Samsa und zeigte auf die Tür, ohne die Frauen von sich zu lassen. »Wie meinen Sie das?«, sagte der mittlere der Herren etwas verdutzt und lächelte süßlich. Die zwei anderen hielten die Hände auf dem Rücken und rieben sie ununterbrochen aneinander, in freudiger Erwartung eines großen Streites, der für sie aber günstig ausgehen musste. »Ich meine es genau so, wie ich es sage«, antwortete Herr Samsa und ging mit seinen beiden Begleiterinnen auf den Untermieter zu. Dieser stand zuerst still da und sah zu Boden, als ob sich die Dinge in seinem Kopf zu einer neuen Ordnung zusammenfügten. »Dann gehen wir also«, sagte er dann und sah zu Herrn Samsa auf, als verlange er in einer plötzlich ihn überkommenden Demut sogar für diesen Entschluss eine neue Genehmigung. Herr Samsa nickte ihm nur mehrmals kurz mit großen Augen zu. Daraufhin ging der Herr tatsächlich sofort mit langen Schritten ins Vorzimmer. Seine beiden Freunde hatten schon eine Weile mit ruhigen Händen aufgehorcht und hüpften ihm jetzt geradezu nach, aus Angst, Herr Samsa könnte vor ihnen ins Vorzimmer eintreten und die Verbindung mit ihrem Anführer stören. Im Vorzimmer nahmen alle drei ihre Hüte vom Kleiderständer, zogen ihre Stöcke aus dem Ständer, verbeugten sich stumm und verließen die Wohnung. In einem, wie sich zeigte, völlig unbegründeten Misstrauen trat Herr Samsa mit den beiden Frauen auf den Treppenabsatz hinaus. An das Geländer gelehnt, sahen sie zu, wie die drei Herren zwar langsam, aber stetig die lange Treppe hinabstiegen, in jedem Stockwerk in einer bestimmten Biegung des Treppenhauses verschwanden und nach ein paar Augenblicken wieder hervorkamen. Je tiefer sie kamen, desto mehr verlor sich das Interesse der Familie Samsa für sie, und als ihnen ein Metzgergeselle mit einer Kiste auf dem Kopf in stolzer Haltung entgegenkam und dann hoch über ihnen hinwegstieg, verließen Herr Samsa und die Frauen bald das Geländer und gingen, als wären sie erleichtert, zurück in die Wohnung.

Sie beschlossen, den heutigen Tag zum Ausruhen und Spazierengehen zu nutzen. Sie hatten diese Arbeitspause nicht nur verdient, sie brauchten sie sogar unbedingt. Und so setzten sie sich an den Tisch und schrieben drei Entschuldigungsbriefe: Herr Samsa an seine Direktion, Frau Samsa an ihren Auftraggeber und Grete an ihren Chef. Während des Schreibens kam die Haushälterin herein, um zu sagen, dass sie gehe, denn ihre Morgenarbeit sei beendet. Die drei Schreibenden nickten zuerst nur, ohne aufzuschauen. Erst als die Haushälterin sich immer noch nicht entfernen wollte, sah man ärgerlich auf. »Nun?«, fragte Herr Samsa. Die Haushälterin stand lächelnd in der Tür, als habe sie der Familie eine großartige Neuigkeit zu verkünden, würde es aber nur tun, wenn sie gründlich ausgefragt würde. Die fast aufrechte kleine Straußenfeder auf ihrem Hut, über die sich Herr Samsa schon während ihrer ganzen Dienstzeit geärgert hatte, schwankte leicht in alle Richtungen. »Also, was wollen Sie eigentlich?«, fragte Frau Samsa, vor der die Haushälterin noch am meisten Respekt hatte. »Nun«, antwortete die Haushälterin und konnte vor freundlichem Lachen nicht gleich weiterreden, »darüber, wie das Zeug von nebenan weggeschafft werden soll, müssen Sie sich keine Sorgen machen. Es ist schon alles erledigt.« Frau Samsa und Grete beugten sich zu ihren Briefen nieder, als wollten sie weiterschreiben. Herr Samsa, der merkte, dass die Haushälterin nun alles ausführlich beschreiben wollte, wehrte dies mit ausgestreckter Hand entschieden ab. Da sie aber nicht erzählen durfte, erinnerte sie sich an ihre große Eile, rief offenbar beleidigt: »Tschüs zusammen!«, drehte sich wild um und verließ unter fürchterlichem Türenknallen die Wohnung.

»Abends wird sie entlassen«, sagte Herr Samsa, bekam aber weder von seiner Frau noch von seiner Tochter eine Antwort, denn die Haushälterin schien ihre kaum gewonnene Ruhe wieder gestört zu haben. Sie erhoben sich, gingen zum Fenster und blieben dort, sich umarmend. Herr Samsa drehte sich in seinem Sessel zu ihnen um und beobachtete sie eine Weile still. Dann rief er: »Also, kommt doch her. Lasst endlich die alten Sorgen ruhen. Und nehmt auch ein wenig Rücksicht auf mich.« Sogleich folgten ihm die Frauen, eilten zu ihm, liebkosten ihn und beendeten rasch ihre Briefe.

Dann verließen alle drei gemeinsam die Wohnung, was sie schon seit Monaten nicht mehr getan hatten, und fuhren mit der Straßenbahn ins Grüne vor die Stadt. Der Wagen, in dem sie allein saßen, war ganz von warmer Sonne durchflutet. Sie besprachen, bequem auf ihren Sitzen zurückgelehnt, die Aussichten für die Zukunft und fanden, dass diese bei näherer Betrachtung durchaus nicht schlecht waren, denn alle drei Anstellungen waren, worüber sie sich eigentlich noch gar nicht ausgetauscht hatten, überaus günstig und besonders für später vielversprechend. Die größte sofortige Verbesserung der Lage musste sich natürlich leicht durch einen Wohnungswechsel ergeben. Sie wollten nun eine kleinere und billigere, aber besser gelegene und überhaupt praktischere Wohnung nehmen, als die jetzige, die noch von Gregor ausgesucht worden war. Während sie sich so unterhielten, fiel Herrn und Frau Samsa beim Anblick ihrer immer lebhafter werdenden Tochter fast gleichzeitig auf, wie sie in der letzten Zeit, trotz aller Sorgen, die ihre Wangen blass gemacht hatten, zu einem schönen und blühenden Mädchen herangewachsen war. Stiller werdend und sich fast unbewusst durch Blicke verständigend, dachten sie daran, dass es nun an der Zeit wäre, auch einen anständigen Mann für sie zu suchen. Und es war ihnen wie eine Bestätigung ihrer neuen Träume und guten Absichten, als am Ziel ihrer Fahrt die Tochter als Erste aufstand und ihren jungen Körper streckte.`,
}
