services:
  explainnginxlocaltest:
    image: nginx:1.19.7-alpine
    container_name: explainnginxlocaltest
    depends_on:
      - explainfacelocaltest
      - explainserverlocaltest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.localtest:/etc/nginx/nginx.conf
  explainserverlocaltest:
    build:
      context: server/
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./server/src:/app/src
      - ./server/e2e:/app/e2e
    command: yarn start:dev
    container_name: explainserverlocaltest
    environment:
      MODE: localtest
      PORT: 3001
    env_file:
      - .env
    ports:
      - 3001:3001
  explainfacelocaltest:
    build:
      context: face/
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./face:/app
      - ./face:/public
    command: yarn run dev
    container_name: explainfacelocaltest
    depends_on:
      - explainserverlocaltest
    environment:
      MODE: localtest
