services:
  explainnginx:
    image: nginx:1.19.7-alpine
    container_name: explain-nginx
    depends_on:
      - explainface
      - explainserver
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: explainit.ru,www.explainit.ru
      LETSENCRYPT_HOST: explainit.ru,www.explainit.ru
  explainserver:
    build:
      context: server/
      dockerfile: Dockerfile.server
    restart: unless-stopped
    command: yarn start:prod
    container_name: explain-server
    environment:
      MODE: publish
      PORT: 3001
    env_file:
      - .env
  explainface:
    build:
      context: face/
      dockerfile: Dockerfile.server
    restart: unless-stopped
    command: yarn run start
    container_name: explain-face
    depends_on:
      - explainserver
    environment:
      MODE: publish
