version: "3.8"
services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: explain-nginx
    depends_on:
      - face
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: explainit.ru,www.explainit.ru
      LETSENCRYPT_HOST: explainit.ru,www.explainit.ru
  face:
    build:
      context: face/
      dockerfile: Dockerfile.server
    restart: unless-stopped
    command: yarn run start
    container_name: explain-face
    environment: {}
networks:
  default:
    external:
      name: nginx-proxy
