services:
  explainnginxserverdevelop:
    image: nginx:1.19.7-alpine
    container_name: explainnginxserverdevelop
    depends_on:
      - explainserverserverdevelop
    volumes:
      - ./nginx/nginx.conf.serverdevelop:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: dev.explainit.ru,www.dev.explainit.ru
      LETSENCRYPT_HOST: dev.explainit.ru,www.dev.explainit.ru
  explainserverserverdevelop:
    build:
      context: server/
      dockerfile: Dockerfile.server
    restart: unless-stopped
    command: npm start:prod
    container_name: explainserverserverdevelop
    environment:
      MODE: serverdevelop
      PORT: 3001
    env_file:
      - .env.server.develop
networks:
  default:
    external: true
    name: nginx-proxy
