services:
  explainnginxlocaldev:
    image: nginx:1.19.7-alpine
    container_name: explainnginxlocaldev
    depends_on:
      - explainfacelocaldev
      - explainserverlocaldev
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.localdev:/etc/nginx/nginx.conf
  explainserverlocaldev:
    build:
      context: server/
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./server/src:/app/src
      - ./server/e2e:/app/e2e
    command: yarn start:dev
    container_name: explainserverlocaldev
    environment:
      MODE: localdev
      PORT: 3001
    env_file:
      - .env
    ports:
      - 3001:3001
  explainfacelocaldev:
    build:
      context: face/
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./face:/app
      - ./face:/public
    command: yarn run dev
    container_name: explainfacelocaldev
    depends_on:
      - explainserverlocaldev
    environment:
      MODE: localdev
