services:
  explainnginxlocalcheckserver:
    image: nginx:1.19.7-alpine
    container_name: explainnginxlocalcheckserver
    depends_on:
      - explainpostgreslocalcheckserver
      - explainserverlocalcheckserver
      - explainfacelocalcheckserver
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.localcheckserver:/etc/nginx/nginx.conf
  explainpostgreslocalcheckserver:
    image: postgres:16.2
    restart: unless-stopped
    container_name: explainpostgreslocalcheckserver
    ports:
      - 5445:5432
    environment:
      POSTGRES_CONTAINER: ${POSTGRES_CONTAINER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env.localcheckserver
    volumes:
      - pgdata:/var/lib/postgresql/data
  explainredislocalcheckserver:
    image: redis:7.4.4
    restart: unless-stopped
    container_name: explainredislocalcheckserver
    ports:
      - 6382:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    env_file:
      - .env.localcheckserver
    volumes:
      - redis_data:/data
  explainserverlocalcheckserver:
    build:
      context: server/
      dockerfile: Dockerfile.server
    restart: unless-stopped
    command: yarn start:prod
    container_name: explainserverlocalcheckserver
    depends_on:
      - explainpostgreslocalcheckserver
    environment:
      MODE: localcheckserver
      PORT: 3001
    env_file:
      - .env.localcheckserver
  explainfacelocalcheckserver:
    build:
      context: face/
      dockerfile: Dockerfile.server
    restart: unless-stopped
    command: yarn run start
    container_name: explainfacelocalcheckserver
    depends_on:
      - explainpostgreslocalcheckserver
      - explainserverlocalcheckserver
    environment:
      MODE: localcheckserver
volumes:
  pgdata: {}
  redis_data: {}
