services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: explain-nginx
    depends_on:
      - face
      - server
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf
  server:
    build:
      context: server/
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./server/src:/app/src
    command: yarn start:dev
    container_name: explain-server
    environment:
      MODE: dev
      PORT: 3001
    ports:
      - 3001:3001
  face:
    build:
      context: face/
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./face:/app
      - ./face:/public
    command: yarn run dev
    container_name: explain-face
    depends_on:
      - server
    environment: {}
