services:
  explainnginxlocaldev:
    image: nginx:1.19.7-alpine
    container_name: explainnginxlocaldev
    depends_on:
      - explainpostgreslocaldev
      - explainserverlocaldev
      - explainfacelocaldev
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.localdev:/etc/nginx/nginx.conf
  explainpostgreslocaldev:
    image: postgres:16.2
    restart: unless-stopped
    container_name: explainpostgreslocaldev
    ports:
      - 5443:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env.localdev
    volumes:
      - pgdata:/var/lib/postgresql/data
  explainredislocaldev:
    image: redis:7.4.4
    restart: unless-stopped
    container_name: explainredislocaldev
    ports:
      - 6381:6379
    env_file:
      - .env.localdev
    volumes:
      - redis_data:/data
  explainserverlocaldev:
    build:
      context: server/
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./server/src:/app/src
      - ./server/e2e:/app/e2e
    command: npm run start:dev
    container_name: explainserverlocaldev
    depends_on:
      - explainpostgreslocaldev
    environment:
      MODE: localdev
      PORT: 3001
    env_file:
      - .env.localdev
    ports:
      - 3001:3001
  explainfacelocaldev:
    build:
      context: face/
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./face:/app
      - ./face:/public
    command: npm run dev
    container_name: explainfacelocaldev
    depends_on:
      - explainpostgreslocaldev
      - explainserverlocaldev
    environment:
      MODE: localdev
volumes:
  pgdata: {}
  redis_data: {}
