services:
  explainnginxlocalcheckserver:
    image: nginx:1.19.7-alpine
    container_name: explainnginxlocalcheckserver
    depends_on:
      - explainfacelocalcheckserver
      - explainserverlocalcheckserver
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.localcheckserver:/etc/nginx/nginx.conf
  explainserverlocalcheckserver:
    build:
      context: server/
      dockerfile: Dockerfile.server
    restart: unless-stopped
    command: yarn start:prod
    container_name: explainserverlocalcheckserver
    environment:
      MODE: localcheckserver
      PORT: 3001
    env_file:
      - .env
  explainfacelocalcheckserver:
    build:
      context: face/
      dockerfile: Dockerfile.server
    restart: unless-stopped
    command: yarn run start
    container_name: explainfacelocalcheckserver
    depends_on:
      - explainserverlocalcheckserver
    environment:
      MODE: localcheckserver
