services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: explain-nginx
    depends_on:
      - face
      - server
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf
  server:
    build:
      context: server/
      dockerfile: Dockerfile.server
    restart: unless-stopped
    volumes:
      - ./server/src:/app/src
    command: yarn start:prod
    container_name: explain-server
    environment:
      MODE: server
      PORT: 3001
    env_file:
      - .env
  face:
    build:
      context: face/
      dockerfile: Dockerfile.server
    restart: unless-stopped
    command: yarn run start
    container_name: explain-face
    depends_on:
      - server
    environment: {}
