// Адаптированный текст
export const chapter_24 = {
	name: 'Capítulo XXIV',
	header: 'Donde se prosigue la aventura de la Sierra Morena',
	text: `Dice la historia que don Quijote escuchaba con grandísima atención al andrajoso Caballero de la Sierra, el cual, continuando su conversación, dijo:

—Por cierto, señor, quienquiera que seáis, que no os conozco, os agradezco las muestras de cortesía que conmigo habéis usado. Quisiera encontrarme en condiciones de poder serviros con más que mi buena voluntad, en respuesta al buen recibimiento que me habéis dado. Mas mi suerte no quiere darme otra cosa para corresponder a las buenas obras que me hacen, que no sean buenos deseos de satisfacerlas.

—Los que yo tengo —respondió don Quijote— son de serviros. Tanto, que tenía decidido no salir de estas sierras hasta encontraros y saber de vos si el dolor que mostráis tener con la rareza de vuestra vida se podía remediar de alguna manera. Y si fuera necesario buscarlo, buscarlo con toda la diligencia posible. Y si vuestra desventura fuera de aquellas que tienen cerradas las puertas a todo consuelo, pensaba ayudaros a llorarla y lamentarla como mejor pudiera. Que todavía es un consuelo en las desgracias encontrar quien se duela de ellas. Y si mi buen intento merece ser agradecido con alguna cortesía, os suplico, señor, por la mucha que veo que en vos se encierra, y juntamente os conjuro por la cosa que en esta vida más habéis amado o amáis, que me digáis quién sois y la causa que os ha traído a vivir y a morir entre estas soledades como un animal salvaje. Pues vivís entre ellos, tan ajeno de vos mismo como lo muestra vuestro traje y persona. Y juro —añadió don Quijote—, por la orden de caballería que recibí, aunque indigno y pecador, y por la profesión de caballero andante, que si en esto, señor, me complacéis, os serviré con la seriedad a que me obliga el ser quien soy: ya sea remediando vuestra desgracia, si tiene remedio, o ayudándoos a llorarla, como os lo he prometido.

El Caballero del Bosque, que oyó hablar de tal manera al de la Triste Figura, no hacía sino mirarlo, y volver a mirarlo, y mirarlo de nuevo de arriba abajo. Y después de haberlo mirado bien, le dijo:

—Si tienen algo que darme de comer, por amor de Dios que me lo den. Que, después de haber comido, yo haré todo lo que se me manda, en agradecimiento por tan buenos deseos como aquí se me han mostrado.

Luego, Sancho de su saco y el cabrero de su morral sacaron con qué el Roto satisfizo su hambre. Comió lo que le dieron como una persona aturdida, tan deprisa que no daba espacio entre un bocado y otro, pues antes los engullía que los tragaba. Y mientras comía, ni él ni los que lo miraban hablaban. Cuando acabó de comer, les hizo señas de que lo siguieran. Así lo hicieron, y él los llevó a un prado verde que estaba al dar la vuelta a una roca, no muy lejos de allí. Al llegar, se tendió en el suelo, sobre la hierba, y los demás hicieron lo mismo. Y todo esto sin que ninguno hablara, hasta que el Roto, después de haberse acomodado, dijo:

—Si gustáis, señores, que os diga en breves palabras la inmensidad de mis desventuras, me habéis de prometer que con ninguna pregunta ni otra cosa interrumpiréis el hilo de mi triste historia. Porque en el punto en que lo hagáis, en ese se quedará lo que fuera contando.

Estas palabras del Roto trajeron a la memoria de don Quijote el cuento que le había contado su escudero, cuando no acertó el número de las cabras que habían pasado el río y la historia quedó pendiente. Pero, volviendo al Roto, prosiguió diciendo:

—Hago esta advertencia porque querría pasar brevemente por el relato de mis desgracias. Traerlas a la memoria no me sirve de otra cosa que añadir otras nuevas, y mientras menos me preguntéis, más pronto acabaré yo de decirlas, aunque no dejaré de contar nada que sea importante para satisfacer del todo vuestro deseo.

Don Quijote se lo prometió en nombre de los demás. Y él, con esta seguridad, comenzó de esta manera:

—Mi nombre es Cardenio; mi patria, una de las mejores ciudades de esta Andalucía; mi linaje, noble; mis padres, ricos; mi desventura, tanta que la deben de haber llorado mis padres y sentido mi linaje, sin poderla aliviar con su riqueza. Porque para remediar las desgracias del cielo, poco suelen valer los bienes de fortuna. Vivía en esta misma tierra un cielo, donde el amor puso toda la gloria que yo pudiera desear: tal es la hermosura de Luscinda, doncella tan noble y tan rica como yo, pero con más suerte y menos firmeza de la que se debía a mis honrados pensamientos. A esta Luscinda amé, quise y adoré desde mis tiernos y primeros años, y ella me quiso a mí con aquella sencillez y buen ánimo que su poca edad permitía. Nuestros padres sabían de nuestras intenciones y no les pesaba, porque veían que, cuando avanzaran, no podían tener otro fin que el de casarnos, cosa que casi la aseguraba la igualdad de nuestro linaje y riquezas. Creció la edad, y con ella el amor de ambos. Al padre de Luscinda le pareció que, por buenas consideraciones, estaba obligado a negarme la entrada a su casa, casi imitando en esto a los padres de aquella Tisbe tan famosa entre los poetas. Y esta negación fue como añadir leña al fuego y deseo al deseo. Porque, aunque pusieron silencio a las lenguas, no pudieron ponérselo a las plumas, las cuales, con más libertad que las lenguas, suelen dar a entender a quien quieren lo que está encerrado en el alma. Muchas veces, la presencia de la persona amada turba y enmudece la intención más determinada y la lengua más atrevida. ¡Ay, cielos, y cuántas cartas le escribí! ¡Cuán afectuosas y honestas respuestas tuve! ¡Cuántas canciones compuse y cuántos versos enamorados, donde el alma declaraba y trasladaba sus sentimientos, pintaba sus encendidos deseos, entretenía sus memorias y recreaba su voluntad!

»En efecto, viéndome apurado y que mi alma se consumía con el deseo de verla, decidí poner en práctica y acabar de una vez lo que me pareció que más convenía para conseguir mi deseado y merecido premio. Y fue el pedírsela a su padre como legítima esposa, como lo hice. A lo que él me respondió que me agradecía la voluntad que mostraba de honrarlo, y de querer honrarme con miembros de su familia, pero que, siendo mi padre vivo, a él le correspondía por justo derecho hacer aquella petición. Porque, si no fuera con mucha voluntad y gusto suyo, Luscinda no era mujer para tomarse ni darse a escondidas.

»Le agradecí su buena intención, pareciéndome que tenía razón en lo que decía, y que mi padre estaría de acuerdo en cuanto se lo dijera. Con esta intención, en aquel mismo instante, fui a decirle a mi padre lo que deseaba. Y al tiempo que entré en una habitación donde estaba, lo encontré con una carta abierta en la mano. Antes de que yo le dijera palabra, me la dio y me dijo: ''Por esa carta verás, Cardenio, la voluntad que el duque Ricardo tiene de hacerte un favor''.» Este duque Ricardo, como ya vosotros, señores, debéis de saber, es un grande de España que tiene su estado en lo mejor de esta Andalucía. «Tomé y leí la carta, la cual venía tan llena de elogios que a mí mismo me pareció mal si mi padre dejaba de cumplir lo que en ella se le pedía. Era que me enviara enseguida a donde él estaba; quería que fuera compañero, no criado, de su hijo el mayor, y que él se encargaba de ponerme en un estado que correspondiera a la estima en que me tenía. Leí la carta y enmudecí al leerla, y más cuando oí que mi padre me decía: ''De aquí a dos días te partirás, Cardenio, a hacer la voluntad del duque; y da gracias a Dios que te va abriendo camino por donde alcances lo que yo sé que mereces''. Añadió a estas otras razones de padre consejero. »Llegó el plazo de mi partida, hablé una noche con Luscinda, le conté todo lo que pasaba, y lo mismo hice con su padre, suplicándole que esperara algunos días y retrasara su boda hasta que yo viera lo que Ricardo me quería. Él me lo prometió y ella me lo confirmó con mil juramentos y mil desmayos. Fui, en fin, a donde estaba el duque Ricardo. Fui por él tan bien recibido y tratado que desde el principio la envidia comenzó a hacer su oficio, teniéndomela los criados antiguos, pareciéndoles que las muestras que el duque daba de favorecerme serían en perjuicio suyo. Pero el que más se alegró con mi llegada fue un hijo segundo del duque, llamado Fernando, un joven gallardo, gentilhombre, liberal y enamorado, el cual, en poco tiempo, quiso que fuéramos tan amigos que todos hablaban de ello. Y aunque el hermano mayor me quería bien y me hacía favores, no llegaba al extremo con que don Fernando me quería y trataba. 

»Es el caso que, como entre los amigos no hay secreto que no se comunique, y la intimidad que yo tenía con don Fernando ya era de amistad, me declaraba todos sus pensamientos, especialmente uno de amoroso que lo traía con un poco de inquietud. Quería mucho a una labradora, vasalla de su padre (y ella tenía padres muy ricos), y era tan hermosa, recatada, discreta y honesta que nadie que la conocía se decidía en cuál de estas cosas tenía más excelencia. Estas tan buenas cualidades de la hermosa labradora llevaron los deseos de don Fernando a tal punto que se decidió, para poder alcanzar su objetivo y conquistar la integridad de la labradora, a darle palabra de ser su esposo, porque de otra manera era intentar lo imposible. Yo, obligado por su amistad, con las mejores razones que supe y con los ejemplos más vivos que pude, intenté disuadirlo de tal propósito. Pero, viendo que no servía de nada, decidí contarle el caso al duque Ricardo, su padre. Mas don Fernando, como astuto y discreto, se receló y temió de esto, pareciéndole que yo estaba obligado, como buen criado, a no tener encubierta una cosa que venía tan en perjuicio del honor de mi señor el duque. Y así, para distraerme y engañarme, me dijo que no encontraba otro mejor remedio para poder apartar de la memoria la hermosura que tan sujeto lo tenía, que ausentarse por algunos meses. Y que quería que la ausencia fuera que los dos nos viniéramos a casa de mi padre, con la excusa que darían al duque de que venía a ver y a comprar unos muy buenos caballos que en mi ciudad había, que es madre de los mejores del mundo.

»Apenas le oí decir esto, cuando, movido por mi afición, aunque su decisión no fuera tan buena, la aprobé como una de las más acertadas que se podían imaginar, por ver qué buena ocasión y oportunidad se me ofrecía de volver a ver a mi Luscinda. Con este pensamiento y deseo, aprobé su parecer y reforcé su propósito, diciéndole que lo pusiera en práctica con la mayor brevedad posible, porque, en efecto, la ausencia hacía su oficio, a pesar de los más firmes pensamientos. Ya cuando él me vino a decir esto, según se supo después, había gozado de la labradora con título de esposo, y esperaba ocasión de revelarlo sin peligro, temeroso de lo que el duque su padre haría cuando supiera su disparate.

»Sucedió, pues, que, como el amor en los jóvenes, en su mayor parte, no es amor sino apetito, el cual, como tiene por último fin el deleite, al alcanzarlo se acaba y tiene que retroceder, porque no puede pasar adelante del término que le puso la naturaleza, término que no le puso a lo que es verdadero amor...; quiero decir que, en cuanto don Fernando gozó de la labradora, se le aplacaron sus deseos y se enfriaron sus insistencias. Y si primero fingía querer ausentarse para remediarlos, ahora de veras procuraba irse para no ponerlos en práctica. El duque le dio licencia y me mandó que lo acompañara. Vinimos a mi ciudad, mi padre lo recibió como quien era; vi yo luego a Luscinda, volvieron a vivir, aunque no habían estado muertos ni amortiguados, mis deseos. De los cuales di cuenta, para mi mal, a don Fernando, por parecerme que, en la ley de la mucha amistad que mostraba, no le debía ocultar nada. Le alabé la hermosura, la gracia y la inteligencia de Luscinda de tal manera, que mis alabanzas movieron en él los deseos de querer ver a una doncella adornada de tan buenas cualidades. Se los cumplí, por mi corta suerte, enseñándosela una noche, a la luz de una vela, por una ventana por donde los dos solíamos hablarnos. La vio con un vestido sencillo, tal, que todas las bellezas que él había visto hasta entonces las puso en olvido. Enmudeció, perdió el sentido, quedó absorto y, finalmente, tan enamorado como veréis en el transcurso del relato de mi desventura. Y para encenderle más el deseo, que a mí me ocultaba y al cielo a solas descubría, quiso la fortuna que encontrara un día una carta suya pidiéndome que la pidiera a su padre como esposa, tan discreta, tan honesta y tan enamorada que, al leerla, me dijo que solo en Luscinda se encerraban todas las gracias de hermosura y de entendimiento que en las demás mujeres del mundo estaban repartidas.

»Bien es verdad que quiero confesar ahora que, aunque yo veía con cuán justas causas don Fernando a Luscinda alababa, me pesaba oír aquellas alabanzas de su boca, y comencé a temer y a recelarme de él. Porque no pasaba un momento sin que quisiera que habláramos de Luscinda, y él movía la conversación, aunque la trajera a colación de forma forzada. Cosa que despertaba en mí un no sé qué de celos, no porque yo temiera algún contratiempo por parte de la bondad y de la fe de Luscinda, pero, con todo, mi suerte me hacía temer lo mismo que ella me aseguraba. Don Fernando procuraba siempre leer los papeles que yo a Luscinda enviaba y los que ella me respondía, con el pretexto de que le gustaba mucho la inteligencia de ambos. Sucedió, pues, que, habiéndome pedido Luscinda un libro de caballerías para leer, del que era ella muy aficionada, que era el de "Amadís de Gaula"...»

No bien hubo oído don Quijote nombrar un libro de caballerías, cuando dijo:
—Si me hubiera dicho usted, al principio de su historia, que la señora Luscinda era aficionada a libros de caballerías, no habría sido necesaria otra exageración para darme a entender la alteza de su entendimiento. Porque no lo tendría tan bueno como usted, señor, lo ha pintado, si careciera del gusto de tan sabrosa lectura. Así que, para mí, no es necesario gastar más palabras en declararme su hermosura, valor y entendimiento. Con solo haber entendido su afición, la confirmo como la mujer más hermosa y más discreta del mundo. Y quisiera yo, señor, que usted le hubiera enviado junto con "Amadís de Gaula" al bueno de "Don Rugel de Grecia". Yo sé que a la señora Luscinda le gustaría mucho Daraida y Garaya, y las discreciones del pastor Darinel y aquellos admirables versos de sus bucólicas, cantadas y representadas por él con toda gracia, inteligencia y naturalidad. Pero tiempo podrá venir en que se enmiende esa falta, y no se tarda más en hacer la corrección que lo que quiera usted tardar en venir conmigo a mi aldea. Allí le podré dar más de trescientos libros, que son el regalo de mi alma y el entretenimiento de mi vida. Aunque creo que ya no tengo ninguno, gracias a la malicia de malos y envidiosos encantadores. Y perdóneme usted por haber contravenido a lo que prometimos de no interrumpir su conversación. Pues, al oír cosas de caballerías y de caballeros andantes, está tan fuera de mi mano dejar de hablar de ellos como lo está en la de los rayos del sol dejar de calentar, ni en los de la luna de humedecer. Así que, perdón y prosiga, que es lo que ahora más importa.

Mientras don Quijote decía lo que queda dicho, a Cardenio se le había caído la cabeza sobre el pecho, dando muestras de estar profundamente pensativo. Y aunque don Quijote le dijo dos veces que prosiguiera su historia, ni alzaba la cabeza ni respondía palabra. Pero, al cabo de un buen rato, la levantó y dijo:

—No se me puede quitar del pensamiento, ni habrá quien me lo quite en el mundo, ni quien me haga entender otra cosa (y sería un necio el que lo contrario entendiera o creyera), sino que aquel granuja del maestro Elisabat estaba amancebado con la reina Madásima.

—¡Eso no, voto a tal! —respondió con mucha cólera don Quijote (y lo dijo con la vehemencia que acostumbraba)—. Y esa es una muy gran malicia, o bellaquería, por mejor decir. La reina Madásima fue una señora muy principal, y no se ha de presumir que tan alta princesa se hubiera de amancebar con un sacamuelas. Y quien lo contrario entienda, miente como un granuja. Y yo se lo daré a entender, a pie o a caballo, armado o desarmado, de noche o de día, o como más le guste.

Cardenio lo estaba mirando muy atentamente, al cual ya le había venido el ataque de su locura y no estaba para proseguir su historia. Ni tampoco don Quijote se la oyera, de tan disgustado que estaba por lo que de Madásima había oído. ¡Extraño caso, que así la defendía como si verdaderamente fuera su señora verdadera y natural: tal lo tenían sus malditos libros! Digo, pues, que como ya Cardenio estaba loco y se oyó tratar de mentiroso y de granuja, con otros insultos semejantes, la broma le pareció mal. Alzó una piedra que encontró junto a sí y le dio con ella en el pecho un golpe tan fuerte a don Quijote que lo hizo caer de espaldas. Sancho Panza, que vio caer así a su señor, arremetió contra el loco con el puño cerrado. Y el Roto lo recibió de tal suerte que con un puñetazo lo tiró a sus pies, y luego se subió sobre él y le golpeó las costillas muy a su gusto. El cabrero, que quiso defenderlo, corrió el mismo peligro. Y después de que los tuvo a todos rendidos y molidos, los dejó y se fue, con tranquila calma, a esconderse en la montaña.

Se levantó Sancho y, con la rabia que tenía de verse golpeado tan sin merecerlo, acudió a tomar venganza del cabrero, diciéndole que él tenía la culpa de no haberles avisado de que a aquel hombre le daban ataques de locura a veces. Que si lo hubieran sabido, habrían estado sobre aviso para poderse proteger. Respondió el cabrero que ya lo había dicho, y que si él no lo había oído, no era suya la culpa. Sancho Panza replicó, y el cabrero volvió a replicar. Y el fin de las réplicas fue agarrarse de las barbas y darse tales puñetazos que, si don Quijote no los hubiera puesto en paz, se habrían hecho pedazos. Sancho, agarrado al cabrero, decía:

—Déjeme usted, señor Caballero de la Triste Figura, que en este, que es un villano como yo y no está armado caballero, bien puedo, sin riesgo para mí, satisfacerme del agravio que me ha hecho, peleando con él mano a mano, como un hombre honrado.

—Así es —dijo don Quijote—, pero yo sé que él no tiene ninguna culpa de lo sucedido.

Con esto los apaciguó. Y don Quijote volvió a preguntar al cabrero si sería posible encontrar a Cardenio, porque le quedaba un grandísimo deseo de saber el fin de su historia. El cabrero le dijo lo que primero le había dicho: que no sabía con certeza su paradero, pero que si anduviera mucho por aquellos contornos, no dejaría de encontrarlo, ya fuera cuerdo o loco.`,
}
