export const chapter_16 = {
	name: 'Capítulo XVI',
	header: 'De lo que le sucedió al ingenioso hidalgo en la venta que él imaginaba ser castillo',
	text: `El posadero, que vio a don Quijote atravesado sobre el burro, le preguntó a Sancho qué mal traía. Sancho le respondió que no era nada, solo que se había caído de una roca y que venía con las costillas algo magulladas. El posadero tenía por mujer a una persona que no era como suelen ser las de su oficio; era caritativa por naturaleza y se compadecía de las calamidades de sus prójimos. Por eso, acudió enseguida a curar a don Quijote. Hizo que una hija suya, una joven muchacha de muy buen parecer, la ayudara a cuidar a su huésped.

Servía también en la posada una joven asturiana, ancha de cara, de cuello corto, de nariz chata, tuerta de un ojo y del otro no muy sana. La verdad es que la buena figura de su cuerpo compensaba las demás faltas: no medía más de un metro y medio de altura, y la espalda, que la tenía algo cargada, la hacía mirar al suelo más de lo que ella quisiera. Esta amable muchacha, pues, ayudó a la joven, y las dos le hicieron una cama muy mala a don Quijote en un desván que, en otros tiempos, claramente había servido de pajar durante muchos años.

En ese mismo lugar también se alojaba un arriero, que tenía su cama hecha un poco más allá de la de nuestro don Quijote. Y aunque su cama estaba hecha con los aparejos y las mantas de sus mulas, era mucho mejor que la de don Quijote. La de él solo consistía en cuatro tablas mal lisas sobre dos bancos no muy iguales, y un colchón que, de tan delgado, parecía una colcha, lleno de grumos. Si no fuera porque por algunas roturas se veía que eran de lana, al tacto, por su dureza, parecían de piedra. Tenía dos sábanas hechas de cuero de escudo y una manta cuyos hilos, si se quisieran contar, no se perdería ni uno solo.

En esta maldita cama se acostó don Quijote. Luego, la posadera y su hija le aplicaron emplastos de arriba abajo, mientras las alumbraba Maritornes, que así se llamaba la asturiana. Al aplicarle los emplastos, la posadera vio a don Quijote tan lleno de cardenales por todas partes, que dijo que aquello parecían más golpes que una caída.

—No fueron golpes —dijo Sancho—, sino que la roca tenía muchos picos y salientes, y cada uno le hizo un cardenal. Y también le dijo: —Haga usted, señora, que queden algunas vendas, que no faltará quien las necesite, porque también a mí me duele un poco la espalda.

—De esa manera —respondió la posadera—, también usted debió de caerse.

—No me caí —dijo Sancho Panza—, sino que del susto que me llevé al ver caer a mi amo, me duele tanto el cuerpo que parece que me han dado mil palos.

—Bien podría ser eso —dijo la joven—. A mí me ha pasado muchas veces que sueño que me caigo de una torre y que nunca acabo de llegar al suelo. Y al despertar, me encuentro tan adolorida y agotada como si de verdad me hubiera caído.

—Ahí está el punto, señora —respondió Sancho Panza—. Que yo, sin soñar nada, estando más despierto que ahora, me encuentro con casi tantos cardenales como mi señor don Quijote.

—¿Cómo se llama este caballero? —preguntó la asturiana Maritornes.

—Don Quijote de la Mancha —respondió Sancho Panza—. Y es un caballero aventurero, de los mejores y más fuertes que se han visto en el mundo en mucho tiempo.

—¿Qué es un caballero aventurero? —replicó la moza.

—¿Tan nueva sois en el mundo que no lo sabéis? —respondió Sancho Panza—. Pues sabed, hermana mía, que un caballero aventurero es alguien que en un momento es apaleado y al siguiente es emperador. Hoy es la criatura más desdichada y necesitada del mundo, y mañana podría tener dos o tres coronas de reinos que dar a su escudero.

—Pues, ¿cómo es que vos, siendo escudero de tan buen señor —dijo la posadera—, no tenéis, al parecer, ni siquiera un condado?

—Aún es temprano —respondió Sancho—, porque solo hace un mes que andamos buscando aventuras, y hasta ahora no hemos encontrado ninguna que lo sea. Y a veces, uno busca una cosa y encuentra otra. Es verdad que si mi señor don Quijote se recupera de esta herida o caída y yo no quedo lisiado por ella, no cambiaría mis esperanzas por el mejor título de España.

Don Quijote escuchaba muy atento todas estas conversaciones. Sentándose en la cama como pudo, y tomando de la mano a la posadera, le dijo:

—Creedme, hermosa señora, que podéis llamaros afortunada por haber alojado en este vuestro castillo a mi persona. Soy tal que, si no me alabo, es por lo que suele decirse, que la alabanza propia degrada. Pero mi escudero os dirá quién soy. Solo os digo que tendré eternamente grabado en mi memoria el servicio que me habéis hecho, para agradecéroslo mientras me dure la vida. Y ojalá los altos cielos quisieran que el amor no me tuviera tan rendido y sujeto a sus leyes, y los ojos de aquella hermosa ingrata de la que hablo entre dientes. Si no fuera por eso, los ojos de esta hermosa joven serían los dueños de mi libertad.

Confundidas estaban la posadera, su hija y la buena de Maritornes al oír las razones del caballero andante. Las entendían tanto como si hablara en griego, aunque se dieron cuenta de que todo eran ofrecimientos y piropos. Y como no estaban acostumbradas a un lenguaje semejante, lo miraban con asombro, y les parecía un hombre diferente a los que solían ver. Agradeciéndole sus ofrecimientos con palabras propias de una posada, lo dejaron. Y la asturiana Maritornes curó a Sancho, que no lo necesitaba menos que su amo.

El arriero había acordado con ella que aquella noche se divertirían juntos, y ella le había dado su palabra de que, en cuanto los huéspedes estuvieran tranquilos y sus amos durmiendo, iría a buscarlo y a satisfacerle el gusto en todo lo que le pidiera. Y se cuenta de esta buena moza que jamás dio tales palabras que no las cumpliera, aunque las diera en un monte y sin testigos. Presumía de ser muy honrada, y no consideraba una afrenta trabajar sirviendo en la posada, porque decía que las desgracias y los malos sucesos la habían llevado a ese estado.

La dura, estrecha, pequeña y falsa cama de don Quijote estaba primero, en mitad de aquel estrellado establo. Luego, junto a él, Sancho hizo la suya, que solo contenía una estera y una manta, que más parecía de tela de saco que de lana. A estas dos camas les seguía la del arriero, fabricada, como se ha dicho, con los aparejos de las dos mejores mulas que traía. Aunque tenía doce, eran lustrosas, gordas y famosas, porque era uno de los arrieros más ricos de Arévalo, según dice el autor de esta historia. Hace especial mención de este arriero porque lo conocía muy bien, e incluso se dice que era pariente suyo. Aparte de que Cide Hamete Benengeli fue un historiador muy curioso y muy preciso en todas las cosas. Y se nota, pues los detalles que se han contado, a pesar de ser tan mínimos y sin importancia, no los quiso pasar en silencio. De donde podrán tomar ejemplo los historiadores serios, que nos cuentan las acciones de forma tan breve que apenas las saboreamos, dejándose en el tintero lo más sustancial de la obra, ya sea por descuido, malicia o ignorancia. ¡Bendito sea mil veces el autor de "Tablante de Ricamonte", y el de aquel otro libro donde se cuentan los hechos del conde Tomillas, y con qué precisión lo describen todo!

Digo, pues, que después de que el arriero visitara a sus animales y les diera su segunda ración de pienso, se tendió en sus aparejos y se puso a esperar a su puntualísima Maritornes. Sancho ya estaba curado y acostado. Y aunque intentaba dormir, no se lo permitía el dolor de sus costillas. Y don Quijote, con el dolor de las suyas, tenía los ojos abiertos como una liebre. Toda la posada estaba en silencio, y no había más luz que la de una lámpara que colgaba en medio del portal.

Esta maravillosa quietud, y los pensamientos que nuestro caballero siempre traía de los sucesos que a cada paso se cuentan en los libros, autores de su desgracia, le trajeron a la imaginación una de las locuras más extrañas que se puedan imaginar. Se imaginó que había llegado a un famoso castillo —pues, como se ha dicho, todas las posadas donde se alojaba le parecían castillos— y que la hija del posadero era la hija del señor del castillo. Y que ella, vencida por su gentileza, se había enamorado de él y le había prometido que aquella noche, a escondidas de sus padres, vendría a yacer con él un buen rato. Teniendo toda esta quimera que él se había fabricado por cierta y verdadera, comenzó a preocuparse y a pensar en el peligroso trance en que se vería su honestidad. Y se propuso en su corazón no cometer traición a su señora Dulcinea del Toboso, aunque la misma reina Ginebra con su dama Quintañona se le pusieran delante.

Pensando, pues, en estas locuras, llegó el tiempo y la hora —que para él fue desafortunada— de la venida de la asturiana. Ella, en camisa y descalza, con el pelo recogido en una red de tela, entró con pasos sigilosos y atentos en la habitación donde los tres se alojaban, en busca del arriero. Pero apenas llegó a la puerta, don Quijote la sintió. Y sentándose en la cama, a pesar de sus emplastos y con dolor de sus costillas, extendió los brazos para recibir a su hermosa doncella. La asturiana, que, muy recogida y en silencio, iba con las manos por delante buscando a su querido, se topó con los brazos de don Quijote. Él la agarró fuertemente de una muñeca y, tirando de ella hacia sí, sin que ella se atreviera a decir palabra, la hizo sentar sobre la cama. Le tocó luego la camisa, y aunque era de tela áspera, a él le pareció de finísimo y delgado cendal. Llevaba en las muñecas unas cuentas de vidrio, pero a él le parecieron preciosas perlas orientales. Los cabellos, que de alguna manera parecían crines, él los tomó por hebras del más brillante oro de Arabia, cuyo resplandor oscurecía al del mismo sol. Y el aliento, que, sin duda alguna, olía a ensalada pasada y trasnochada, a él le pareció que arrojaba de su boca un olor suave y aromático.

Finalmente, él la pintó en su imaginación con la misma apariencia y modo que había leído en sus libros sobre la otra princesa que vino a ver al caballero malherido, vencida por sus amores, con todos los adornos que aquí se han descrito. Y era tanta la ceguera del pobre hidalgo, que ni el tacto, ni el aliento, ni otras cosas que la buena muchacha traía consigo, lo desengañaban, las cuales habrían hecho vomitar a cualquiera que no fuera arriero. Al contrario, le parecía que tenía entre sus brazos a la diosa de la hermosura. Y, teniéndola bien agarrada, con voz amorosa y baja, le comenzó a decir:

—Quisiera encontrarme en condiciones, hermosa y alta señora, de poder pagar un favor tan grande como el que me habéis hecho con la vista de vuestra gran hermosura. Pero la fortuna, que no se cansa de perseguir a los buenos, ha querido ponerme en esta cama, donde yazgo tan molido y quebrantado que, aunque mi voluntad quisiera satisfacer la vuestra, sería imposible. Y a esta imposibilidad se añade otra mayor, que es la fe prometida que tengo dada a la sin par Dulcinea del Toboso, única señora de mis más escondidos pensamientos. Si esto no estuviera de por medio, no sería yo un caballero tan necio como para dejar pasar en blanco la afortunada ocasión en que vuestra gran bondad me ha puesto.

Maritornes estaba muy angustiada y sudando al verse tan agarrada por don Quijote. Sin entender ni prestar atención a las razones que le decía, intentaba soltarse sin hablar. El bueno del arriero, a quien sus malos deseos mantenían despierto, sintió a su amante desde el momento en que entró por la puerta. Estuvo escuchando atentamente todo lo que don Quijote decía y, celoso de que la asturiana le hubiera faltado a su palabra por otro, se fue acercando más a la cama de don Quijote. Se quedó quieto para ver en qué terminaban aquellas palabras que no podía entender. Pero al ver que la moza forcejeaba por soltarse y que don Quijote se esforzaba por retenerla, la broma le pareció mal. Levantó el brazo y descargó un puñetazo tan terrible sobre las delgadas mandíbulas del enamorado caballero, que le bañó toda la boca en sangre. Y no contento con esto, se le subió encima de las costillas y, con los pies, se las recorrió todas de principio a fin.

La cama, que era un poco débil y no tenía unos cimientos firmes, no pudo soportar el peso añadido del arriero y se vino abajo. Con el gran ruido, el posadero se despertó e imaginó que debían de ser peleas de Maritornes, porque, habiéndola llamado a gritos, no respondía. Con esta sospecha, se levantó y, encendiendo un candil, se fue hacia donde había sentido la pelea. La moza, al ver que venía su amo, que era de carácter terrible, muy asustada y alborotada, se refugió en la cama de Sancho Panza, que aún dormía. Allí se acurrucó y se hizo un ovillo. El posadero entró diciendo:

—¿Dónde estás, prostituta? ¡Seguro que estas son cosas tuyas!

En esto, Sancho se despertó. Al sentir aquel bulto casi encima de él, pensó que tenía una pesadilla y comenzó a dar puñetazos a diestro y siniestro. Entre otros, le dio no sé cuántos a Maritornes, la cual, sintiendo el dolor y olvidando la honestidad, le devolvió a Sancho tantos golpes que, a su pesar, le quitó el sueño. Al verse tratado de aquella manera y sin saber por quién, se levantó como pudo, se abrazó con Maritornes, y comenzaron entre los dos la pelea más reñida y graciosa del mundo. Al ver el arriero, a la luz del candil del posadero, cómo andaba su dama, dejó a don Quijote y acudió a darle el socorro necesario. Lo mismo hizo el posadero, pero con una intención diferente: fue a castigar a la moza, creyendo sin duda que ella sola era la causa de toda aquella armonía. Y así como se suele decir: el gato al ratón, el ratón a la cuerda, la cuerda al palo; el arriero le pegaba a Sancho, Sancho a la moza, la moza a él, el posadero a la moza. Y todos se daban con tanta prisa que no se daban un momento de descanso. Y lo bueno fue que al posadero se le apagó el candil. Y al quedarse a oscuras, se daban todos a ciegas y sin compasión, de modo que dondequiera que ponían la mano, no dejaban cosa sana.

Alojaba casualmente aquella noche en la posada un agente de los que llaman de la Santa Hermandad Vieja de Toledo. Al oír el extraño estruendo de la pelea, agarró su vara y la caja de lata de sus títulos, y entró a oscuras en la habitación, diciendo:

—¡Alto en nombre de la justicia! ¡Alto en nombre de la Santa Hermandad!

Y el primero con quien se topó fue con el golpeado don Quijote, que estaba en su cama derribada, tendido boca arriba, sin sentido. Y, agarrándole la barba a tientas, no cesaba de decir:

—¡Auxilio a la justicia!

Pero, al ver que el que tenía agarrado no se movía, se dio a entender que estaba muerto y que los que allí dentro estaban eran sus asesinos. Con esta sospecha, reforzó la voz, diciendo:

—¡Ciérrese la puerta de la posada! ¡Que no se vaya nadie, que aquí han muerto a un hombre!

Esta voz sobresaltó a todos, y cada cual dejó la pelea en el punto en que la voz lo sorprendió. El posadero se retiró a su habitación, el arriero a sus aparejos, la moza a su rincón. Solo los desdichados don Quijote y Sancho no pudieron moverse de donde estaban. En esto, el agente soltó la barba de don Quijote y salió a buscar luz para buscar y prender a los delincuentes. Pero no la encontró, porque el posadero, a propósito, había apagado la lámpara cuando se retiró a su cuarto. Y tuvo que acudir a la chimenea, donde, con mucho trabajo y tiempo, el agente encendió otro candil.`,
}
