export const chapter_9 = {
	name: 'Capítulo IX',
	header: 'Donde se concluye y da fin a la estupenda batalla que el gallardo vizcaíno y el valiente manchego tuvieron',
	text: `En la primera parte de esta historia, dejamos al valiente vizcaíno y al famoso don Quijote con las espadas en alto, a punto de descargar dos golpes furiosos. Eran tan fuertes que, si acertaban de lleno, como mínimo se habrían partido en dos de arriba abajo, como una granada. Y en ese punto tan crucial, la sabrosa historia se interrumpió, sin que el autor nos dijera dónde podríamos encontrar lo que faltaba.

Esto me causó una gran pena, porque el placer de haber leído tan poco se convirtió en disgusto al pensar en lo difícil que sería encontrar la gran parte que, a mi parecer, faltaba de una historia tan agradable. Me parecía imposible y fuera de toda buena costumbre que a un caballero tan bueno le faltara un sabio que se encargara de escribir sus hazañas nunca vistas. Esto no le faltó a ninguno de los caballeros andantes de los que la gente dice que van en busca de aventuras.

Cada uno de ellos tenía uno o dos sabios, como hechos a medida, que no solo escribían sus actos, sino que también describían sus pensamientos más pequeños y sus trivialidades, por muy escondidas que fueran. Y no podía ser que un caballero tan bueno fuera tan desafortunado como para que le faltara lo que a otros como Platir les sobraba. Por eso, no podía creer que una historia tan elegante hubiera quedado incompleta y dañada. Le echaba la culpa a la maldad del tiempo, devorador de todas las cosas, que la tenía oculta o la había destruido.

Por otra parte, me parecía que, ya que entre sus libros se habían encontrado obras tan modernas como "Desengaño de celos" y "Ninfas y Pastores de Henares", su propia historia también debía de ser moderna. Y que, si no estaba escrita, estaría en la memoria de la gente de su pueblo y de los alrededores. Esta idea me tenía confundido y deseoso de saber, real y verdaderamente, toda la vida y milagros de nuestro famoso español don Quijote de la Mancha, luz y espejo de la caballería manchega.

Fue el primero en nuestra edad y en estos tiempos tan desastrosos que se dedicó al trabajo y ejercicio de las armas andantes, a deshacer injusticias, a socorrer viudas y a amparar doncellas. De aquellas que andaban de monte en monte y de valle en valle con sus látigos, sus caballos y con toda su virginidad a cuestas. Porque, a menos que algún cobarde, algún villano o algún gigante descomunal las forzara, hubo doncellas en tiempos pasados que, al cabo de ochenta años, sin haber dormido un solo día bajo techo, se fueron a la tumba tan vírgenes como el día que nacieron.

Digo, pues, que por estas y otras muchas razones, nuestro elegante Quijote es digno de continuas y memorables alabanzas. Y a mí tampoco se me deben negar, por el trabajo y la diligencia que puse en buscar el final de esta agradable historia. Aunque bien sé que si el cielo, el azar y la fortuna no me ayudan, el mundo se quedará sin el pasatiempo y el gusto que podría tener durante casi dos horas el que la lea con atención. Así fue como la encontré:

Estando yo un día en el Alcaná de Toledo, un muchacho llegó a vender unas carpetas y papeles viejos a un vendedor de seda. Y como soy aficionado a leer, aunque sean los papeles rotos de las calles, llevado por mi inclinación natural, tomé una de las carpetas que el muchacho vendía y vi que tenía caracteres que reconocí como árabes. Y aunque los reconocía, no sabía leerlos. Anduve buscando si por allí había algún morisco que supiera leerlo. No fue muy difícil encontrar un intérprete así, pues incluso si hubiera buscado uno de una lengua mejor y más antigua, lo habría encontrado.

Al final, la suerte me ofreció uno. Le conté mi deseo y, poniéndole el libro en las manos, lo abrió por la mitad y, al leer un poco, se empezó a reír. Le pregunté de qué se reía. Me respondió que de algo que estaba escrito en el margen como una anotación. Le pedí que me lo dijera, y él, sin dejar de reír, dijo:

—Está escrito aquí en el margen: "Esta Dulcinea del Toboso, tantas veces mencionada en esta historia, dicen que tenía la mejor mano para salar cerdos que cualquier otra mujer en toda la Mancha".

Cuando oí decir "Dulcinea del Toboso", me quedé atónito y en suspenso, porque enseguida me imaginé que aquellas carpetas contenían la historia de don Quijote. Con esta idea, le di prisa para que leyera el principio. Y, haciéndolo así, traduciendo de repente el árabe al castellano, dijo que decía: "Historia de don Quijote de la Mancha, escrita por Cide Hamete Benengeli, historiador arábigo".

Se necesitó mucha discreción para disimular la alegría que sentí cuando oí el título del libro. Adelantándome al vendedor de seda, le compré al muchacho todos los papeles y carpetas por medio real. Si él hubiera sido listo y hubiera sabido lo mucho que yo los deseaba, bien podría haber pedido y conseguido más de seis reales por la compra. Me aparté luego con el morisco por el claustro de la iglesia principal y le rogué que me tradujera al castellano todas las carpetas que trataban de don Quijote, sin quitarles ni añadirles nada, ofreciéndole el pago que él quisiera.

Se contentó con una buena cantidad de pasas y trigo, y prometió traducirlos bien, fielmente y con mucha rapidez. Pero yo, para facilitar más el asunto y para no dejar escapar tan buen descubrimiento, lo llevé a mi casa, donde en poco más de mes y medio lo tradujo todo, tal como aquí se cuenta.

En la primera carpeta estaba pintada, de forma muy natural, la batalla de don Quijote con el vizcaíno. Estaban en la misma postura que cuenta la historia, con las espadas levantadas, uno cubierto con su escudo y el otro con la almohada. La mula del vizcaíno estaba tan bien pintada que, a tiro de ballesta, se notaba que era de alquiler. A los pies del vizcaíno había un letrero que decía: "Don Sancho de Azpetia", que sin duda debía ser su nombre. Y a los pies de Rocinante había otro que decía: "Don Quijote".

Rocinante estaba maravillosamente pintado: largo, delgado, con el espinazo muy marcado y extremadamente flaco. Mostraba claramente con cuánta precisión y acierto se le había puesto el nombre de Rocinante. Junto a él estaba Sancho Panza, que sujetaba a su burro del cabestro. A los pies del burro había otro letrero que decía: "Sancho Zancas". Y debía de ser porque, según mostraba la pintura, tenía la barriga grande, el talle corto y las piernas largas. Por eso se le debió de poner el nombre de Panza y de Zancas, pues con estos dos apodos lo llama a veces la historia.

Había otros pequeños detalles que observar, pero todos son de poca importancia y no afectan a la verdadera relación de la historia, pues ninguna historia es mala si es verdadera. Si se le puede poner alguna objeción a esta en cuanto a su verdad, no puede ser otra que el hecho de que su autor fuera árabe, siendo muy propio de esa nación ser mentirosos. Aunque, por ser tan enemigos nuestros, se puede pensar más bien que el autor se quedó corto en las alabanzas en lugar de excederse.

Así me lo parece a mí, pues cuando podría y debería haber extendido su pluma en las alabanzas de tan buen caballero, parece que a propósito las pasa en silencio. Algo mal hecho y peor pensado, ya que los historiadores deben ser precisos, verdaderos y nada apasionados. Ni el interés, ni el miedo, ni el rencor, ni el afecto deben desviarlos del camino de la verdad, cuya madre es la historia, émula del tiempo, depósito de las acciones, testigo de lo pasado, ejemplo y aviso de lo presente, y advertencia de lo por venir. En esta sé que se encontrará todo lo que se pueda desear en la historia más agradable. Y si algo bueno le falta, creo que fue por culpa de su autor, más que por falta del personaje.

En fin, su segunda parte, siguiendo la traducción, comenzaba de esta manera:

Puestas en alto las afiladas espadas de los dos valientes y enfadados combatientes, no parecía sino que amenazaban al cielo, a la tierra y al abismo, tal era la valentía y el porte que tenían. El primero en descargar el golpe fue el furioso vizcaíno. Fue un golpe dado con tanta fuerza y tanta furia que, si la espada no se le hubiera torcido en el camino, aquel solo golpe habría bastado para poner fin a su dura contienda y a todas las aventuras de nuestro caballero. Pero la buena suerte, que lo tenía guardado para cosas mayores, torció la espada de su contrario, de modo que, aunque le acertó en el hombro izquierdo, no le hizo más daño que desarmarle todo ese lado, llevándose de paso gran parte del casco y la mitad de la oreja. Todo ello cayó al suelo con un estruendo espantoso, dejándolo muy malherido.

¡Dios mío! ¡Y quién será capaz de contar ahora la rabia que sintió nuestro manchego al verse en esa situación! Basta decir que se levantó de nuevo en los estribos y, apretando más la espada con ambas manos, descargó con tal furia sobre el vizcaíno, acertándole de lleno en la almohada y en la cabeza, que, sin que tan buena defensa sirviera de nada, como si una montaña cayera sobre él, empezó a echar sangre por la nariz, la boca y los oídos. Dio señales de que iba a caer de la mula, y habría caído, sin duda, si no se hubiera abrazado a su cuello. Pero, aun así, sacó los pies de los estribos y luego soltó los brazos. La mula, asustada por el terrible golpe, se echó a correr por el campo, y a los pocos saltos tiró a su dueño al suelo.

Don Quijote lo estaba mirando con mucha calma. Y al verlo caer, saltó de su caballo y con gran agilidad se acercó a él. Poniéndole la punta de la espada en los ojos, le dijo que se rindiera o le cortaría la cabeza. El vizcaíno estaba tan aturdido que no podía responder palabra. Y lo habría pasado mal, según lo ciego que estaba don Quijote, si las señoras del coche, que hasta entonces habían mirado la pelea con gran susto, no se hubieran acercado a él. Con mucha insistencia, le pidieron que les hiciera el gran favor de perdonarle la vida a su escudero.

A esto, don Quijote respondió con mucho tono y seriedad:

—Por cierto, hermosas señoras, estoy muy contento de hacer lo que me pedís. Pero ha de ser con una condición y un acuerdo: este caballero me ha de prometer ir al pueblo del Toboso y presentarse de mi parte ante la sin par doña Dulcinea, para que ella haga de él lo que más le plazca.

La temerosa y desconsolada señora, sin pararse a pensar en lo que don Quijote pedía y sin preguntar quién era Dulcinea, le prometió que el escudero haría todo lo que se le ordenara de su parte.

—Pues, confiando en esa palabra, no le haré más daño, aunque bien se lo tenía merecido.`,
}
