export const chapter_27 = {
	name: 'Capítulo XXVII',
	header: 'De cómo salieron con su intención el cura y el barbero, con otras cosas dignas de que se cuenten en esta grande historia',
	text: `Al barbero le gustó mucho la idea del cura, y la pusieron en práctica de inmediato. Le pidieron a la dueña de la venta una falda y unos pañuelos para la cabeza, dejándole como garantía una sotana nueva del cura. El barbero se hizo una gran barba con la cola de un buey, que era de un color entre rojizo y pardo, y que el ventero usaba para colgar su peine. La ventera les preguntó para qué querían esas cosas. El cura le explicó brevemente la locura de don Quijote y que necesitaban ese disfraz para sacarlo de la montaña donde se encontraba en ese momento.

El ventero y la ventera se dieron cuenta entonces de que el loco era su huésped, el que preparaba el bálsamo, y el amo del escudero que habían manteado. Le contaron al cura todo lo que les había pasado con él, sin omitir lo que Sancho solía callar.

Finalmente, la ventera vistió al cura de una forma muy llamativa. Le puso una falda de paño, llena de franjas de terciopelo negro de un palmo de ancho, todas con cortes decorativos. También le puso un corpiño de terciopelo verde, adornado con ribetes de raso blanco. Tanto la falda como el corpiño parecían haber sido hechos en tiempos del rey Wamba. El cura no permitió que le pusieran el tocado, sino que se puso en la cabeza un gorrito de tela acolchada que usaba para dormir. Se ató a la frente una cinta de tafetán negro y con otra cinta se hizo un antifaz, con el que se cubrió muy bien la barba y el rostro. Se caló su sombrero, que era tan grande que podía servirle de parasol, y cubriéndose con su capa, se subió a la mula sentado de lado, como una mujer. El barbero se subió a la suya, con su barba que le llegaba a la cintura, entre rojiza y blanca, hecha, como ya se ha dicho, de la cola de un buey de color pardo.

Se despidieron de todos y de la buena Maritornes, que prometió rezar un rosario, aunque se consideraba pecadora, para que Dios les concediera el éxito en una empresa tan ardua y cristiana como la que habían emprendido.

Pero, apenas salió de la venta, el cura tuvo un pensamiento: que hacía mal en vestirse de esa manera, por ser algo indecente para un sacerdote, aunque fuera muy importante. Al decírselo al barbero, le rogó que cambiaran los trajes, pues era más justo que el barbero fuera la doncella necesitada y él hiciera de escudero. Así, su dignidad se ofendería menos. Y si no quería hacerlo, estaba decidido a no seguir, aunque a don Quijote se lo llevara el diablo.

En ese momento, llegó Sancho, y al verlos a los dos con aquel atuendo no pudo contener la risa. Finalmente, el barbero aceptó todo lo que el cura quiso. Cambiando el plan, el cura le fue explicando la forma en que debía actuar y las palabras que debía decir a don Quijote para convencerlo y obligarlo a que se fuera con él, y dejara el apego al lugar que había escogido para su inútil penitencia. El barbero respondió que, sin que le dieran lecciones, él lo haría perfectamente. No quiso vestirse en ese momento, sino esperar a estar cerca de donde se encontraba don Quijote. Así que dobló su ropa, el cura se arregló la barba y siguieron su camino, guiados por Sancho Panza. Él les fue contando lo que les había sucedido con el loco que encontraron en la sierra, pero ocultando el hallazgo de la maleta y todo lo que contenía; que, aunque no era tonto, el joven era un poco codicioso.

Al día siguiente llegaron al lugar donde Sancho había dejado las señales con las ramas para encontrar el sitio donde había dejado a su señor. Al reconocerlo, les dijo que aquella era la entrada y que ya podían vestirse, si es que eso era relevante para la libertad de su señor. Ellos le habían dicho antes que ir y vestirse de esa manera era de suma importancia para sacar a su amo de aquella mala vida que había escogido. Le encargaron mucho que no le dijera a su amo quiénes eran, ni que los conocía. Y si le preguntaba, como seguramente haría, si le había dado la carta a Dulcinea, que dijera que sí. Y que, como ella no sabía leer, le había respondido de palabra, diciéndole que le ordenaba, bajo amenaza de su castigo, que fuera a verla inmediatamente, pues era un asunto de gran importancia. Con esto y con lo que ellos pensaban decirle, estaban seguros de que lo llevarían a una vida mejor y lograrían que se pusiera en camino para ser emperador o monarca; porque de ser arzobispo no había de qué preocuparse.

Sancho escuchó todo, lo guardó bien en su memoria y les agradeció mucho la intención que tenían de aconsejar a su señor que fuera emperador y no arzobispo. Porque él pensaba que los emperadores podían hacer más favores a sus escuderos que los arzobispos viajeros. También les dijo que sería bueno que él se adelantara a buscarlo y a darle la respuesta de su señora. Seguramente eso bastaría para sacarlo de aquel lugar, sin que ellos tuvieran que tomarse tanto trabajo. Les pareció bien lo que Sancho Panza decía, y así, decidieron esperarlo hasta que volviera con la noticia de haber encontrado a su amo.

Sancho entró por las quebradas de la sierra, dejando a los dos en un lugar por donde corría un pequeño y tranquilo arroyo, a quien daban una sombra agradable y fresca unas rocas y algunos árboles que por allí había. El día que llegaron era caluroso, uno de esos días de agosto, cuando por aquellas tierras el calor suele ser muy intenso. Eran las tres de la tarde. Todo lo cual hacía el lugar más agradable e invitaba a que en él esperasen el regreso de Sancho, como en efecto hicieron.

Estando, pues, los dos allí, tranquilos y a la sombra, llegó a sus oídos una voz que, sin el sonido de ningún otro instrumento que la acompañara, sonaba dulce y suavemente. Esto les causó bastante admiración, pues les parecía que aquél no era lugar para que hubiera alguien que cantara tan bien. Porque, aunque se suele decir que en los bosques y en los campos se encuentran pastores con voces extraordinarias, eso es más una exageración de poetas que una verdad. Y más aún cuando se dieron cuenta de que lo que oían cantar no eran versos de rústicos ganaderos, sino de cultos cortesanos. Y esta verdad se confirmó al escuchar los siguientes versos:

¿Quién disminuye mis bienes?
Desdenes.
Y ¿quién aumenta mis penas?
Los celos.
Y ¿quién prueba mi paciencia?
Ausencia.
De ese modo, en mi dolencia
ningún remedio se alcanza,
pues me matan la esperanza
desdenes, celos y ausencia.
¿Quién me causa este dolor?
Amor.
Y ¿quién mi gloria rechaza?
Fortuna.
Y ¿quién consiente en mi pena?
El cielo.
De ese modo, yo temo
morir de este mal extraño,
pues se aumentan para mi mal,
amor, fortuna y el cielo.
¿Quién mejorará mi suerte?
La muerte.
Y el bien de amor, ¿quién lo alcanza?
El cambio.
Y sus males, ¿quién los cura?
La locura.
De ese modo, no es sensato
querer curar la pasión
cuando los remedios son
muerte, cambio y locura.

La hora, el tiempo, la soledad, la voz y la habilidad del que cantaba causaron admiración y alegría en los dos oyentes, los cuales se quedaron quietos, esperando si oían algo más. Pero, viendo que el silencio duraba un rato, decidieron salir a buscar al músico que con tan buena voz cantaba. Y, cuando se disponían a hacerlo, la misma voz les indicó que no se movieran, y llegó de nuevo a sus oídos, cantando este soneto:

Soneto

Santa amistad, que con ligeras alas,
dejando tu apariencia en el suelo,
entre almas benditas, en el cielo,
subiste alegre a las salas celestiales,
desde allá, cuando quieres, nos muestras
la justa paz cubierta con un velo,
a través del cual a veces se trasluce el celo
de buenas obras que, al final, son malas.
¡Oh amistad, deja el cielo!, o no permitas
que el engaño se vista tu librea,
con que destruye a la intención sincera;
que si no le quitas tus apariencias,
pronto el mundo se verá en la pelea
de la primera y discordante confusión.

El canto terminó con un profundo suspiro, y los dos, con atención, volvieron a esperar por si se oía algo más. Pero, al ver que la música se había convertido en sollozos y en lamentos lastimeros, decidieron averiguar quién era el triste personaje, tan extraordinario en la voz como doloroso en los gemidos. No anduvieron mucho, cuando, al doblar la punta de una roca, vieron a un hombre del mismo aspecto y figura que Sancho Panza les había descrito cuando les contó la historia de Cardenio. Aquel hombre, cuando los vio, sin asustarse, se quedó quieto, con la cabeza inclinada sobre el pecho como un hombre pensativo, sin levantar los ojos para mirarlos más que la primera vez, cuando llegaron de improviso.

El cura, que era un hombre de buen hablar y que ya conocía su desgracia por las señas que le habían dado, se le acercó. Con palabras breves pero muy discretas, le rogó y persuadió que abandonara aquella vida tan miserable, para que no la perdiera allí, lo que sería la mayor de las desgracias. Cardenio estaba entonces en su sano juicio, libre de aquel ataque de furia que tan a menudo lo sacaba de sí mismo. Al ver a los dos con un atuendo tan poco común para quienes andaban por aquellas soledades, no dejó de sorprenderse un poco. Más aún cuando oyó que le hablaban de su asunto como de algo conocido, pues las palabras del cura así se lo dieron a entender. De modo que respondió de esta manera:

—Bien veo, señores, seáis quienes seáis, que el cielo, que cuida de socorrer a los buenos, y a menudo también a los malos, sin que yo lo merezca, me envía a estos lugares tan remotos y apartados del trato común de la gente, a algunas personas que, poniéndome ante los ojos con vivas y variadas razones lo equivocado que estoy al llevar la vida que llevo, han intentado sacarme de aquí a un lugar mejor. Pero como no saben que yo sé que al salir de este mal caeré en otro mayor, quizás me consideren un hombre de poco entendimiento, o peor aún, sin juicio alguno. Y no sería de extrañar que así fuera, porque me parece que la fuerza de la imaginación de mis desgracias es tan intensa y tiene tanto poder en mi perdición que, sin que yo pueda evitarlo, me quedo como una piedra, falto de todo buen sentido y conocimiento. Me doy cuenta de esta verdad cuando algunos me cuentan y me muestran señales de las cosas que he hecho mientras aquel terrible ataque me domina. Entonces no puedo hacer más que lamentarme en vano, maldecir sin provecho mi suerte y, como disculpa de mis locuras, contar la causa de ellas a cuantos quieran oírla. Porque, si los cuerdos ven cuál es la causa, no se sorprenderán de los efectos, y si no me dan...

Los dos, que no deseaban otra cosa que saber de su propia boca la causa de su mal, le rogaron que se la contase, ofreciéndole no hacer nada que él no quisiera, ya fuera para su remedio o su consuelo. Con esto, el triste caballero comenzó su lastimosa historia, casi con las mismas palabras y en los mismos términos que la había contado a don Quijote y al cabrero pocos días atrás. En aquella ocasión, por el asunto del maestro Elisabat y la insistencia de don Quijote en guardar el decoro de la caballería, el cuento quedó incompleto, como la historia lo relata. Pero ahora la buena suerte quiso que el ataque de locura se detuviera y le diera la oportunidad de contarlo hasta el final. Y así, llegando al pasaje de la carta que don Fernando había encontrado en el libro de Amadís de Gaula, Cardenio dijo que la recordaba muy bien y que decía así:

«Luscinda a Cardenio

Cada día descubro en ti valores que me obligan y fuerzan a estimarte más; y así, si quisieras liberarme de esta deuda sin deshonrarme, podrías hacerlo muy bien. Tengo un padre que te conoce y que me quiere mucho, el cual, sin oponerse a mi voluntad, aceptará la que sea justo que tengas, si es que me quieres como dices y como creo.

»Por esta carta me decidí a pedir a Luscinda como esposa, como ya les he contado. Y fue por esta carta por la que don Fernando consideró a Luscinda como una de las mujeres más discretas e inteligentes de su tiempo. Y esta carta fue la que le generó el deseo de destruirme, antes de que mi plan se realizara. Le expliqué a don Fernando cuál era la condición que ponía el padre de Luscinda: que mi padre se la pidiera. Yo no me atrevía a decírselo, temeroso de que no aceptaría. No porque no conociera bien la calidad, bondad, virtud y hermosura de Luscinda, y que tenía suficientes cualidades para ennoblecer a cualquier otra familia de España, sino porque sabía por él que deseaba que no me casara tan pronto, hasta ver qué planes tenía para mí el duque Ricardo. En resumen, le dije que no me atrevía a decírselo a mi padre, tanto por aquel inconveniente como por otros muchos motivos que me asustaban, sin saber cuáles eran, pero me parecía que lo que yo deseaba nunca se cumpliría.

»A todo esto, don Fernando me respondió que él se ocuparía de hablar con mi padre y de hacer que él hablara con el de Luscinda. ¡Oh Mario ambicioso, oh Catilina cruel, oh Sila facineroso, oh Galalón embustero, oh Vellido traidor, oh Julián vengativo, oh Judas codicioso! Traidor, cruel, vengativo y embustero, ¿qué mal te había hecho este pobre hombre, que con tanta sinceridad te descubrió los secretos y alegrías de su corazón? ¿Qué ofensa te hice? ¿Qué palabras te dije, o qué consejos te di, que no estuvieran todos dirigidos a aumentar tu honra y tu beneficio? Pero, ¿de qué me quejo, desdichado de mí? Pues es cosa cierta que cuando las desgracias vienen marcadas por las estrellas, como vienen desde lo alto, cayendo con furia y con violencia, no hay fuerza en la tierra que las detenga, ni habilidad humana que pueda prevenirlas. ¿Quién podría imaginar que don Fernando, un caballero ilustre, discreto, agradecido por mis servicios, poderoso para alcanzar lo que su deseo amoroso le pidiera dondequiera que estuviera, se iba a obsesionar, como se dice, con quitarme la única oveja que yo tenía, y que ni siquiera era mía todavía? Pero dejemos estas consideraciones aparte, por inútiles y sin provecho, y reanudemos el hilo roto de mi desdichada historia.

»Digo, pues, que, como a don Fernando le parecía que mi presencia era un obstáculo para llevar a cabo su falso y malvado plan, decidió enviarme a su hermano mayor con el pretexto de pedirle dinero para pagar seis caballos. De forma deliberada, y solo con el fin de que me ausentara (para poder llevar a cabo mejor su dañada intención), los compró el mismo día que se ofreció a hablar con mi padre, y quiso que yo fuera a por el dinero. ¿Pude acaso prevenir esta traición? ¿Pude, por ventura, llegar a imaginarla? No, por cierto. Al contrario, con grandísimo gusto, me ofrecí a irme enseguida, contento por la buena compra hecha. Aquella noche hablé con Luscinda, y le dije lo que había acordado con don Fernando, y que mantuviera la firme esperanza de que nuestros buenos y justos deseos se cumplirían. Ella me dijo, tan ajena como yo a la traición de don Fernando, que procurara volver pronto, porque creía que el cumplimiento de nuestros deseos no tardaría más que lo que tardara mi padre en hablar con el suyo. No sé qué pasó, que, en cuanto terminó de decirme esto, se le llenaron los ojos de lágrimas y un nudo se le hizo en la garganta, que no le dejaba decir ni una palabra de las muchas otras que me pareció que intentaba decirme.

»Quedé sorprendido por este nuevo suceso, que jamás había visto en ella. Porque siempre que hablábamos, las veces que la buena fortuna y mi diligencia lo permitían, lo hacíamos con mucha alegría y felicidad, sin mezclar en nuestras conversaciones lágrimas, suspiros, celos, sospechas o temores. Todo era para mí engrandecer mi suerte por habérmela dado el cielo por señora: yo exageraba su belleza y admiraba su valor y entendimiento. Ella me correspondía, alabando en mí lo que, como enamorada, le parecía digno de alabanza. Con esto, nos contábamos cien mil tonterías y sucesos de nuestros vecinos y conocidos. Y a lo que más llegaba mi atrevimiento era a tomarle, casi a la fuerza, una de sus bellas y blancas manos, y acercarla a mi boca, según lo permitía la estrechez de una reja baja que nos dividía. Pero la noche anterior al triste día de mi partida, ella lloró, gimió y suspiró. Luego se fue y me dejó lleno de confusión y sobresalto, asustado de haber visto tan nuevas y tristes muestras de dolor y sentimiento en Luscinda. Pero, para no destruir mis esperanzas, lo atribuí todo a la fuerza del amor que me tenía y al dolor que suele causar la ausencia en los que se quieren bien.

»En fin, yo me fui triste y pensativo, con el alma llena de imaginaciones y sospechas, sin saber qué sospechaba ni qué imaginaba: claros indicios que me mostraban el triste suceso y la desventura que me aguardaba. Llegué al lugar adonde me habían enviado. Le di las cartas al hermano de don Fernando. Fui bien recibido, pero no me despacharon pronto, porque me mandó esperar, para mi disgusto, ocho días, y en un lugar donde el duque, su padre, no me viera, porque su hermano le escribía que le enviara cierto dinero sin que su padre lo supiera. Y todo fue una invención del falso don Fernando, pues a su hermano no le faltaba dinero para despacharme de inmediato. Fue una orden y un mandato que me puso en una situación difícil de obedecer, pues me parecía imposible soportar tantos días la vida en ausencia de Luscinda, y más habiéndola dejado con la tristeza que les he contado. Pero, con todo esto, obedecí, como buen criado, aunque veía que sería a costa de mi salud.

»Pero, a los cuatro días de haber llegado, apareció un hombre buscándome con una carta. Por el sobre, reconocí que era de Luscinda, porque la letra era suya. La abrí, temeroso y con sobresalto, creyendo que algo grave debía haberla impulsado a escribirme estando ausente, pues en persona rara vez lo hacía. Antes de leerla, le pregunté al hombre quién se la había dado y cuánto había tardado en el camino. Me dijo que, por casualidad, pasando por una calle de la ciudad a mediodía, una señora muy hermosa lo llamó desde una ventana, con los ojos llenos de lágrimas. Con mucha prisa le dijo: 'Hermano, si eres cristiano, como pareces, por amor de Dios te ruego que lleves enseguida esta carta al lugar y a la persona que indica el sobre, que todo es bien conocido, y con ello harás un gran servicio a nuestro Señor. Y, para que no te falten medios para hacerlo, toma lo que va en este pañuelo'. Y diciendo esto, me arrojó por la ventana un pañuelo donde venían atados cien reales y esta sortija de oro que aquí traigo, con esa carta que te he dado. Y luego, sin esperar mi respuesta, se retiró de la ventana; aunque primero vio cómo yo tomaba la carta y el pañuelo, y por señas le dije que haría lo que me mandaba. Y así, viéndome tan bien pagado por el trabajo que podía tomarme en traértela y conociendo por el sobre que eras tú a quien se enviaba, porque yo, señor, te conozco muy bien, y obligado también por las lágrimas de aquella hermosa señora, decidí no fiarme de nadie más, sino venir yo mismo a dártela. Y en dieciséis horas que hace que me la dio, he hecho el camino, que sabes que es de dieciocho leguas.

»Mientras el agradecido y nuevo mensajero me decía esto, yo estaba pendiente de sus palabras, y me temblaban las piernas de tal manera que apenas podía mantenerme en pie. Finalmente, abrí la carta y vi que contenía estas palabras: "La promesa que don Fernando te dio de hablar con tu padre para que hablara con el mío, la ha cumplido más para su propio beneficio que para el tuyo. Debes saber, señor, que él me ha pedido por esposa, y mi padre, convencido de la ventaja que él cree que don Fernando te ofrece, ha aceptado lo que él quiere, con tanta certeza que dentro de dos días se celebrará la boda, tan en secreto y a solas, que solo serán testigos los cielos y alguna gente de la casa. Imagina cómo estoy; si te conviene venir, ven a verlo; y si te quiero bien o no, el resultado de este asunto te lo demostrará. Quiera Dios que esta carta llegue a tus manos antes de que la mía tenga que unirse a la de quien tan mal sabe cumplir su palabra".

»Estas, en resumen, fueron las palabras que contenía la carta y las que me hicieron ponerme en camino de inmediato, sin esperar otra respuesta ni más dinero. Porque entonces comprendí claramente que no había sido la compra de los caballos, sino la de su propio deseo, lo que había movido a don Fernando a enviarme a ver a su hermano. El enfado que sentí contra don Fernando, junto con el temor de perder el tesoro que con tantos años de servicios y deseos había ganado, me dieron alas. Pues, casi como en un vuelo, al día siguiente llegué a mi pueblo, en el momento y la hora adecuados para ir a hablar con Luscinda. Entré en secreto y dejé la mula en la que venía en casa del buen hombre que me había traído la carta. Y la suerte quiso que en ese momento tuviera la fortuna de encontrar a Luscinda en la reja, testigo de nuestro amor. Luscinda me reconoció al instante, y yo la reconocí a ella; pero no como ella debería haberme reconocido a mí, ni yo a ella. Pero, ¿quién hay en el mundo que pueda presumir de haber penetrado y conocido el pensamiento confuso y el carácter cambiante de una mujer? Nadie, por cierto.

»Digo, pues, que, en cuanto Luscinda me vio, me dijo: "Cardenio, estoy vestida de novia; ya me están esperando en la sala el traidor de don Fernando y mi codicioso padre, con otros testigos, que antes lo serán de mi muerte que de mi boda. No te preocupes, amigo, sino procura estar presente en este sacrificio. Y si mis razones no pueden impedirlo, llevo escondida una daga que podrá impedir fuerzas más decididas, poniendo fin a mi vida y demostrándote la voluntad que te he tenido y te tengo". Yo le respondí, turbado y deprisa, temeroso de no tener tiempo para contestarle: "Señora, que tus acciones confirmen tus palabras; que si tú llevas una daga para demostrar tu valía, aquí llevo yo una espada para defenderte o para matarme si la suerte nos es adversa". No creo que pudiera oír todas estas palabras, porque sentí que la llamaban deprisa, porque el novio esperaba. Con esto se cerró la noche de mi tristeza, se me ocultó el sol de mi alegría: me quedé sin luz en los ojos y sin entendimiento. No atinaba a entrar en su casa, ni podía moverme a ningún lado. Pero, considerando lo importante que era mi presencia para lo que pudiera suceder en aquel caso, me animé lo más que pude y entré en su casa. Y como ya conocía muy bien todas sus entradas y salidas, y más con el alboroto que en secreto había en ella, nadie me vio. Así que, sin ser visto, tuve la oportunidad de esconderme en el hueco de una ventana de la misma sala, que estaba cubierto por los extremos de dos tapices. Desde allí podía ver, sin ser visto, todo lo que sucedía en la sala.

»¿Quién podría describir ahora los sobresaltos que me dio el corazón mientras estuve allí, los pensamientos que me asaltaron, las consideraciones que hice? Fueron tantas y tales, que ni se pueden decir ni es bueno que se digan. Baste con que sepan que el novio entró en la sala sin más adorno que la ropa que solía llevar. Lo acompañaba como padrino un primo hermano de Luscinda, y en toda la sala no había nadie de fuera, solo los criados de la casa. Poco después, salió de una habitación Luscinda, acompañada de su madre y de dos de sus doncellas, tan bien arreglada y compuesta como su condición y hermosura merecían, y como quien era la personificación de la elegancia y el garbo de la corte. Mi asombro y mi éxtasis no me permitieron mirar y notar en particular lo que llevaba puesto. Solo pude fijarme en los colores, que eran rojo y blanco, y en los destellos de las piedras y joyas del tocado y de todo el vestido. Pero por encima de todo destacaba la singular belleza de su hermoso cabello rubio; era tal que, en competencia com as preciosas piedras y las luces de cuatro antorchas que había en la sala, el suyo brillaba con más resplandor. ¡Oh, memoria, enemiga mortal de mi descanso! ¿De qué sirve recordarme ahora la incomparable belleza de aquella adorada enemiga mía? ¿No será mejor, cruel memoria, que me recuerdes y me muestres lo que hizo entonces, para que, movido por tan evidente agravio, procure, ya que no la venganza, al menos perder la vida? Señores, no se cansen de escuchar estas digresiones que hago; que mi pena no es de esas que se pueden o deben contar de forma breve y superficial, pues cada circunstancia suya me parece digna de un largo discurso.

A esto le respondió el cura que no solo no se cansaban de oírle, sino que les gustaban mucho los pequeños detalles que contaba, por ser tales, que merecían no pasarse en silencio y recibir la misma atención que la parte principal de la historia.

— «Digo, pues —prosiguió Cardenio—, que, estando todos en la sala, entró el cura de la parroquia y, tomando a los dos de la mano para hacer lo que se requiere en tal ceremonia, al decir: '¿Quiere usted, señora Luscinda, al señor don Fernando, que está presente, por su legítimo esposo, como lo manda la Santa Madre Iglesia?', yo saqué toda la cabeza y el cuello de entre los tapices. Con oídos muy atentos y el alma turbada, me puse a escuchar lo que Luscinda respondía, esperando de su respuesta la sentencia de mi muerte o la confirmación de mi vida. ¡Ah, quién se atreviera a salir entonces, gritando!: '¡Ah, Luscinda, Luscinda, mira lo que haces, considera lo que me debes, mira que eres mía y que no puedes ser de otro! ¡Advierte que tu sí y el fin de mi vida serán en el mismo instante! ¡Ah, traidor don Fernando, ladrón de mi gloria, muerte de mi vida! ¿Qué quieres? ¿Qué pretendes? Considera que cristianamente no puedes alcanzar tus deseos, porque Luscinda es mi esposa y yo soy su marido'. ¡Ah, loco de mí, ahora que estoy ausente y lejos del peligro, digo que debía haber hecho lo que no hice! ¡Ahora que dejé que me robaran mi más preciado tesoro, maldigo al ladrón, de quien podría vengarme si tuviera el corazón para ello como lo tengo para quejarme! En fin, como entonces fui cobarde y necio, no es de extrañar que muera ahora avergonzado, arrepentido y loco.

»El cura estaba esperando la respuesta de Luscinda, que se demoró un buen rato en darla. Y, cuando yo pensaba que sacaría la daga para demostrar su valía, o que desataría su lengua para decir alguna verdad o desengaño que me beneficiara, oí que dijo con voz débil y apagada: 'Sí, quiero'. Y lo mismo dijo don Fernando; y, dándole el anillo, quedaron unidos por un lazo indisoluble. El novio se acercó a abrazar a su esposa. Ella, poniéndose la mano sobre el corazón, cayó desmayada en los brazos de su madre. Queda ahora por decir cómo me quedé yo al ver, en el 'sí' que había oído, mis esperanzas burladas, y falsas las palabras y promesas de Luscinda. Imposibilitado de recuperar jamás el bien que en aquel instante había perdido. Me quedé sin saber qué hacer, desamparado, a mi parecer, por todo el cielo. Me sentí enemigo de la tierra que me sostenía, el aire me negaba el aliento para mis suspiros y el agua, la humedad para mis ojos. Solo el fuego creció de tal manera que todo yo ardía de rabia y de celos.

»Todos se alborotaron con el desmayo de Luscinda. Su madre, al desabrocharle el pecho para que le diera el aire, descubrió en él un papel cerrado. Don Fernando lo tomó enseguida y se puso a leerlo a la luz de una de las antorchas. Al terminar de leerlo, se sentó en una silla y se puso la mano en la mejilla, con aspecto de hombre muy pensativo, sin atender a los remedios que le hacían a su esposa para que volviera en sí. Yo, viendo alborotada a toda la gente de la casa, me aventuré a salir, sin importar si me veían o no. Estaba decidido, si me veían, a cometer una locura tal que todo el mundo comprendiera la justa indignación de mi pecho en el castigo del falso don Fernando, y también en el de la inconstante y desmayada traidora. Pero mi suerte, que me debe de tener guardado para mayores males, si es que los hay, quiso que en aquel momento me sobrara el entendimiento que después me ha faltado. Y así, sin querer vengarme de mis mayores enemigos (lo cual hubiera sido fácil, pues no me esperaban), quise tomar la justicia por mi mano y ejecutar en mí mismo el castigo que ellos merecían. Y quizás con más rigor del que habría usado con ellos si entonces les hubiera dado muerte, pues la muerte repentina acaba pronto con el sufrimiento, pero la que se alarga con tormentos siempre mata sin acabar con la vida.

»En fin, salí de aquella casa y fui a la de aquel donde había dejado la mula. Hice que me la ensillara, y sin despedirme de él, monté en ella y salí de la ciudad, sin atreverme, como un nuevo Lot, a volver la cara para mirarla. Y cuando me vi solo en el campo, y la oscuridad de la noche me cubría y su silencio me invitaba a quejarme, sin miedo a ser escuchado ni conocido, solté la voz y di rienda suelta a mi lengua con tantas maldiciones contra Luscinda y don Fernando, como si con ellas pudiera reparar el agravio que me habían hecho. La llamé cruel, ingrata, falsa y desagradecida; pero, sobre todo, codiciosa, pues la riqueza de mi enemigo le había cegado la voluntad.

»Finalmente, llegué a la conclusión de que poco amor, poco juicio, mucha ambición y deseos de grandeza la hicieron olvidar las palabras con las que me había engañado, entretenido y mantenido mis firmes esperanzas y honestos deseos. Con estas voces y con esta inquietud caminé lo que quedaba de aquella noche, y al amanecer llegué a la entrada de estas sierras. Caminé por ellas otros tres días, sin senda ni camino alguno, hasta que fui a parar a unos prados, que no sé en qué parte de estas montañas se encuentran. Allí pregunté a unos ganaderos dónde estaba la parte más áspera de estas sierras. Me dijeron que hacia esta parte. Hacia allí me dirigí, con la intención de acabar aquí con mi vida. Al entrar en estas asperezas, mi mula cayó muerta de cansancio y de hambre, o, lo que yo más creo, para deshacerse de una carga tan inútil como yo. Me quedé a pie, agotado por la naturaleza, muerto de hambre, sin tener, ni pensar en buscar, a nadie que me ayudara.

»De esa manera estuve no sé cuánto tiempo, tendido en el suelo. Al cabo del cual, me levanté sin hambre y encontré junto a mí a unos cabreros, que, sin duda, debieron de ser los que remediaron mi necesidad. Porque ellos me contaron cómo me habían encontrado y cómo estaba diciendo tantos disparates y desatinos, que daba claros indicios de haber perdido el juicio. Y yo he sentido en mí, desde entonces, que no siempre estoy completamente cuerdo, sino tan deteriorado y débil que hago mil locuras: me rasgo la ropa, doy voces por estas soledades, maldigo mi suerte y repito en vano el nombre amado de mi enemiga, sin tener otro pensamiento ni intención entonces que intentar acabar con mi vida gritando. Y cuando vuelvo en mí, me encuentro tan cansado y agotado que apenas puedo moverme. Normalmente vivo en el hueco de un alcornoque, lo suficientemente grande para cubrir este miserable cuerpo. Los vaqueros y cabreros que andan por estas montañas, movidos por la caridad, me alimentan, dejándome la comida en los caminos y en las rocas por donde creen que podré pasar y encontrarla. Y así, aunque en esos momentos me falte el juicio, la necesidad natural me hace reconocer el alimento y despierta en mí el deseo de quererlo y la voluntad de tomarlo. Otras veces me dicen ellos, cuando me encuentran en mi sano juicio, que salgo a los caminos y que les quito la comida por la fuerza a los pastores que la llevan del pueblo a las majadas, aunque me la den de buen grado.

»De esta manera paso mi miserable y extrema vida, hasta que el cielo quiera llevarla a su fin último, o borrar de mi memoria la hermosura y la traición de Luscinda y el agravio de don Fernando. Que si él hace esto sin quitarme la vida, yo volveré a pensar con más claridad; si no, no queda sino rogarle que tenga misericordia de mi alma, pues no siento en mí el valor ni las fuerzas para sacar mi cuerpo de este aprieto en que por mi gusto he querido ponerme». Ésta es, ¡oh señores!, la amarga...

Aquí Cardenio terminó su larga y triste historia de amor. Y, en el momento en que el cura se disponía a decirle algunas palabras de consuelo, lo interrumpió una voz que llegó a sus oídos. En acentos lastimeros oyeron que decía lo que se contará en la cuarta parte de esta narración, pues en este punto el sabio y atento historiador Cide Hamete Benengeli dio fin a la tercera.

Cuarta parte del ingenioso hidalgo don Quijote de la Mancha

`,
}
