export const chapter_28 = {
	name: 'Capítulo XXVIII',
	header: 'Que trata de la nueva y agradable aventura que al cura y barbero sucedió en la mesma sierra',
	text: `Fueron tiempos muy felices y afortunados aquellos en los que vino al mundo el audacísimo caballero don Quijote de la Mancha. Gracias a que tuvo la honrosa determinación de querer resucitar y devolver al mundo la ya perdida y casi muerta orden de la caballería andante, ahora, en nuestra época, tan necesitada de alegres entretenimientos, gozamos no solo de la dulzura de su verdadera historia, sino también de los cuentos y episodios que contiene. Estos, en parte, no son menos agradables, ingeniosos y verdaderos que la misma historia. Y esta, prosiguiendo su enredado hilo, cuenta que, justo cuando el cura se preparaba para consolar a Cardenio, lo interrumpió una voz que llegó a sus oídos y que, con acento triste, decía así:

— ¡Ay, Dios! ¿Será posible que ya he hallado un lugar que pueda servir de tumba escondida para la pesada carga de este cuerpo que sostengo contra mi voluntad? Sí, será posible, si la soledad que prometen estas sierras no me engaña. ¡Ay, infeliz de mí! ¡Qué agradable compañía me harán estos riscos y malezas, pues me darán la oportunidad de comunicar mis desgracias al cielo con mis quejas! Mucho mejor que la de cualquier ser humano, pues no hay nadie en la tierra de quien se pueda esperar consejo en las dudas, alivio en las quejas, ni remedio en los males.

El cura y los que estaban con él oyeron y percibieron todas estas palabras. Y como les pareció, y así era, que se decían muy cerca, se levantaron a buscar a su dueño. No habían andado veinte pasos, cuando detrás de un peñasco vieron, sentado al pie de un fresno, a un joven vestido de campesino. Como tenía el rostro inclinado porque se estaba lavando los pies en el arroyo que por allí corría, no pudieron vérselo en ese momento. Se acercaron con tanto silencio que él no los sintió, pues solo estaba atento a lavarse los pies, que parecían dos pedazos de cristal blanco nacidos entre las otras piedras del arroyo. Les sorprendió la blancura y belleza de los pies, y les pareció que no estaban hechos para pisar la tierra ni para andar tras el arado y los bueyes, como indicaba la ropa de su dueño. Y así, viendo que no habían sido sentidos, el cura, que iba delante, hizo señas a los otros dos para que se escondieran detrás de unas rocas que allí había. Así lo hicieron todos, mirando con atención lo que el joven hacía. Llevaba puesta una capa parda de dos faldones, muy ajustada al cuerpo con una toalla blanca. Llevaba, asimismo, unos calzones y polainas de paño pardo, y en la cabeza una gorra también parda. Tenía las polainas subidas hasta la mitad de la pierna, que, sin duda alguna, parecía de alabastro blanco. Terminó de lavarse los hermosos pies y luego, con un pañuelo que sacó de debajo de la gorra, se los secó. Y, al quitársela, levantó el rostro, y los que lo miraban tuvieron la oportunidad de ver una hermosura incomparable. Era tal, que Cardenio le dijo al cura en voz baja:

— Esta, si no es Luscinda, no es una persona humana, sino divina.

La joven se quitó la gorra y, al sacudir la cabeza a un lado y a otro, se le empezó a soltar y a esparcir una cabellera que podría despertar la envidia del mismo sol. Con esto se dieron cuenta de que quien parecía un campesino era en realidad una mujer, y además, delicada, y la más hermosa que sus ojos habían visto hasta entonces; incluso para Cardenio, si no hubiera conocido a Luscinda, pues después afirmó que solo la belleza de Luscinda podía competir con aquella. Sus largos y rubios cabellos no solo le cubrían la espalda, sino que la envolvían por completo, de tal manera que, a excepción de los pies, no se veía ninguna otra parte de su cuerpo. Para peinarse, usó sus manos, que, si en el agua los pies parecían pedazos de cristal, entre los cabellos semejaban trozos de nieve compacta. Todo esto aumentaba la admiración y el deseo de los tres hombres por saber quién era.

Por eso decidieron mostrarse. Y al movimiento que hicieron para ponerse de pie, la hermosa muchacha levantó la cabeza y, apartándose el pelo de la cara con ambas manos, miró a quienes hacían el ruido. Apenas los vio, se puso de pie y, sin esperar a calzarse ni a recogerse el pelo, agarró rápidamente un bulto, como de ropa, que tenía junto a sí, e intentó huir, llena de turbación y susto. Pero no había dado seis pasos cuando, al no poder soportar sus delicados pies la aspereza de las piedras, cayó al suelo. Al ver esto, los tres corrieron hacia ella, y el cura fue el primero en decirle:
— Deténgase, señora, sea quien sea, que los que aquí ve no tienen otra intención que la de servirla. No hay motivo para que emprenda una huida tan inútil, porque ni sus pies podrán soportarlo ni nosotros lo permitiremos.

A todo esto, ella no respondía palabra, atónita y confusa. Se acercaron a ella y, tomándola de la mano, el cura prosiguió:

— Lo que su atuendo, señora, nos oculta, su cabello nos lo revela. Son señales claras de que no deben de ser de poca importancia las causas que han disfrazado su belleza con una ropa tan indigna y la han traído a una soledad como esta. Ha sido una suerte encontrarla, si no para dar remedio a sus males, al menos para aconsejarla. Pues ningún mal puede ser tan agotador, ni llegar a tal extremo, mientras no se acaba la vida, como para negarse a escuchar siquiera el consejo que con buena intención se le da al que lo padece. Así que, señora mía, o señor mío, o lo que usted quiera ser, pierda el susto que nuestra presencia le ha causado y cuéntenos su buena o mala suerte. En nosotros juntos, o en cada uno por separado, encontrará a quien le ayude a sentir sus desgracias.

Mientras el cura decía estas palabras, la joven disfrazada estaba como absorta, mirándolos a todos, sin mover los labios ni decir nada, como un campesino rústico al que de repente le muestran cosas raras y nunca vistas. Pero, volviendo el cura a decirle otras razones con el mismo propósito, ella, dando un profundo suspiro, rompió el silencio y dijo:

— Ya que la soledad de estas sierras no ha sido suficiente para esconderme, ni la libertad de mi pelo suelto ha permitido que mi lengua mienta, sería inútil fingir ahora de nuevo algo que, de ser creído, sería más por cortesía que por cualquier otra razón. Dicho esto, señores, les agradezco el ofrecimiento que me han hecho, el cual me obliga a complacerlos en todo lo que me han pedido. Aunque temo que el relato que les haga de mis desdichas les causará, además de compasión, tristeza, porque no encontrarán remedio para solucionarlas ni consuelo para sobrellevarlas. Pero, a pesar de todo, para que mi honor no quede en entredicho ante ustedes, ya que me han reconocido como mujer y me ven joven, sola и con esta ropa —cosas todas que, juntas o por separado, pueden destruir cualquier buena reputación—, tendré que decir lo que preferiría callar si pudiera.

Todo esto lo dijo sin detenerse aquella que parecía una mujer tan hermosa, con una lengua tan suelta y una voz tan suave, que su inteligencia no les admiró menos que su belleza. Y, volviéndole a hacer nuevos ofrecimientos y ruegos para que cumpliera lo prometido, ella, sin hacerse más de rogar, se calzó con toda decencia y se recogió el pelo. Se acomodó en el asiento de una piedra y, con los tres sentados a su alrededor, haciendo un esfuerzo por contener unas lágrimas que le asomaban a los ojos, con voz tranquila y clara, comenzó la historia de su vida de esta manera:

— «En esta Andalucía hay un lugar del que toma título un duque, que lo convierte en uno de los que llaman “grandes” en España. Este tiene dos hijos: el mayor, heredero de su estado y, al parecer, de sus buenas costumbres; y el menor, no sé de qué es heredero, sino de las traiciones de Vellido y de los engaños de Galalón. Mis padres son vasallos de este señor, humildes de linaje, pero tan ricos que si sus bienes naturales igualaran a los de su fortuna, ni ellos tendrían más que desear ni yo temería verme en la desdicha en que me veo. Porque quizás mi mala suerte nace de la que no tuvieron ellos al no haber nacido nobles. Es verdad que no son tan humildes como para avergonzarse de su condición, ni tan nobles como para quitarme la idea de que de su humildad viene mi desgracia. Ellos, en fin, son labradores, gente sencilla, sin mezcla de ninguna raza de mala fama y, como suele decirse, cristianos viejos de pura cepa. Pero son tan ricos que su riqueza y su magnífico estilo de vida les van ganando poco a poco el nombre de hidalgos, e incluso de caballeros. Aunque la mayor riqueza y nobleza de la que se enorgullecían era de tenerme a mí por hija. Y, así, por no tener otra ni otro que los heredase, y por ser padres cariñosos, yo era una de las hijas más mimadas que jamás hayan existido. Era el espejo en que se miraban, el bastón de su vejez, y el objetivo al que encaminaban todos sus deseos, comparándolos con el cielo. Y como ellos eran tan buenos, los míos no se desviaban ni un punto de los suyos. Y de la misma manera que yo era dueña de sus corazones, así lo era de su hacienda. Por mí se contrataban y despedían los criados; la administración y cuenta de lo que se sembraba y cosechaba pasaba por mis manos; los molinos de aceite, las bodegas de vino, el número del ganado mayor y menor, el de las colmenas. Finalmente, de todo aquello que un labrador tan rico como mi padre puede tener y tiene, yo llevaba la cuenta, y era la administradora y señora, con tanta dedicación por mi parte y con tanto gusto por la suya, que de buen grado...»

No bien había nombrado a don Fernando la que contaba el cuento, cuando a Cardenio se le cambió el color del rostro y comenzó a sudar, con una alteración tan grande que el cura y el barbero, que se fijaron en ello, temieron que le sobreviniera aquel ataque de locura que habían oído decir que le daba de vez en cuando. Pero Cardenio no hizo más que sudar y quedarse quieto, mirando fijamente a la campesina, imaginando quién era ella. La cual, sin darse cuenta de los movimientos de Cardenio, prosiguió su historia, diciendo:

— «Y apenas me vieron cuando, según dijo él después, quedó tan enamorado de mí como bien lo demostraron sus acciones. Pero, por acabar pronto con el cuento, que no lo tiene, de mis desdichas, quiero pasar por alto las diligencias que hizo don Fernando para declararme su amor. Sobornó a toda la gente de mi casa, dio y ofreció regalos y favores a mis parientes. Todos los días eran de fiesta y de regocijo en mi calle; por las noches, las músicas no dejaban dormir a nadie. Las cartas que, sin saber cómo, llegaban a mis manos, eran infinitas, llenas de palabras de amor y ofrecimientos, con más promesas y juramentos que letras. Todo lo cual no solo no me ablandaba, sino que me endurecía como si fuera mi enemigo mortal, y como si todas las obras que hacía para doblegar mi voluntad las hiciera para el efecto contrario. No porque a mí me pareciera mal la amabilidad de don Fernando, ni porque me molestaran en exceso sus atenciones. Porque me daba una cierta alegría verme tan querida y estimada por un caballero tan principal, y no me pesaba ver en sus cartas mis alabanzas; que en esto, por feas que seamos las mujeres, me parece que siempre nos gusta oír que nos llaman hermosas. Pero a todo esto se oponían mi honestidad y los continuos consejos que me daban mis padres, que ya conocían muy abiertamente la voluntad de don Fernando, porque a él ya no le importaba que todo el mundo la supiera. Mis padres me decían que solo en mi virtud y bondad dejaban y depositaban su honra y su fama, y que considerara la desigualdad que había entre don Fernando y yo. Así me daría cuenta de que sus pensamientos, aunque él dijera otra cosa, se encaminaban más a su propio placer que a mi bien. Y que si yo quería poner algún tipo de obstáculo para que él abandonara su injusta pretensión, ellos me casarían enseguida con quien yo más quisiera, ya fuera de los más principales de nuestro pueblo o de todos los alrededores, pues todo se podía esperar de nuestra gran riqueza.»

»Todas estas precauciones mías, que él debía de tomar por desdenes, debieron de ser la causa de avivar más su deseo lascivo, que este nombre quiero dar a la voluntad que me mostraba. La cual, si hubiera sido como debía, ustedes no la sabrían ahora, porque no habría habido ocasión de contársela. Finalmente, don Fernando supo que mis padres andaban buscándome marido para quitarle a él la esperanza de poseerme, o, al menos, para que yo tuviera más guardianes que me vigilaran. Y esta noticia o sospecha fue la causa de que hiciera lo que ahora oirán. Y fue que una noche, estando yo en mi habitación con la única compañía de una doncella que me servía, con las puertas bien cerradas por temor a que, por descuido, mi honestidad se viera en peligro, sin saber ni imaginar cómo, en medio de estas precauciones y prevenciones, y en la soledad de este silencio y encierro, me lo encontré delante. Su vista me turbó de tal manera que me quitó la de mis ojos y me enmudeció la lengua. Y así, no fui capaz de gritar, ni creo que él me hubiera dejado hacerlo, porque enseguida se acercó a mí y, tomándome en sus brazos (porque yo, como digo, no tuve fuerzas para defenderme, según estaba de turbada), comenzó a decirme tales razones, que no sé cómo es posible que la mentira tenga tanta habilidad para componerlas de modo que parezcan tan verdaderas. El traidor hacía que sus lágrimas dieran crédito a sus palabras y sus suspiros a su intención. Yo, pobrecita, sola entre los míos, poco experimentada en casos semejantes, comencé, no sé de qué modo, a tomar por verdaderas tantas falsedades, pero no de tal suerte que sus lágrimas y suspiros me movieran a una compasión menos que buena.

»Y así, pasándoseme aquel primer susto, recuperé un poco el ánimo perdido, y con más valentía de la que pensé que podría tener, le dije: "Señor, si en lugar de estar en sus brazos, estuviera entre los de un león feroz, y me aseguraran que me libraría de ellos si hacía o decía algo en perjuicio de mi honestidad, tan imposible sería hacerlo o decirlo como es posible que lo que fue deje de haber sido. Así que, si usted tiene mi cuerpo ceñido con sus brazos, yo tengo mi alma atada a mis buenos deseos, que son tan diferentes de los suyos como verá si, a la fuerza, quiere seguir adelante con ellos. Soy su vasalla, pero no su esclava; ni la nobleza de su sangre tiene ni debe tener poder para deshonrar y menospreciar la humildad de la mía. Y tanto me estimo yo, campesina y labradora, como usted, señor y caballero. Conmigo, su fuerza no tendrá ningún efecto, ni su riqueza valor alguno, ni sus palabras podrán engañarme, ni sus suspiros y lágrimas enternecerme. Si alguna de todas estas cosas que he dicho viera yo en el que mis padres me dieran por esposo, a su voluntad se ajustaría la mía, y mi voluntad no se apartaría de la suya. De modo que, si quedara con honra, aunque quedara sin gusto, de buen grado le entregaría lo que usted, señor, ahora con tanta fuerza procura. Todo esto lo he dicho porque no debe pensar que de mí conseguirá algo quien no sea mi legítimo esposo". "Si no te detiene más que eso, bellísima Dorotea" —que este es el nombre de esta desdichada—, dijo el desleal caballero, "mira, aquí te doy mi mano para ser tuyo, y que sean testigos de esta verdad los cielos, a quienes nada se esconde, y esta imagen de Nuestra Señora que aquí tienes".»

Cuando Cardenio le oyó decir que se llamaba Dorotea, volvió a sentir sus sobresaltos y acabó de confirmar como verdadera su primera opinión. Pero no quiso interrumpir el cuento, para ver en qué acababa lo que él ya casi sabía. Solo dijo:

— ¿Que Dorotea es su nombre, señora? He oído hablar de otra del mismo nombre que quizás comparte sus desdichas. Siga adelante, que ya llegará el momento en que le diga cosas que la asombrarán tanto como la lastimarán.
Dorotea se fijó en las palabras de Cardenio y en su extraño y desastroso atuendo, y le rogó que si sabía algo de su situación, se lo dijera de inmediato. Porque si algo bueno le había dejado la fortuna, era el ánimo que tenía para sufrir cualquier desastre que le sobreviniera, segura de que, a su parecer, ninguno podía llegar que aumentara ni un punto el que ya tenía.

— No lo perdería yo, señora —respondió Cardenio—, en decirle lo que pienso, si fuera verdad lo que imagino; y hasta ahora no se pierde la oportunidad, ni a usted le importa nada saberlo.

— Sea lo que sea —respondió Dorotea—, «lo que en mi cuento pasa fue que, tomando don Fernando una imagen que en aquella habitación había, la puso por testigo de nuestra boda. Con palabras muy eficaces y juramentos extraordinarios, me dio su palabra de ser mi marido. Aunque, antes de que terminara de decirlas, le dije que mirara bien lo que hacía y que considerara el enfado que su padre se llevaría al verlo casado con una campesina vasalla suya. Que no lo cegara mi hermosura, la que fuera, pues no era suficiente para hallar en ella disculpa de su error. Y que si algún bien me quería hacer, por el amor que me tenía, que fuera dejar correr mi suerte al nivel de mi condición, porque los matrimonios tan desiguales nunca se disfrutan ni duran mucho con el mismo gusto con que empiezan.»

»Todas estas razones que aquí he dicho le dije, y otras muchas que no recuerdo, pero no fueron suficientes para que él dejara de seguir su intento. Así como el que no piensa pagar, que, al cerrar un trato, no repara en inconvenientes. Yo, en ese momento, hice un breve razonamiento conmigo misma, y me dije: "Bueno, no seré yo la primera que por vía de matrimonio haya subido de un estado humilde a uno grande, ni será don Fernando el primero a quien la hermosura, o una ciega afición, que es lo más cierto, le haya hecho tomar una compañía desigual a su grandeza. Pues si no hago nada nuevo ni fuera de lo común, bien está aceptar esta honra que la suerte me ofrece, aunque la voluntad que me muestra no dure más que lo que dure el cumplimiento de su deseo. Que, al fin y al cabo, para con Dios seré su esposa. Y si quiero rechazarlo con desdenes, veo que está en una situación en la que, si no actúa como debe, usará la fuerza, y yo quedaré deshonrada y sin disculpa por la culpa que me podría atribuir quien no supiera cuán sin ella he llegado a este punto. Porque, ¿qué razones serían suficientes para persuadir a mis padres, y a otros, de que este caballero entró en mi habitación sin mi consentimiento?"»

»Todas estas preguntas y respuestas revolví yo en un instante en mi imaginación. Y, sobre todo, comenzaron a convencerme y a inclinarme a lo que fue, sin yo pensarlo, mi perdición: los juramentos de don Fernando, los testigos que ponía, las lágrimas que derramaba y, finalmente, su porte y su gentileza, que, acompañados de tantas muestras de verdadero amor, podrían haber rendido a otro corazón tan libre y recatado como el mío. Llamé a mi criada para que en la tierra acompañara a los testigos del cielo. Don Fernando volvió a reiterar y confirmar sus juramentos, añadió nuevos santos como testigos a los primeros, se echó mil maldiciones futuras si no cumplía lo que me prometía. Volvió a humedecer sus ojos y a aumentar sus suspiros, me apretó más entre sus brazos, de los que nunca me había soltado. Y con esto, y con que mi doncella volviera a salir de la habitación, yo dejé de serlo y él acabó de ser un traidor.

»El día que siguió a la noche de mi desgracia no llegaba tan deprisa como yo creo que don Fernando deseaba, porque, después de cumplido lo que el apetito pide, el mayor gusto que puede haber es apartarse de donde se alcanzó. Digo esto porque don Fernando se apresuró a marcharse, y por obra de mi doncella, que fue la misma que lo había traído, antes del amanecer ya estaba en la calle. Y, al despedirse de mí, aunque no con tanta insistencia y vehemencia como cuando vino, me dijo que estuviera segura de su fe y de que sus juramentos eran firmes y verdaderos. Y, para mayor confirmación de su palabra, se sacó un rico anillo del dedo y me lo puso en el mío. En efecto, él se fue y yo me quedé no sé si triste o alegre. Lo que sí sé decir es que me quedé confusa y pensativa, y casi fuera de mí con el nuevo acontecimiento. Y no tuve ánimo, o no se me ocurrió, regañar a mi doncella por la traición cometida de encerrar a don Fernando en mi misma habitación, porque aún no me decidía si lo que me había sucedido era bueno o malo. Al partir, le dije a don Fernando que por el mismo camino que había usado aquella vez podía verme otras noches, pues ya era suya, hasta que, cuando él quisiera, aquello se hiciera público. Pero no vino ninguna otra noche, si no fue la siguiente, ni pude verlo en la calle ni en la iglesia en más de un mes. En vano me cansé de buscarlo, aunque supe que estaba en el pueblo y que la mayoría de los días iba de caza, un ejercicio que le gustaba mucho. Bien sé yo que estos días y estas horas fueron para mí aciagos y desgraciados, y bien sé que en ellos comencé a dudar, e incluso a desconfiar de la fe de don Fernando. Y sé también que mi doncella oyó entonces las palabras de regaño por su atrevimiento que antes no había oído. Y sé que me vi obligada a contener mis lágrimas y a componer mi rostro para no dar ocasión a que mis padres me preguntasen por qué andaba descontenta y me obligaran a inventarles mentiras.

— Pero todo esto se acabó en un instante...»

Cardenio oyó el nombre de Luscinda y no hizo otra cosa que encogerse de hombros, morderse los labios, arquear las cejas y, poco después, dejar caer de sus ojos dos fuentes de lágrimas. Pero Dorotea no por eso dejó de seguir su cuento, diciendo:

— «Esta triste noticia llegó a mis oídos y, en lugar de helárseme el corazón al oírla, fue tanta la cólera y la rabia que se encendió en él, que faltó poco para que no saliera a la calle gritando, publicando la traición que se me había hecho. Pero esa furia se calmó por entonces al pensar en poner en práctica esa misma noche lo que hice: que fue ponerme este atuendo, que me dio uno de los que llaman “zagales” en casa de los labradores, que era criado de mi padre. A él le descubrí toda mi desventura y le rogué que me acompañara hasta la ciudad donde creía que estaba mi enemigo. Él, después de haber criticado mi atrevimiento y reprobado mi decisión, al verme resuelta en mi parecer, se ofreció a hacerme compañía, como él dijo, hasta el fin del mundo. Luego, al momento, guardé en una funda de almohada un vestido de mujer, y algunas joyas y dinero, por lo que pudiera pasar. Y en el silencio de aquella noche, sin avisar a mi traidora doncella, salí de mi casa, acompañada de mi criado y de muchas imaginaciones, y me puse en camino hacia la ciudad a pie, llevada en volandas por el deseo de llegar, ya no para impedir lo que daba por hecho, sino al menos para decirle a don Fernando que me explicara con qué alma lo había hecho. »Llegué en dos días y medio adonde quería, y, al entrar en la ciudad, pregunté por la casa de los padres de Luscinda. Y el primero al que le pregunté me respondió más de lo que yo quisiera oír. Me indicó la casa y todo lo que había sucedido en la boda de su hija, algo tan público en la ciudad, que se cuenta en corrillos por todas partes. Me dijo que la noche en que don Fernando se casó con Luscinda, después de que ella diera el “sí” para ser su esposa, le había dado un fuerte desmayo. Y que, al acercarse su esposo a desabrocharle el pecho para que le diera el aire, le encontró un papel escrito con la misma letra de Luscinda, en el que decía y declaraba que ella no podía ser esposa de don Fernando, porque ya lo era de Cardenio.»

»Todo esto era público y notorio en toda la ciudad, y todos hablaban de ello. Y más hablaron cuando supieron que Luscinda había desaparecido de casa de sus padres y de la ciudad, pues no la encontraron por ninguna parte. Sus padres estaban desesperados y no sabían qué hacer para encontrarla. Esto que supe reavivó mis esperanzas, y consideré que era mejor no haber encontrado a don Fernando que encontrarlo casado. Me pareció que aún no estaba del todo cerrada la puerta a mi remedio, y me convencí de que quizás el cielo había puesto aquel impedimento en el segundo matrimonio para hacerle recordar lo que debía al primero, y para que se diera cuenta de que era cristiano y que estaba más obligado a su alma que a las apariencias humanas. Todas estas cosas revolvía en mi fantasía, y me consolaba sin tener consuelo, aferrándome a unas esperanzas lejanas y débiles para soportar la vida, que ya aborrezco.

»Estando, pues, en la ciudad, sin saber qué hacerme, ya que no encontraba a don Fernando, llegó a mis oídos un pregón público, donde se prometía una gran recompensa a quien me encontrara, dando las señas de mi edad y de la misma ropa que llevaba. Y oí decir que se rumoreaba que el joven que vino conmigo me había sacado de casa de mis padres, cosa que me dolió en el alma, al ver cuán bajo había caído mi crédito. Pues no bastaba con perderlo por mi huida, sino que además se añadía con quién, siendo una persona tan inferior y tan indigna de mis buenos pensamientos. En cuanto oí el pregón, me fui de la ciudad con mi criado, que ya empezaba a dar muestras de dudar en la promesa de fidelidad que me había hecho. Y aquella noche nos adentramos en lo más espeso de esta montaña, con el miedo de que nos encontraran. Pero, como suele decirse, un mal llama a otro, y el fin de una desgracia suele ser el principio de otra mayor, así me sucedió a mí. Porque mi buen criado, hasta entonces fiel y seguro, en cuanto me vio en esta soledad, incitado por su propia maldad más que por mi hermosura, quiso aprovecharse de la ocasión que, a su parecer, estos lugares deshabitados le ofrecían. Y, con poca vergüenza y menos temor de Dios ni respeto por mí, me declaró su amor. Y viendo que yo, con palabras feas y justas, respondía a la desvergüenza de sus propósitos, dejó de lado los ruegos, con los que primero pensó tener éxito, y comenzó a usar la fuerza. Pero el justo cielo, que pocas o ninguna vez deja de mirar y favorecer a las justas intenciones, favoreció las mías, de manera que con mis pocas fuerzas, y con poco trabajo, lo empujé por un despeñadero, donde lo dejé, sin saber si muerto o vivo. Y luego, con más ligereza de la que mi susto y mi cansancio permitían, me adentré en estas montañas, sin más pensamiento ni plan que esconderme en ellas y huir de mi padre y de aquellos que, de su parte, me andaban buscando.

»Con este deseo, hace no sé cuántos meses que entré en ellas, donde encontré a un ganadero que me llevó como su criado a un lugar que está en las entrañas de esta sierra. Al cual he servido de zagal todo este tiempo, procurando estar siempre en el campo para ocultar estos cabellos que ahora, tan sin pensarlo, me han descubierto. Pero toda mi astucia y toda mi dedicación fueron inútiles, pues mi amo se dio cuenta de que yo no era un hombre, y nació en él el mismo mal pensamiento que en mi criado. Y, como no siempre la fortuna da remedios junto con los trabajos, no encontré despeñadero ni barranco desde donde arrojar y librar de penas al amo, como lo encontré para el criado. Y así, consideré que era un inconveniente menor dejarlo y esconderme de nuevo entre estas asperezas que probar con él mis fuerzas o mis excusas. Digo, pues, que volví a esconderme en el bosque, y a buscar un lugar donde, sin impedimento alguno, pudiera con suspiros y lágrimas rogar al cielo que se apiade de mi desventura y me dé ingenio y favor para salir de ella, o para dejar la vida entre estas soledades, sin que quede memoria de esta triste, que tan sin culpa suya habrá dado materia para que de ella se hable y murmure en su tierra y en las ajenas.»

`,
}