// Адаптированный текст
export const chapter_25 = {
	name: 'Capítulo XXV',
	header: 'Que trata de las extrañas cosas que en Sierra Morena sucedieron al valiente caballero de la Mancha, y de la imitación que hizo a la penitencia de Beltenebros',
	text: `Don Quijote se despidió del cabrero y, subiendo otra vez sobre Rocinante, le mandó a Sancho que lo siguiera. Sancho lo hizo, con su burro, de muy mala gana. Se iban adentrando poco a poco en lo más áspero de la montaña, y Sancho se moría por hablar con su amo. Deseaba que él comenzara la conversación para no contravenir la orden que le tenía dada. Pero, no pudiendo soportar tanto silencio, le dijo:

—Señor don Quijote, écheme su bendición y déme licencia. Desde aquí me quiero volver a mi casa, con mi mujer y mis hijos, con quienes, por lo menos, hablaré y conversaré todo lo que quiera. Porque querer usted que vaya con él por estos lugares solitarios, de día y de noche, y que no le hable cuando me apetezca, es enterrarme en vida. Si la suerte quisiera que los animales hablaran, como en tiempos de Esopo, sería menos malo, porque yo conversaría con mi burro lo que me viniera en gana y con esto pasaría mi mala fortuna. Es una cosa dura, y que no se puede soportar con paciencia, andar buscando aventuras toda la vida para no encontrar sino patadas, manteos, ladrillazos y puñetazos. Y con todo esto, nos hemos de coser la boca, sin atrevernos a decir lo que uno tiene en el corazón, como si fuera mudo.

—Ya te entiendo, Sancho —respondió don Quijote—. Te mueres porque te levante la prohibición que te tengo puesta en la lengua. Dala por levantada y di lo que quieras, con la condición de que este levantamiento no ha de durar más que mientras andemos por estas sierras.

—Que así sea —dijo Sancho—. Hable yo ahora, que después Dios sabe lo que será. Y comenzando a gozar de este salvoconducto, digo: ¿qué necesidad tenía usted de defender tanto a aquella reina Madásima, o como se llame? ¿O qué importaba que aquel abad fuera su amigo o no? Si usted hubiera pasado de ello, pues no era su juez, bien creo yo que el loco habría seguido con su historia, y se habrían ahorrado el golpe de la piedra, las patadas y aun más de seis bofetadas.

—En verdad, Sancho —respondió don Quijote—, si tú supieras, como yo lo sé, cuán honrada y principal señora era la reina Madásima, yo sé que dirías que tuve mucha paciencia, pues no rompí la boca por donde tales blasfemias salieron. Porque es una gran blasfemia decir o pensar que una reina esté amancebada con un cirujano. La verdad de la historia es que aquel maestro Elisabat que el loco mencionó fue un hombre muy prudente y de muy sanos consejos, y sirvió de tutor y médico a la reina. Pero pensar que ella era su amante es un disparate digno de un gran castigo. Y para que veas que Cardenio no supo lo que dijo, has de advertir que cuando lo dijo ya estaba fuera de sí.

—Eso digo yo —dijo Sancho—. No había por qué hacer caso de las palabras de un loco. Porque si la buena suerte no lo hubiera ayudado a usted y hubiera dirigido la piedra a la cabeza, como la dirigió al pecho, ¡buena la habríamos hecho por defender a aquella mi señora, que Dios confunda! ¡Vaya si Cardenio no se habría librado por loco!

—Contra cuerdos y contra locos está obligado cualquier caballero andante a defender la honra de las mujeres, cualesquiera que sean, y más aún la de las reinas de tan alta alcurnia y provecho como fue la reina Madásima, a quien yo tengo particular afición por sus buenas cualidades. Porque, además de haber sido hermosa, fue muy prudente y muy sufrida en sus calamidades, que las tuvo muchas. Y los consejos y la compañía del maestro Elisabat le fueron de mucho provecho y alivio para poder llevar sus trabajos con prudencia y paciencia. Y de aquí tomó ocasión el vulgo ignorante y mal intencionado de decir y pensar que ella era su amante. Y mienten, digo otra vez, y mentirán doscientas veces más todos los que tal piensen y digan.

—Ni yo lo digo ni lo pienso —respondió Sancho—. Allá ellos; con su pan se lo coman. Si fueron amancebados o no, a Dios habrán dado cuenta. De mis viñas vengo, no sé nada; no soy amigo de saber vidas ajenas. Que el que compra y miente, en su bolsa lo siente. Además, desnudo nací, desnudo me hallo: ni pierdo ni gano. Pero, ¿y si lo fueran, qué me importa a mí? Y muchos piensan que hay tocinos y no hay estacas. Mas, ¿quién puede ponerle puertas al campo? Y además, ¡hasta de Dios han hablado!

—¡Válgame Dios —dijo don Quijote—, y qué de necedades vas ensartando, Sancho! ¿Qué tiene que ver lo que tratamos con los refranes que hilos? Por tu vida, Sancho, que te calles. Y de aquí en adelante, ocúpate de arrear a tu burro y deja de meterte en lo que no te importa. Y entiende con todos tus cinco sentidos que todo cuanto yo he hecho, hago y haré, va muy puesto en razón y muy conforme a las reglas de la caballería, que las sé mejor que cuantos caballeros las profesaron en el mundo.

—Señor —respondió Sancho—, ¿y es buena regla de caballería que andemos perdidos por estas montañas, sin senda ni camino, buscando a un loco, al cual, después de encontrarlo, quizás le venga en gana acabar lo que dejó comenzado, no de su cuento, sino de la cabeza de usted y de mis costillas, acabando de rompérnoslas del todo?

—Calla, te digo otra vez, Sancho —dijo don Quijote—. Porque te hago saber que no solo me trae por estas partes el deseo de encontrar al loco, sino también el que tengo de hacer aquí una proeza con la que he de ganar perpetuo nombre y fama en todo lo descubierto de la tierra. Y será tal, que he de poner con ella el sello a todo aquello que puede hacer perfecto y famoso a un caballero andante.

—¿Y es de muy gran peligro esa proeza? —preguntó Sancho Panza.

—No —respondió el de la Triste Figura—, aunque podría darse el caso de que tuviéramos mala suerte en lugar de buena. Pero todo dependerá de tu diligencia.

—¿De mi diligencia? —dijo Sancho.

—Sí —dijo don Quijote—. Porque si vuelves pronto de adonde pienso enviarte, pronto se acabará mi pena y pronto comenzará mi gloria. Y para no tenerte más en suspenso, esperando en qué han de parar mis razones, quiero, Sancho, que sepas que el famoso Amadís de Gaula fue uno de los más perfectos caballeros andantes. No he dicho bien "fue uno": fue el solo, el primero, el único, el señor de todos cuantos hubo en su tiempo en el mundo. ¡Mal año para don Belianís y para todos aquellos que digan que se le igualó en algo, porque se engañan, lo juro! Digo asimismo que, cuando un pintor quiere hacerse famoso en su arte, procura imitar los originales de los pintores más excepcionales que conoce. Y esta misma regla corre para todos los oficios o ejercicios importantes que sirven para el adorno de las repúblicas. Y así lo ha de hacer y lo hace el que quiere alcanzar nombre de prudente y sufrido: imitar a Ulises, en cuya persona y trabajos nos pinta Homero un retrato vivo de prudencia y sufrimiento. Como también nos mostró Virgilio, en la persona de Eneas, el valor de un hijo piadoso y la sagacidad de un valiente y entendido capitán, no pintándolos ni descubriéndolos como ellos fueron, sino como habían de ser, para quedar como ejemplo de sus virtudes a los hombres venideros. De la misma manera, Amadís fue el norte, la estrella de la mañana, el sol de los valientes y enamorados caballeros, a quien debemos imitar todos aquellos que servimos bajo la bandera del amor y de la caballería. Siendo esto así, como lo es, hallo yo, amigo Sancho, que el caballero andante que más lo imite estará más cerca de alcanzar la perfección de la caballería. Y una de las cosas en que más este caballero mostró su prudencia, valor, valentía, sufrimiento, firmeza y amor fue cuando se retiró, desdeñado por la señora Oriana, a hacer penitencia en la Peña Pobre, cambiando su nombre por el de Beltenebros, un nombre, por cierto, significativo y propio para la vida que él por su voluntad había escogido...

—En efecto —dijo Sancho—, ¿qué es lo que usted quiere hacer en este lugar tan remoto?

—¿No te he dicho ya —respondió don Quijote— que quiero imitar a Amadís, haciendo aquí del desesperado, del necio y del furioso? Quiero imitar juntamente al valiente don Roldán, cuando encontró en una fuente las señales de que Angélica la Bella había cometido una infamia con Medoro. De cuya pena se volvió loco y arrancó los árboles, enturbió las aguas de las claras fuentes, mató pastores, destruyó ganados, quemó cabañas, derribó casas, arrastró yeguas e hizo otras cien mil insolencias, dignas de eterno nombre y escritura. Y, aunque yo no pienso imitar a Roldán, o Orlando, o Rotolando (que todos estos tres nombres tenía), parte por parte en todas las locuras que hizo, dijo y pensó, haré el bosquejo, como mejor pueda, en las que me parezcan más esenciales. Y podría ser que viniera a contentarme con la sola imitación de Amadís, que sin hacer locuras dañinas, sino de lloros y sentimientos, alcanzó tanta fama como el que más.

—Me parece a mí —dijo Sancho— que los caballeros que hicieron tal cosa fueron provocados y tuvieron una causa para hacer esas necedades y penitencias. Pero usted, ¿qué causa tiene para volverse loco? ¿Qué dama lo ha desdeñado, o qué señales ha encontrado que le den a entender que la señora Dulcinea del Toboso ha hecho alguna niñería con moro o cristiano?

—Ahí está el punto —respondió don Quijote—, y esa es la fineza de mi negocio. Que un caballero andante se vuelva loco con causa, no tiene mérito ni gracia. El toque está en enloquecer sin motivo y dar a entender a mi dama que, si hago esto sin razón, ¿qué haría con una? Además, tengo una gran ocasión en la larga ausencia que he hecho de mi siempre señora Dulcinea del Toboso. Como ya oíste decir a aquel pastor de antes, Ambrosio: "quien está ausente, todos los males tiene y teme". Así que, amigo Sancho, no gastes tiempo en aconsejarme que deje una imitación tan rara, tan feliz y tan nunca vista. Loco soy, loco he de ser hasta que tú vuelvas con la respuesta de una carta que contigo pienso enviar a mi señora Dulcinea. Y si fuera tal como mi fe merece, se acabará mi necedad y mi penitencia. Y si fuera lo contrario, seré loco de verdad, y siéndolo, no sentiré nada. Así que, de cualquier manera que responda, saldré del conflicto y trabajo en que me dejes, gozando del bien que me trajeres, por cuerdo, o no sintiendo el mal que me trajeres, por loco. Pero dime, Sancho, ¿traes bien guardado el yelmo de Mambrino? Ya vi que lo levantaste del suelo cuando aquel desagradecido lo quiso hacer pedazos. Pero no pudo, de donde se puede ver la fineza de su temple.

A lo cual respondió Sancho:

—¡Vive Dios, señor Caballero de la Triste Figura, que no puedo sufrir ni llevar con paciencia algunas cosas que usted dice! Y por ellas vengo a imaginar que todo cuanto me dice de caballerías y de alcanzar reinos e imperios, de dar islas y de hacer otros favores y grandezas, como es uso de caballeros andantes, todo debe de ser cosa de viento y mentira, y todo patraña, o como lo llamemos. Porque quien oiga decir a usted que una bacía de barbero es el yelmo de Mambrino, y que no salga de este error en más de cuatro días, ¿qué ha de pensar, sino que quien tal dice y afirma debe de tener el juicio hueco? La bacía yo la llevo en el saco, toda abollada, y la llevo para repararla en mi casa y hacerme la barba en ella, si Dios me da la gracia de que algún día me vea con mi mujer y mis hijos.

—Mira, Sancho, por el mismo Dios que antes juraste, te juro —dijo don Quijote— que tienes el entendimiento más corto que tiene o tuvo escudero en el mundo. ¿Es posible que en todo el tiempo que andas conmigo no te has dado cuenta de que todas las cosas de los caballeros andantes parecen quimeras, necedades y disparates, y que están todas hechas al revés? Y no porque sea así, sino porque anda entre nosotros siempre una multitud de encantadores que todas nuestras cosas cambian y truecan y las vuelven según su gusto, y según tienen las ganas de favorecernos o destruirnos. Y así, eso que a ti te parece una bacía de barbero, a mí me parece el yelmo de Mambrino, y a otro le parecerá otra cosa. Y fue una rara providencia del sabio que está de mi parte hacer que parezca una bacía a todos lo que real y verdaderamente es un yelmo, a causa de que, siendo él de tanta estima, todo el mundo me perseguiría por quitármelo. Pero como ven que no es más que una bacinilla de barbero, no se preocupan de procurarlo, como se mostró bien en el que quiso romperlo y lo dejó en el suelo sin llevárselo. Que, en verdad, si lo hubiera conocido, nunca lo habría dejado. Guárdalo, amigo, que por ahora no lo necesito. Antes me tengo que quitar toda esta armadura y quedarme desnudo como cuando nací, si es que me da la voluntad de seguir en mi penitencia más a Roldán que a Amadís.

Llegaron, en estas conversaciones, al pie de una alta montaña que, casi como una roca cortada, estaba sola entre otras muchas que la rodeaban. Corría por su falda un suave arroyo, y se hacía por toda su redondez un prado tan verde y exuberante que daba gusto a los ojos que lo miraban. Había por allí muchos árboles silvestres y algunas plantas y flores, que hacían el lugar apacible. Este sitio escogió el Caballero de la Triste Figura para hacer su penitencia. Y así, al verlo, comenzó a decir en voz alta, como si estuviera sin juicio:

—Este es el lugar, ¡oh, cielos!, que designo y escojo para llorar la desventura en que vosotros mismos me habéis puesto. Este es el sitio donde las lágrimas de mis ojos acrecentarán las aguas de este pequeño arroyo, y mis continuos y profundos suspiros moverán constantemente las hojas de estos árboles montaraces, en testimonio y señal de la pena que mi atormentado corazón padece. ¡Oh, vosotros, quienquiera que seáis, dioses rústicos que en este lugar inhabitable tenéis vuestra morada, oíd las quejas de este desdichado amante, a quien una larga ausencia y unos imaginados celos han traído a lamentarse entre estas asperezas y a quejarse de la dura condición de aquella ingrata y bella, término y fin de toda humana hermosura! ¡Oh, vosotras, ninfas y dríadas, que tenéis por costumbre habitar en las espesuras de los montes, así los ligeros y lascivos sátiros, de quienes sois, aunque en vano, amadas, no perturben jamás vuestro dulce sosiego, y ayudadme a lamentar mi desventura, o, al menos, no os canséis de oírla! ¡Oh, Dulcinea del Toboso, día de mi noche, gloria de mi pena, norte de mis caminos, estrella de mi fortuna, así el cielo te la dé buena en cuanto aciertes a pedirle, que consideres el lugar y el estado a que tu ausencia me ha conducido, y que con buen término correspondas a lo que a mi fe se le debe! ¡Oh, solitarios árboles, que desde hoy en adelante habéis de hacer compañía a mi soledad, dad indicio, con el suave movimiento de vuestras ramas, que no os desagrada mi presencia! ¡Oh, tú, escudero mío, agradable compañero en mis más prósperos y adversos sucesos, guarda bien en la memoria lo que aquí me verás hacer, para que lo cuentes y relates a la causa total de todo ello!

Y, diciendo esto, se bajó de Rocinante y en un momento le quitó el freno y la silla. Y, dándole una palmada en las ancas, le dijo:

—Libertad te da el que sin ella queda, ¡oh, caballo tan extraordinario por tus obras como desdichado por tu suerte! Vete por donde quieras, que en la frente llevas escrito que no te igualó en ligereza el Hipogrifo de Astolfo, ni el nombrado Frontino, que tan caro le costó a Bradamante.

Viendo esto, Sancho dijo:

—¡Bien haya quien nos quitó ahora el trabajo de quitarle la albarda al burro! Que, en verdad, no faltarían palmaditas que darle, ni cosas que decirle en su alabanza. Pero si él estuviera aquí, no consentiría yo que nadie le quitara la albarda, pues no había por qué. A él no le tocaban las generales de estar enamorado ni desesperado, pues no lo estaba su amo, que era yo, cuando Dios quería. Y en verdad, señor Caballero de la Triste Figura, si es que mi partida y su locura van en serio, será bueno volver a ensillar a Rocinante para que supla la falta del burro, porque se ahorrará tiempo en mi ida y vuelta. Que si la hago a pie, no sé cuándo llegaré ni cuándo volveré, porque, en resumen, soy mal caminante.

—Digo, Sancho —respondió don Quijote—, que sea como tú quieras, que no me parece mal tu designio. Y digo que de aquí a tres días te partirás, porque quiero que en este tiempo veas lo que por ella hago y digo, para que se lo digas.

—Pues, ¿qué más tengo que ver —dijo Sancho— que lo que he visto?

—¡Estás muy equivocado! —respondió don Quijote—. Ahora me falta rasgar mis vestiduras, esparcir las armas y darme de golpes en la cabeza contra estas rocas, con otras cosas de este tipo que te han de admirar.

—Por amor de Dios —dijo Sancho—, mire usted cómo se da esos golpes. Que podría llegar a una roca tal, y en tal punto, que con el primero se acabara la máquina de esta penitencia. Y yo sería de la opinión de que, ya que a usted le parece que aquí son necesarios los golpes y que no se puede hacer esta obra sin ellos, se contentara, pues todo esto es fingido y cosa de burla, se contentara, digo, con dárselos en el agua, o en alguna cosa blanda como el algodón. Y déjeme a mí el cargo, que yo le diré a mi señora que usted se los daba en una punta de roca más dura que la de un diamante.

—Yo agradezco tu buena intención, amigo Sancho —respondió don Quijote—, mas quiero hacerte saber que todas estas cosas que hago no son de broma, sino muy en serio. Porque de otra manera, sería contravenir a las órdenes de la caballería, que nos mandan que no digamos mentira alguna, bajo pena de ser castigados como renegados, y hacer una cosa por otra es lo mismo que mentir. Así que mis golpes en la cabeza han de ser verdaderos, firmes y valederos, sin que lleven nada de engañoso ni de imaginario. Y será necesario que me dejes algunas vendas para curarme, ya que la suerte quiso que nos faltara el bálsamo que perdimos.

—Más fue perder el burro —respondió Sancho—, pues en él se perdieron las vendas y todo. Y le ruego a usted que no se acuerde más de aquella maldita poción. Solo de oírla mencionar se me revuelve el alma, por no decir el estómago. Y más le ruego: que haga cuenta de que ya han pasado los tres días que me ha dado de plazo para ver las locuras que hace. Que ya las doy por vistas y por cosa juzgada, y diré maravillas a mi señora. Escriba la carta y despácheme enseguida, porque tengo un gran deseo de volver para sacar a usted de este purgatorio donde lo dejo.

—¿Purgatorio lo llamas, Sancho? —dijo don Quijote—. Mejor harías en llamarlo infierno, y aun peor, si hay otra cosa que lo sea.

—Quien está en el infierno —respondió Sancho—, no tiene redención, según he oído decir.

—No entiendo qué quiere decir "redención" —dijo don Quijote.

—Redención es —respondió Sancho— que quien está en el infierno nunca sale de él, ni puede. Lo cual será al revés en usted, o a mí me andarán mal los pies, si es que llevo espuelas para avivar a Rocinante. Y póngame yo de una vez en el Toboso, y delante de mi señora Dulcinea, que yo le diré tales cosas de las necedades y locuras —que todo es uno— que usted ha hecho y queda haciendo, que la venga a poner más blanda que un guante, aunque la encuentre más dura que un alcornoque. Con cuya respuesta dulce y melosa volveré por los aires, como un brujo, y sacaré a usted de este purgatorio, que parece infierno y no lo es, pues hay esperanza de salir de él. La cual, como tengo dicho, no la tienen los que están en el infierno, ni creo que usted dirá otra cosa.

—Así es la verdad —dijo el de la Triste Figura—. Pero, ¿qué haremos para escribir la carta?

—Y la orden de pago por los burros también —añadió Sancho.

—Todo irá incluido —dijo don Quijote—. Y sería bueno, ya que no hay papel, que la escribiéramos, como hacían los antiguos, en hojas de árboles o en unas tablillas de cera. Aunque tan difícil será encontrar eso ahora como el papel. Mas ya me ha venido a la memoria dónde será bueno, y aun más que bueno, escribirla: en la libreta de notas que fue de Cardenio. Y tú tendrás cuidado de hacerla copiar en papel, con buena letra, en el primer lugar que encuentres donde haya un maestro de escuela, o si no, cualquier sacristán te la copiará. Y no se la des a copiar a ningún escribano, que hacen una letra procesal que no la entenderá ni Satanás.

—Pues, ¿qué se ha de hacer con la firma? —dijo Sancho.

—Las cartas de Amadís nunca se firman —respondió don Quijote.

—Está bien —respondió Sancho—, pero la orden de pago forzosamente se ha de firmar. Y esa, si se copia, dirán que la firma es falsa y me quedaré sin burros.

—La orden de pago irá firmada en la misma libreta. Al verla, mi sobrina no pondrá dificultad en cumplirla. Y en lo que toca a la carta de amor, pondrás por firma: "Vuestro hasta la muerte, el Caballero de la Triste Figura". Y no importará mucho que vaya de mano ajena, porque, por lo que yo recuerdo, Dulcinea no sabe escribir ni leer, y en toda su vida ha visto mi letra ni una carta mía. Porque mis amores y los suyos han sido siempre platónicos, sin extenderse a más que a una mirada honesta. Y aun esto tan de vez en cuando, que me atreveré a jurar con verdad que en los doce años que hace que la quiero más que a la luz de estos ojos que ha de comer la tierra, no la he visto cuatro veces. Y aun podría ser que de estas cuatro veces, ella no se hubiera dado cuenta de que la miraba. Tal es el recato y el encierro con que sus padres, Lorenzo Corchuelo y su madre, Aldonza Nogales, la han criado.

—¡Vaya, vaya! —dijo Sancho—. ¿Que la hija de Lorenzo Corchuelo es la señora Dulcinea del Toboso, llamada por otro nombre Aldonza Lorenzo?

—Esa es —dijo don Quijote—. Y es la que merece ser señora de todo el universo.

—Bien la conozco —dijo Sancho—, y sé decir que tira una barra tan bien como el zagal más forzudo de todo el pueblo. ¡Vive el Dador, que es una moza de rompe y rasga, hecha y derecha y de pelo en pecho! Puede sacar del lodo a cualquier caballero andante, o por andar, que la tenga por señora. ¡Oh, qué fuerza tiene y qué voz! Sé decir que se puso un día encima del campanario de la aldea a llamar a unos zagales suyos que andaban en un barbecho de su padre. Y aunque estaban de allí a más de media legua, la oyeron como si estuvieran al pie de la torre. Y lo mejor que tiene es que no es nada remilgada, porque tiene mucho de cortesana: con todos se burla y de todo hace mueca y gracia. Ahora digo, señor Caballero de la Triste Figura, que no solamente puede y debe usted hacer locuras por ella, sino que, con justo título, puede desesperarse y ahorcarse. Y nadie que lo sepa dirá que no hizo muy bien, aunque lo lleve el diablo. Y querría ya verme en camino, solo por verla. Que hace muchos días que no la veo, y debe de estar ya cambiada, porque andar siempre en el campo, al sol y al aire, gasta mucho la cara de las mujeres. Y le confieso a usted una verdad, señor don Quijote: que hasta aquí he estado en una gran ignorancia. Pensaba bien y fielmente que la señora Dulcinea debía de ser alguna princesa de quien usted estaba enamorado, o alguna persona tal que mereciera los ricos presentes que usted le ha enviado: así el del vizcaíno como el de los galeotes, y otros muchos que deben ser, según las muchas victorias que usted ha ganado y ganó en el tiempo en que yo aún no era su escudero. Pero, bien considerado, ¿qué se le ha de dar a la señora Aldonza Lorenzo, digo, a la señora Dulcinea del Toboso, de que se le vayan a arrodillar delante de ella los vencidos que usted le envía y ha de enviar? Porque podría ser que, al tiempo que ellos llegaran, estuviera ella rastrillando lino...

—Ya te he dicho antes de ahora muchas veces, Sancho —dijo don Quijote—, que eres un gran hablador, y que, aunque de ingenio tosco, muchas veces despuntas con agudeza. Mas, para que veas cuán necio eres tú y cuán discreto soy yo, quiero que me oigas un breve cuento. «Has de saber que una viuda hermosa, joven, libre y rica, y, sobre todo, desenvuelta, se enamoró de un joven sirviente, robusto y de buen porte. Su superior lo supo, y un día le dijo a la buena viuda, a modo de reprimenda fraternal: ''Estoy maravillado, señora, y no sin mucha causa, de que una mujer tan principal, tan hermosa y tan rica como usted, se haya enamorado de un hombre tan vulgar, tan bajo y tan ignorante como fulano, habiendo en esta casa tantos maestros, tantos presentados y tantos teólogos, entre quienes usted podría escoger como entre peras y decir: 'Éste quiero, aquel no quiero'''. Mas ella le respondió, con mucha gracia y desenvoltura: ''Usted, señor mío, está muy engañado, y piensa muy a la antigua si cree que he escogido mal en fulano, por ignorante que le parezca. Pues, para lo que yo lo quiero, sabe tanta filosofía, y más, que Aristóteles''». Así que, Sancho, para lo que yo quiero a Dulcinea del Toboso, tanto vale como la más alta princesa de la tierra. Sí, que no todos los poetas que alaban damas, bajo un nombre que ellos a su antojo les ponen, es verdad que las tienen. ¿Piensas tú que las Amarilis, las Filis, las Silvias, las Dianas, las Galateas, las Fílidas y otras tales de que los libros, los romances, las tiendas de los barberos, los teatros de las comedias están llenos, fueron verdaderamente damas de carne y hueso, y de aquellos que las celebran y celebraron? No, por cierto, sino que la mayoría se las inventan, para dar tema a sus versos y para que los tengan por enamorados y por hombres que tienen valor para serlo. Y así, me basta a mí pensar y creer que la buena de Aldonza Lorenzo es hermosa y honesta. Y lo del linaje importa poco, que no han de ir a investigar para darle ningún hábito, y yo me hago la cuenta de que es la más alta princesa del mundo. Porque has de saber, Sancho, si no lo sabes, que dos cosas solas incitan a amar más que otras, que son la mucha hermosura y la buena fama, y estas dos cosas se hallan consumadamente en Dulcinea. Porque en hermosura, ninguna la iguala, y en buena fama, pocas la alcanzan. Y para concluir con todo, yo imagino que todo lo que digo es así, sin que sobre ni falte nada. Y la pinto en mi imaginación como la deseo, así en la belleza como en la principalidad, y ni la alta Elena, ni la romana Lucrecia, ni otra alguna de las mujeres famosas de las edades pasadas, griegas, bárbaras o latinas, le llegan ni con mucho. Y que diga el que quiera lo que quiera; que si por esto soy reprendido por los ignorantes, no seré castigado por los más rigurosos.

—Digo que en todo tiene usted razón —respondió Sancho—, y que yo soy un asno. Mas no sé yo para qué nombro "asno" en mi boca, pues no se ha de mentar la soga en casa del ahorcado. Pero venga la carta, y adiós, que me voy.

Don Quijote sacó la libreta de notas y, apartándose a un lado, con mucha calma comenzó a escribir la carta. Al acabarla, llamó a Sancho y le dijo que se la quería leer para que la tomara de memoria, por si acaso se le perdía por el camino, porque de su desdicha todo se podía temer. A lo cual respondió Sancho:

—Escríbala usted dos o tres veces ahí en el libro y démelo, que yo lo llevaré bien guardado. Porque pensar que yo la he de aprender de memoria es un disparate, que la tengo tan mala que muchas veces se me olvida cómo me llamo. Pero, con todo eso, dígamela usted, que me alegraré mucho de oírla, que debe de ir como hecha a medida.

—Escucha, que así dice —dijo don Quijote:

Carta de don Quijote a Dulcinea del Toboso

Soberana y alta señora:

El herido por la punta de la ausencia y el llagado por las telas del corazón, dulcísima Dulcinea del Toboso, te envía la salud que él no tiene. Si tu hermosura me desprecia, si tu valor no es en mi favor, si tus desdenes son mi tormento, aunque yo sea muy sufrido, mal podré sostenerme en esta pena, que además de ser fuerte, es muy duradera. Mi buen escudero Sancho te dará entera relación, ¡oh, bella ingrata, amada enemiga mía!, del modo en que por tu causa quedo. Si gustas de socorrerme, tuyo soy; y si no, haz lo que te plazca; que, con acabar mi vida, habré satisfecho a tu crueldad y a mi deseo.

Tuyo hasta la muerte,

El Caballero de la Triste Figura.

—¡Por vida de mi padre —dijo Sancho al oír la carta—, que es la cosa más alta que jamás he oído! ¡Maldita sea, y cómo le dice usted ahí todo cuanto quiere, y qué bien que encaja en la firma "El Caballero de la Triste Figura"! Digo de verdad que es usted el mismo diablo, y que no hay cosa que no sepa.

—Todo es necesario —respondió don Quijote— para el oficio que tengo.

—Ea, pues —dijo Sancho—, ponga usted en la otra vuelta la orden de pago de los tres burros y fírmela con mucha claridad, para que la reconozcan al verla.

—Me parece bien —dijo don Quijote.

Y habiéndola escrito, se la leyó, y decía así:

"Por esta primera de burros, mandará usted, señora sobrina, dar a Sancho Panza, mi escudero, tres de los cinco que dejé en casa y están a su cargo. Los cuales tres burros se los mando entregar y pagar por otros tantos aquí recibidos de contado, de lo que consta, y con su carta de pago serán bien dados. Fecha en las entrañas de Sierra Morena, a veintidós de agosto de este presente año."

—Está bien —dijo Sancho—; fírmela usted.

—No es necesario firmarla —dijo don Quijote—, sino solamente poner mi rúbrica, que es lo mismo que una firma, y para tres burros, y aun para trescientos, sería suficiente.

—Yo confío en usted —respondió Sancho—. Déjeme, iré a ensillar a Rocinante, y prepárese usted a echarme su bendición, que enseguida pienso partirme, sin ver las tonterías que usted ha de hacer. Diré que lo vi hacer tantas que no querrá más.

—Por lo menos quiero, Sancho, y porque es necesario, quiero, digo, que me veas desnudo y hacer una o dos docenas de locuras, que las haré en menos de media hora. Porque, habiéndolas tú visto con tus propios ojos, podrás jurar sin problemas sobre las demás que quieras añadir. Y te aseguro que no dirás tantas como yo pienso hacer.

—Por amor de Dios, señor mío, que no lo vea yo a usted desnudo, que me dará mucha lástima y no podré dejar de llorar. Y tengo tal la cabeza, del llanto que anoche hice por el burro, que no estoy para meterme en nuevos lloros. Y si es que usted gusta de que yo vea algunas locuras, hágalas vestido, breves y las que le vengan más a cuento. Además, para mí no era necesario nada de eso, y, como ya he dicho, sería ahorrar el camino de mi vuelta, que ha de ser con las nuevas que usted desea y merece. Y si no, que se prepare la señora Dulcinea. Que si no responde como es debido, juro solemnemente a quien puedo que le tengo de sacar la buena respuesta del estómago a patadas y a bofetones. Porque, ¿dónde se ha de sufrir que un caballero andante, tan famoso como usted, se vuelva loco, sin qué ni para qué, por una...? No me haga decir el resto, señora, porque por Dios que despotrico y lo echo todo a perder, aunque nunca se venda. ¡Bonito soy yo para eso! ¡Mal me conoce! ¡Pues, a fe que si me conociera, se arrepentiría!

—En verdad, Sancho —dijo don Quijote—, que, por lo que parece, no estás tú más cuerdo que yo.

—No estoy tan loco —respondió Sancho—, mas estoy más colérico. Pero, dejando esto aparte, ¿qué va a comer usted mientras yo vuelvo? ¿Va a salir al camino, como Cardenio, a quitárselo a los pastores?

—No te preocupe ese cuidado —respondió don Quijote—. Porque, aunque tuviera, no comería otra cosa que las hierbas y frutos que este prado y estos árboles me den. Que la fineza de mi negocio está en no comer y en hacer otras penitencias equivalentes.

—Adiós, pues. Pero, ¿sabe usted qué temo? Que no voy a acertar a volver a este lugar donde ahora lo dejo, de tan escondido que está.

—Toma bien las señas, que yo procuraré no apartarme de estos contornos —dijo don Quijote—. Y aun tendré cuidado de subirme a estas rocas más altas, para ver si te descubro cuando vuelvas. Además, lo más acertado será, para que no te equivoques y te pierdas, que cortes algunas retamas de las muchas que por aquí hay y las vayas poniendo de trecho en trecho, hasta salir a lo raso. Estas te servirán de hitos y señales para que me encuentres cuando vuelvas, a imitación del hilo del laberinto de Teseo.

—Así lo haré —respondió Sancho Panza.

Y cortando algunos, pidió la bendición a su señor y, no sin muchas lágrimas de ambos, se despidió de él. Y, subiendo sobre Rocinante, a quien don Quijote encomendó mucho, y que cuidara de él como de su propia persona, se puso en camino hacia el llano, esparciendo de trecho a trecho los ramos de la retama, como su amo se lo había aconsejado. Y así se fue, aunque todavía don Quijote le insistía en que lo viera hacer al menos dos locuras. Mas no hubo andado cien pasos, cuando volvió y dijo:

—Digo, señor, que usted ha dicho muy bien: para que pueda jurar sin cargo de conciencia que lo he visto hacer locuras, será bueno que vea siquiera una. Aunque bien grande la he visto en su decisión de quedarse.

—¿No te lo decía yo? —dijo don Quijote—. Espérate, Sancho, que en un instante las haré.

Y quitándose con toda prisa los calzones, quedó en carnes y en pañales. Y luego, sin más ni más, dio dos saltos en el aire y dos volteretas, la cabeza abajo y los pies en alto, descubriendo cosas que, por no verlas otra vez, Sancho volvió la rienda a Rocinante y se dio por contento y satisfecho de que podía jurar que su amo quedaba loco. Y así, lo dejaremos ir su camino, hasta la vuelta, que fue breve.`,
}
