import axios from 'axios'
import type { YoutubeCaptionInfo, YoutubeSubtitleResult } from '../youtube.types'
// youtube-dl-exec has ESM/CJS interop issues with webpack — use require to bypass
const youtubedl: typeof import('youtube-dl-exec').default = require('youtube-dl-exec')

/**
 * Приоритетный список вариантов языка для поиска субтитров.
 *
 * YouTube часто использует региональные коды (en-US, pt-BR и т.д.),
 * поэтому для каждого языка задаём цепочку фолбеков.
 */
const SUBTITLE_LANGUAGES_BY_PRIORITY: Record<string, string[]> = {
	en: ['en', 'en-US', 'en-GB', 'en-CA'],
	fr: ['fr', 'fr-FR', 'fr-CA'],
	de: ['de', 'de-DE', 'de-AT', 'de-CH'],
	es: ['es', 'es-ES', 'es-MX', 'es-419'],
	it: ['it', 'it-IT'],
	tr: ['tr', 'tr-TR'],
	ru: ['ru', 'ru-RU'],
}

/**
 * Получить сырые VTT-субтитры YouTube-видео на указанном языке.
 *
 * Использует `yt-dlp --dump-json` для получения метаданных видео
 * (включая список доступных субтитров и их URL). Затем скачивает
 * VTT-субтитры по прямой ссылке.
 *
 * Конвертация VTT → SRT (включая деление на предложения) выполняется
 * отдельно через LLM на уровне стратегии обработки видео.
 *
 * Приоритет: ручные субтитры → автосгенерированные → null.
 *
 * @param videoId — идентификатор видео на YouTube (например, "dQw4w9WgXcQ")
 * @param language — код языка (например, "en", "ru", "de")
 * @returns сырые VTT-субтитры или null, если субтитры не найдены
 */
export async function getSubtitles(videoId: string, language: string): Promise<YoutubeSubtitleResult | null> {
	const url = `https://www.youtube.com/watch?v=${videoId}`

	const payload = await youtubedl(url, {
		dumpJson: true,
		skipDownload: true,
		noWarnings: true,
		noPart: true,
		noPlaylist: true,
	})

	const typedPayload = payload as Record<string, unknown>

	const subtitles = (typedPayload.subtitles ?? {}) as Record<string, YoutubeCaptionInfo[]>
	const autoCaptions = (typedPayload.automatic_captions ?? {}) as Record<string, YoutubeCaptionInfo[]>

	// Приоритет: ручные субтитры
	const vttUrl = findSubtitleVttUrl(subtitles, language)
	if (vttUrl) {
		const content = await fetchVttContent(vttUrl)
		return { language, isAutoGenerated: false, content }
	}

	// Фолбек: автосгенерированные
	const autoVttUrl = findSubtitleVttUrl(autoCaptions, language)
	if (autoVttUrl) {
		const content = await fetchVttContent(autoVttUrl)
		return { language, isAutoGenerated: true, content }
	}

	return null
}

// ─── Поиск VTT-ссылки ────────────────────────────────────────────────────────

/**
 * Найти URL VTT-субтитров для указанного языка.
 *
 * Сначала ищет точное совпадение языка, затем — по приоритетному списку
 * вариантов (например, для "en" пробует "en", "en-US", "en-GB", "en-CA").
 */
function findSubtitleVttUrl(captions: Record<string, YoutubeCaptionInfo[]>, language: string): string | null {
	const candidateLangs = SUBTITLE_LANGUAGES_BY_PRIORITY[language] ?? [language]

	for (const lang of candidateLangs) {
		const entries = captions[lang]
		if (!entries || entries.length === 0) continue

		const vtt = entries.find((e) => e.ext === 'vtt')
		if (vtt) return vtt.url
	}

	return null
}

// ─── Скачивание VTT ──────────────────────────────────────────────────────────

/**
 * Скачать сырые VTT-субтитры по URL.
 */
async function fetchVttContent(vttUrl: string): Promise<string> {
	const response = await axios.get<string>(vttUrl)
	return response.data
}
