export const chapter_15 = {
	name: '7, lunedì',
	header: 'Il carbonaio e il signore',
	text: `Non l'avrebbe mai detta Garrone, sicuramente, quella parola che disse ieri mattina Carlo Nobis aBetti. Carlo Nobis è superbo perché suo padre è un gran signore: un signore alto, con tutta la barbanera, molto serio, che viene quasi ogni giorno ad accompagnare il figliuolo.
	Ieri mattina Nobis sibisticciò con Betti, uno dei più piccoli, figliuolo d'un carbonaio, e non sapendo più che rispondergli,perché aveva torto, gli disse forte: - Tuo padre è uno straccione. - Betti arrossì fino ai capelli, e nondisse nulla, ma gli vennero le lacrime agli occhi, e tornato a casa ripeté la parola a suo padre; edecco il carbonaio, un piccolo uomo tutto nero, che compare alla lezione del dopopranzo col ragazzoper mano, a fare le lagnanze al maestro.
	Mentre faceva le sue lagnanze al maestro, e tutti tacevano,il padre di Nobis, che levava il mantello al figliuolo, come al solito, sulla soglia dell'uscio, udendopronunciare il suo nome, entrò, e domandò spiegazione.- È quest'operaio, - rispose il maestro, - che è venuto a lagnarsi perché il suo figliuolo Carlo disse alsuo ragazzo: Tuo padre è uno straccione.Il padre di Nobis corrugò la fronte e arrossì leggermente. Poi domandò al figliuolo: - Hai dettoquella parola?
Il figliuolo, - ritto in mezzo alla scuola, col capo basso, davanti al piccolo Betti, - non rispose.Allora il padre lo prese per un braccio e lo spinse più avanti in faccia a Betti, che quasi si toccavano,e gli disse: - Domandagli scusa.Il carbonaio volle interporsi, dicendo: - No, no. - Ma il signore non gli badò, e ripeté al figliuolo: -Domandagli scusa.
Ripeti le mie parole. Io ti domando scusa della parola ingiuriosa, insensata,ignobile che dissi contro tuo padre, al quale il mio... si tiene onorato di stringere la mano.Il carbonaio fece un gesto risoluto, come a dire: Non voglio. Il signore non gli diè retta, e il suofigliuolo disse lentamente, con un fil di voce, senza alzar gli occhi da terra: - Io ti domando scusa...della parola ingiuriosa... insensata... ignobile, che dissi contro tuo padre, al quale il mio... si tieneonorato di stringer la mano.Allora il signore porse la mano al carbonaio, il quale gliela strinse con forza, e poi subito con unaspinta gettò il suo ragazzo fra le braccia di Carlo Nobis.- Mi faccia il favore di metterli vicini, - disse il signore al maestro. - Il maestro mise Betti nel bancodi Nobis. Quando furono al posto, il padre di Nobis fece un saluto ed uscì.Il carbonaio rimase qualche momento sopra pensiero, guardando i due ragazzi vicini; poi s'avvicinòal banco, e fissò Nobis, con espressione d'affetto e di rammarico, come se volesse dirgli qualcosa;ma non disse nulla; allungò la mano per fargli una carezza, ma neppure osò, e gli strisciò soltanto lafronte con le sue grosse dita.
Poi s'avviò all'uscio, e voltatosi ancora una volta a guardarlo, sparì. -Ricordatevi bene di quel che avete visto, ragazzi, - disse il maestro, - questa è la più bella lezionedell'anno.`,
}
