export const chapter_28 = {
	name: '11, domenica',
	header: 'Il muratorino',
	text: `Il «muratorino» è venuto oggi, in cacciatora, tutto vestito di roba smessa di suo padre, ancora biancadi calcina e di gesso. Mio padre lo desiderava anche più di me che venisse.
	Come ci fece piacere!Appena entrato, si levò il cappello a cencio ch'era tutto bagnato di neve e se lo ficcò in un taschino;poi venne innanzi, con quella sua andatura trascurata d'operaio stanco, rivolgendo qua e là il visettotondo come una mela, col suo naso a pallottola; e quando fu nella sala da desinare, data un'occhiatain giro ai mobili, e fissati gli occhi sur un quadretto che rappresenta Rigoletto, un buffone gobbo,fece il «muso di lepre».
	È impossibile trattenersi dal ridere a vedergli fare il muso di lepre. Cimettemmo a giocare coi legnetti: egli ha un'abilità straordinaria a far torri e ponti, che par che stiansu per miracolo, e ci lavora tutto serio, con la pazienza di un uomo.
	Fra una torre e l'altra, mi dissedella sua famiglia: stanno in una soffitta, suo padre va alle scuole serali a imparar a leggere, suamadre è biellese. E gli debbono voler bene, si capisce, perché è vestito così da povero figliuolo, maben riparato dal freddo, coi panni ben rammendati, con la cravatta annodata bene dalla mano di suamadre.
	Suo padre, mi disse, è un pezzo d'uomo, un gigante, che stenta a passar per le porte; mabuono, e chiama sempre il figliuolo «muso di lepre»; il figliuolo, invece, è piccolino. Alle quattro sifece merenda insieme con pane e zebibbo, seduti sul sofà, e quando ci alzammo, non so perché, miopadre non volle che ripulissi la spalliera che il muratorino aveva macchiata di bianco con la suagiacchetta: mi trattenne la mano e ripulì poi lui, di nascosto. Giocando, il muratorino perdette unbottone della cacciatora, e mia madre glie l'attaccò, ed egli si fece rosso e stette a vederla cuciretutto meravigliato e confuso, trattenendo il respiro.
	Poi gli diedi a vedere degli album di caricatureed egli, senz'avvedersene, imitava le smorfie di quelle facce, così bene, che anche mio padre rideva.Era tanto contento quando andò via, che dimenticò di rimettersi in capo il berretto a cencio, earrivato sul pianerottolo, per mostrarmi la sua gratitudine mi fece ancora una volta il muso di lepre.Egli si chiama Antonio Rabucco, e ha otto anni e otto mesi...
- Lo sai, figliuolo, perché non volli che ripulissi il sofà? Perché ripulirlo, mentre il tuo compagnovedeva, era quasi un fargli rimprovero d'averlo insudiciato.
E questo non stava bene, prima perchénon l'aveva fatto apposta, e poi perché l'aveva fatto coi panni di suo padre, il quale se li è ingessatilavorando; e quello che si fa lavorando non è sudiciume: è polvere, è calce, è vernice, è tutto quelloche vuoi, ma non sudiciume.
Il lavoro non insudicia. Non dir mai d'un operaio che vien dal lavoro: -È sporco. - Devi dire: - Ha sui panni i segni, le tracce del suo lavoro. Ricordatene. E vogli bene almuratorino, prima perché è tuo compagno, poi perché è figliuolo d'un operaio.
TUO PADRE`,
}
