export const chapter_22 = {
	name: '25, venerdì',
	header: 'Il primo della classe',
	text: `Garrone s'attira l'affetto di tutti; Derossi, l'ammirazione.
	Ha preso la prima medaglia, sarà sempre ilprimo anche quest'anno, nessuno può competer con lui, tutti riconoscono la sua superiorità in tuttele materie.
	È il primo in aritmetica, in grammatica, in composizione, in disegno, capisce ogni cosaal volo, ha una memoria meravigliosa, riesce in tutto senza sforzo, pare che lo studio sia un giocoper lui... Il maestro gli disse ieri: - Hai avuto dei grandi doni da Dio, non hai altro da fare che nonsciuparli. - E per di più è grande, bello, con una gran corona di riccioli biondi, lesto che salta unbanco appoggiandovi una mano su; e sa già tirare di scherma.
	Ha dodici anni, è figliuolo d'unnegoziante, va sempre vestito di turchino con dei bottoni dorati, sempre vivo, allegro, grazioso contutti, e aiuta quanti può all'esame, e nessuno ha mai osato fargli uno sgarbo o dirgli una bruttaparola. Nobis e Franti soltanto lo guardano per traverso e Votini schizza invidia dagli occhi; ma eglinon se n'accorge neppure. Tutti gli sorridono e lo pigliano per una mano o per un braccio quando vaattorno a raccogliere i lavori, con quella sua maniera graziosa. Egli regala dei giornali illustrati, deidisegni, tutto quello che a casa regalano a lui, ha fatto per il calabrese una piccola carta geograficadelle Calabrie; e dà tutto ridendo, senza badarci, come un gran signore, senza predilezioni peralcuno.
	È impossibile non invidiarlo, non sentirsi da meno di lui in ogni cosa. Ah! io pure, comeVotini, l'invidio. E provo un'amarezza, quasi un certo dispetto contro di lui, qualche volta, quandostento a fare il lavoro a casa, e penso che a quell'ora egli l'ha già fatto, benissimo e senza fatica. Mapoi, quando torno alla scuola, a vederlo così bello, ridente, trionfante, a sentir come risponde alleinterrogazioni del maestro franco e sicuro, e com'è cortese e come tutti gli voglion bene, allora ogniamarezza, ogni dispetto mi va via dal cuore, e mi vergogno d'aver provato quei sentimenti. Vorreiessergli sempre vicino allora; vorrei poter fare tutte le scuole con lui; la sua presenza, la sua voce mimette coraggio, voglia di lavorare, allegrezza, piacere. Il maestro gli ha dato da copiare il raccontomensile che leggerà domani: La piccola vedetta lombarda; egli lo copiava questa mattina, ed eracommosso da quel fatto eroico, tutto acceso nel viso, cogli occhi umidi e con la bocca tremante; e iolo guardavo, com'era bello e nobile!
	Con che piacere gli avrei detto sul viso, francamente: - Derossi,tu vali in tutto più di me! Tu sei un uomo a confronto mio! Io ti rispetto e ti ammiro!`,
}
