export const chapter_12 = {
	name: '1, martedì',
	header: 'Lo spazzacamino',
	text: `Ieri sera andai alla Sezione femminile, accanto alla nostra, per dare il racconto del ragazzo
padovano alla maestra di Silvia, che lo voleva leggere. Settecento ragazze ci sono!
Quando arrivaicominciavano a uscire, tutte allegre per le vacanze d'Ognissanti e dei morti; ed ecco una bella cosache vidi.
Di fronte alla porta della scuola, dall'altra parte della via, stava con un braccio appoggiatoal muro e colla fronte contro il braccio, uno spazzacamino, molto piccolo, tutto nero in viso, col suosacco e il suo raschiatoio, e piangeva dirottamente, singhiozzando. Due o tre ragazze della secondagli s'avvicinarono e gli dissero: - Che hai che piangi a quella maniera? - Ma egli non rispose, econtinuava a piangere. - Ma di' che cos'hai, perché piangi? - gli ripeterono le ragazze.
E allora eglilevò il viso dal braccio, - un viso di bambino, - e disse piangendo che era stato in varie case aspazzare, dove s'era guadagnato trenta soldi, e li aveva persi, gli erano scappati per la sdruciturad'una tasca, - e faceva veder la sdrucitura, - e non osava più tornare a casa senza i soldi. - Il padronemi bastona, - disse singhiozzando, e riabbandonò il capo sul braccio, come un disperato.
Lebambine stettero a guardarlo, tutte serie. Intanto s'erano avvicinate altre ragazze grandi e piccole,povere e signorine, con le loro cartelle sotto il braccio, e una grande, che aveva una penna azzurrasul cappello, cavò di tasca due soldi, e disse: - Io non ho che due soldi: facciamo la colletta. -Anch'io ho due soldi, - disse un'altra vestita di rosso; - ne troveremo ben trenta fra tutte. - E alloracominciarono a chiamarsi: - Amalia! - Luigia! - Annina! - Un soldo. - Chi ha dei soldi? - Qua isoldi! - Parecchie avevan dei soldi per comprarsi fiori o quaderni, e li portarono, alcune più piccolediedero dei centesimi; quella della penna azzurra raccoglieva tutto, e contava a voce alta: - Otto,dieci, quindici! - Ma ci voleva altro. Allora comparve una più grande di tutte, che pareva quasi unamaestrina, e diede mezza lira, e tutte a farle festa. Mancavano ancora cinque soldi. - Ora vengonoquelle della quarta che ne hanno, - disse una. Quelle della quarta vennero e i soldi fioccarono. Tuttes'affollavano. Ed era bello a vedere quel povero spazzacamino in mezzo a tutte quelle vestine ditanti colori, a tutto quel rigirìo di penne, di nastrini, di riccioli.
I trenta soldi c'erano già, e nevenivano ancora, e le più piccine che non avevan denaro, si facevan largo tra le grandi porgendo iloro mazzetti di fiori, tanto per dar qualche cosa. Tutt'a un tratto arrivò la portinaia gridando: - Lasignora Direttrice! - Le ragazze scapparono da tutte le parti come uno stormo di passeri. E allora sivide il piccolo spazzacamino, solo in mezzo alla via, che s'asciugava gli occhi, tutto contento, con lemani piene di denari, e aveva nell'abbottonatura della giacchetta, nelle tasche, nel cappello tantimazzetti di fiori, e c'erano anche dei fiori per terra, ai suoi piedi.`,
}
