export const chapter_19 = {
	name: '18, venerdì',
	header: 'Il Direttore',
	text: `Coretti era contento questa mattina perché è venuto ad assistere al lavoro d'esame mensile il suomaestro di seconda, Coatti, un omone con una grande capigliatura crespa, una gran barba nera, duegrandi occhi scuri, e una voce da bombarda; il quale minaccia sempre i ragazzi di farli a pezzi e diportarli per il collo in Questura, e fa ogni specie di facce spaventevoli; ma non castiga mai nessuno,anzi sorride sempre dentro la barba, senza farsi scorgere.
	Otto sono, con Coatti, i maestri, compresoun supplente piccolo e senza barba, che pare un giovinetto. C'è un maestro di quarta, zoppo,imbacuccato in una grande cravatta di lana, sempre tutto pieno di dolori, e si prese quei doloriquando era maestro rurale, in una scuola umida dove i muri gocciolavano. Un altro maestro diquarta è vecchio e tutto bianco ed è stato maestro dei ciechi. Ce n'è uno ben vestito, con gli occhiali,e due baffetti biondi, che chiamavano l'avvocatino, perché facendo il maestro studiò da avvocato eprese la laurea, e fece anche un libro per insegnare a scriver le lettere.
	Invece quello che c'insegna laginnastica è un tipo di soldato, è stato con Garibaldi, e ha sul collo la cicatrice d'una ferita disciabola toccata alla battaglia di Milazzo. Poi c'è il Direttore, alto, calvo con gli occhiali d'oro, conla barba grigia che gli vien sul petto, tutto vestito di nero e sempre abbottonato fin sotto il mento;così buono coi ragazzi, che quando entrano tutti tremanti in Direzione, chiamati per un rimprovero,non li sgrida, ma li piglia per le mani, e dice tante ragioni, che non dovevan far così, e che bisognache si pentano, e che promettano d'esser buoni, e parla con tanta buona maniera e con una voce cosìdolce che tutti escono con gli occhi rossi, più confusi che se li avesse puniti.
	Povero Direttore, egli èsempre il primo al suo posto, la mattina, a aspettare gli scolari e a dar retta ai parenti, e quando imaestri son già avviati verso casa, gira ancora intorno alla scuola a vedere che i ragazzi non sicaccino sotto le carrozze, o non si trattengan per le strade a far querciola, o a empir gli zaini disabbia o di sassi; e ogni volta che appare a una cantonata, così alto e nero, stormi di ragazziscappano da tutte le parti, piantando lì il giuoco dei pennini e delle biglie, ed egli li minaccia conl'indice da lontano, con la sua aria amorevole e triste. Nessuno l'ha più visto ridere, dice mia madre,dopo che gli è morto il figliuolo ch'era volontario nell'esercito; ed egli ha sempre il suo ritrattodavanti agli occhi, sul tavolino della Direzione. E se ne voleva andare dopo quella disgrazia; avevagià fatto la sua domanda di riposo al Municipio, e la teneva sempre sul tavolino, aspettando digiorno in giorno a mandarla, perché gli rincresceva di lasciare i fanciulli. Ma l'altro giorno parevadeciso, e mio padre ch'era con lui nella Direzione, gli diceva: - Che peccato che se ne vada, signorDirettore! - quando entrò un uomo a fare iscrivere un ragazzo, che passava da un'altra sezione allanostra perché aveva cambiato di casa. A veder quel ragazzo il Direttore fece un atto di meraviglia, -lo guardò un pezzo, guardò il ritratto che tien sul tavolino e tornò a guardare il ragazzo, tirandoselofra le ginocchia e facendogli alzare il viso. Quel ragazzo somigliava tutto al suo figliuolo morto. IlDirettore disse: - Va bene; - fece l'iscrizione, congedò padre e figlio, e restò pensieroso. - Chepeccato che se ne vada! - ripeté mio padre.
	E allora il Direttore prese la sua domanda di riposo, lafece in due pezzi e disse: - Rimango.`,
}
