export const chapter_20 = {
	name: '22, martedì',
	header: 'I soldati',
	text: `Il suo figliuolo era volontario nell'esercito quando morì: per questo il Direttore va sempre sul corsoa veder passare i soldati, quando usciamo dalla scuola.
	Ieri passava un reggimento di fanteria, e cinquanta ragazzi si misero a saltellare intorno alla banda musicale, cantando e battendo il tempocolle righe sugli zaini e sulle cartelle.
	Noi stavamo in un gruppo, sul marciapiede a guardare:Garrone, strizzato nei suoi vestiti troppo stretti, che addentava un gran pezzo di pane; Votini, quelloben vestito, che si leva sempre i peluzzi dai panni; Precossi, il figliuolo del fabbro, con la giacchettadi suo padre, e il calabrese, e il muratorino, e Crossi con la sua testa rossa, e Franti con la sua facciatosta, e anche Robetti, il figliuolo del capitano d'artiglieria, quello che salvò un bambinodall'omnibus, e che ora cammina con le stampelle.
	Franti fece una risata in faccia a un soldato chezoppicava. Ma subito si sentì la mano d'un uomo sulla spalla: si voltò: era il Direttore. - Bada, - glidisse il Direttore; - schernire un soldato quand'è nelle file, che non può né vendicarsi né rispondere,è come insultare un uomo legato: è una viltà. - Franti scomparve. I soldati passavano a quattro aquattro, sudati e coperti di polvere, e i fucili scintillavano al sole. Il Direttore disse: - Voi dovetevoler bene ai soldati, ragazzi. Sono i nostri difensori, quelli che andrebbero a farsi uccidere per noi,se domani un esercito straniero minacciasse il nostro paese.
	Sono ragazzi anch'essi, hanno pochianni più di voi; e anch'essi vanno a scuola; e ci sono poveri e signori, fra loro, come fra voi, evengono da tutte le parti d'Italia. Vedete, si posson quasi riconoscere al viso: passano dei Siciliani,dei Sardi, dei Napoletani, dei Lombardi. Questo poi è un reggimento vecchio, di quelli che hannocombattuto nel 1848. I soldati non son più quelli, ma la bandiera è sempre la stessa. Quanti eranogià morti per il nostro paese intorno a quella bandiera venti anni prima che voi nasceste! - Eccolaqui, - disse Garrone. E infatti si vedeva poco lontano la bandiera, che veniva innanzi, al di sopradelle teste dei soldati. - Fate una cosa, figliuoli, - disse il Direttore, - fate il vostro saluto di scolari,con la mano alla fronte, quando passano i tre colori. - La bandiera, portata da un ufficiale, ci passòdavanti, tutta lacera e stinta, con le medaglie appese all'asta. Noi mettemmo la mano alla fronte,tutt'insieme.
L'ufficiale ci guardò, sorridendo, e ci restituì il saluto con la mano. - Bravi, ragazzi, -disse uno dietro di noi. Ci voltammo a guardare: era un vecchio che aveva all'occhiello del vestito ilnastrino azzurro della campagna di Crimea: un ufficiale pensionato. - Bravi, - disse, - avete fattouna cosa bella. - Intanto la banda del reggimento svoltava in fondo al corso, circondata da una turbadi ragazzi, e cento grida allegre accompagnavan gli squilli delle trombe come un canto di guerra. -Bravi, - ripeté il vecchio ufficiale, guardandoci; - chi rispetta la bandiera da piccolo la saprà difenderda grande.`,
}
