export const chapter_30 = {
	name: '17, sabato',
	header: 'Le maestre',
	text: `Garoffi stava tutto pauroso, quest'oggi, ad aspettare una grande risciacquata del maestro; ma ilmaestro non è comparso, e poiché mancava anche il supplente, è venuta a far scuola la signoraCromi, la più attempata delle maestre, che ha due figliuoli grandi e ha insegnato a leggere e ascrivere a parecchie signore che ora vengono ad accompagnare i loro ragazzi alla Sezione Baretti.
	Era triste, oggi, perché ha un figliuolo malato. Appena che la videro, cominciarono a fare il chiasso.Ma essa con voce lenta e tranquilla disse: - Rispettate i miei capelli bianchi: io non sono soltantouna maestra, sono una madre; - e allora nessuno osò più di parlare, neanche quella faccia di bronzodi Franti, che si contentò di farle le beffe di nascosto.
	Nella classe della Cromi fu mandata laDelcati, maestra di mio fratello, e al posto della Delcati, quella che chiamano «la monachina»,perché è sempre vestita di scuro, con un grembiale nero, e ha un viso piccolo e bianco, i capellisempre lisci gli occhi chiari chiari, e una voce sottile, che par sempre che mormori preghiere.
	E nonsi capisce, dice mia madre: è così mite e timida, con quel filo di voce sempre eguale, che appena sisente, e non grida, non s'adira mai: eppure tiene i ragazzi quieti che non si sentono, i più monellichinano il capo solo che li ammonisca col dito, pare una chiesa la sua scuola, e per questo anchechiamano lei la monachina.
	Ma ce n'è un'altra che mi piace pure: la maestrina della prima inferiorenumero 3, quella giovane col viso color di rosa, che ha due belle pozzette nelle guancie, e porta unagran penna rossa sul cappellino e una crocetta di vetro giallo appesa al collo. È sempre allegra, tienla classe allegra, sorride sempre, grida sempre con la sua voce argentina che par che canti,picchiando la bacchetta sul tavolino e battendo le mani per impor silenzio; poi quando escono, correcome una bambina dietro all'uno e all'altro, per rimetterli in fila; e a questo tira su il bavero, aquell'altro abbottona il cappotto perché non infreddino, li segue fin nella strada perché nons'accapiglino, supplica i parenti che non li castighino a casa, porta delle pastiglie a quei che han latosse, impresta il suo manicotto a quelli che han freddo; ed è tormentata continuamente dai piùpiccoli che le fanno carezze e le chiedon dei baci tirandola pel velo e per la mantiglia; ma essa lilascia fare e li bacia tutti, ridendo, e ogni giorno ritorna a casa arruffata e sgolata, tutta ansante etutta contenta, con le sue belle pozzette e la sua penna rossa.
	È anche maestra di disegno delleragazze, e mantiene col proprio lavoro sua madre e suo fratello.`,
}
