export const chapter_17 = {
	name: '10, giovedì',
	header: 'Mia madre',
	text: `In presenza della maestra di tuo fratello tu mancasti di rispetto a tua madre! Che questo non avvengamai più, Enrico, mai più! La tua parola irriverente m'è entrata nel cuore come una punta d'acciaio.
	Iopensai a tua madre quando, anni sono, stette chinata tutta una notte sul tuo piccolo letto, a misurareil tuo respiro, piangendo sangue dall'angoscia e battendo i denti dal terrore, ché credeva di perderti,ed io temevo che smarrisse la ragione; e a quel pensiero provai un senso di ribrezzo per te.
	Tu,offender tua madre! tua madre che darebbe un anno di felicità per risparmiarti un'ora di dolore, chemendicherebbe per te, che si farebbe uccidere per salvarti la vita! Senti, Enrico. Fissati bene inmente questo pensiero. Immagina pure che ti siano destinati nella vita molti giorni terribili; il piùterribile di tutti sarà il giorno in cui perderai tua madre. Mille volte, Enrico, quando già sarai uomo,forte, provato a tutte le lotte, tu la invocherai, oppresso da un desiderio immenso di risentire unmomento la sua voce e di rivedere le sue braccia aperte per gettarviti singhiozzando, come unpovero fanciullo senza protezione e senza conforto.
	Come ti ricorderai allora d'ogni amarezza che leavrai cagionato, e con che rimorsi le sconterai tutte, infelice! Non sperar serenità nella tua vita, seavrai contristato tua madre. Tu sarai pentito, le domanderai perdono, venererai la sua memoria; -inutilmente, - la coscienza non ti darà pace, quella immagine dolce e buona avrà sempre per teun'espressione di tristezza e di rimprovero che ti metterà l'anima alla tortura. O Enrico, bada: questoè il più sacro degli affetti umani, disgraziato chi lo calpesta. L'assassino che rispetta sua madre haancora qualcosa di onesto e di gentile nel cuore, il più glorioso degli uomini, che l'addolori el'offenda, non è che una vile creatura.
	Che non t'esca mai più dalla bocca una dura parola per coleiche ti diede la vita. E se una ancora te ne sfuggisse, non sia il timore di tuo padre, sia l'impulsodell'anima che ti getti ai suoi piedi, a supplicarla che col bacio del perdono ti cancelli dalla fronte ilmarchio dell'ingratitudine. Io t'amo, figliuol mio, tu sei la speranza più cara della mia vita; ma vorreipiuttosto vederti morto che ingrato a tua madre.
	Va', e per un po' di tempo non portarmi più la tuacarezza; non te la potrei ricambiare col cuore.
	TUO PADRE`,
}
