export const chapter_18 = {
	name: '13, domenica',
	header: 'Il mio compagno Coretti',
	text: `Mio padre mi perdonò; ma io rimasi un poco triste, e allora mia madre mi mandò col figliuologrande del portinaio a fare una passeggiata sul corso.
	A metà circa del corso, passando vicino a uncarro fermo davanti a una bottega, mi sento chiamare per nome, mi volto: era Coretti, il miocompagno di scuola, con la sua maglia color cioccolata e il suo berretto di pelo di gatto tutto sudatoe allegro, che aveva un gran carico di legna sulle spalle. Un uomo ritto sul carro gli porgeva unabracciata di legna per volta, egli le pigliava e le portava nella bottega di suo padre, dove in fretta e infuria le accatastava.- Che fai, Coretti? - gli domandai.- Non vedi? - rispose, tendendo le braccia per pigliare il carico, - ripasso la lezione.Io risi. Ma egli parlava sul serio, e presa la bracciata di legna, cominciò a dire correndo: - Chiamansiaccidenti del verbo... le sue variazioni secondo il numero... secondo il numero e la persona...E poi, buttando giù la legna e accatastandola: - secondo il tempo... secondo il tempo a cui si riferiscel'azione...
E tornando verso il carro a prendere un'altra bracciata: - secondo il modo in cui l'azione è enunciata.Era la nostra lezione di grammatica per il giorno dopo. - Che vuoi, - mi disse, - metto il tempo aprofitto.
Mio padre è andato via col garzone per una faccenda. Mia madre è malata. Tocca a me ascaricare. Intanto ripasso la grammatica. È una lezione difficile oggi. Non riesco a pestarmela nellatesta.
Mio padre ha detto che sarà qui alle sette per darvi i soldi, - disse poi all'uomo del carro.Il carro partì. - Vieni un momento in bottega, - mi disse Coretti.
Entrai: era uno stanzone pieno dicataste di legna e di fascine, con una stadera da una parte. - Oggi è giorno di sgobbo, te lo accertoio, - ripigliò Coretti; - debbo fare il lavoro a pezzi e a bocconi. Stavo scrivendo le proposizioni, èvenuta gente a comprare.
Mi son rimesso a scrivere, eccoti il carro. Questa mattina ho già fatto duecorse al mercato delle legna in piazza Venezia. Non mi sento più le gambe e ho le mani gonfie.Starei fresco se avessi il lavoro di disegno! - E intanto dava un colpo di scopa alle foglie secche e aifuscelli che coprivano l'ammattonato.- Ma dove lo fai il lavoro, Coretti? - gli domandai.- Non qui di certo, - riprese; - vieni a vedere; - e mi condusse in uno stanzino dietro la bottega, cheserve da cucina e da stanza da mangiare, con un tavolo in un canto, dove ci aveva i libri e iquaderni, e il lavoro incominciato. - Giusto appunto, disse, - ho lasciato la seconda risposta per aria:col cuoio si fanno le calzature, le cinghie... Ora ci aggiungo le valigie. - E presa la penna, si mise ascrivere con la sua bella calligrafia. - C'è nessuno? - s'udì gridare in quel momento dalla bottega.Era una donna che veniva a comprar fascinotti. - Eccomi, - rispose Coretti; e saltò di là, pesò ifascinotti, prese i soldi, corse in un angolo a segnar la vendita in uno scartafaccio e ritornò al suolavoro, dicendo: - Vediamo un po' se mi riesce di finire il periodo. - E scrisse: le borse da viaggio,gli zaini per i soldati. - Ah il mio povero caffè che scappa via! - gridò all'improvviso e corse alfornello a levare la caffettiera dal fuoco. - È il caffè per la mamma, - disse; - bisognò bene cheimparassi a farlo.
Aspetta un po' che glie lo portiamo; così ti vedrà, le farà piacere. Son sette giorniche è a letto... Accidenti del verbo! Mi scotto sempre le dita con questa caffettiera. Che cosa ho daaggiungere dopo gli zaini per i soldati? Ci vuole qualche altra cosa e non la trovo. Vieni dallamamma.Aperse un uscio, entrammo in un'altra camera piccola: c'era la mamma di Coretti in un letto grande,con un fazzoletto bianco intorno al capo.- Ecco il caffè, mamma, - disse Coretti porgendo la tazza; - questo è un mio compagno di scuola.- Ah! bravo il signorino, - mi disse la donna; - viene a far visita ai malati, non è vero?Intanto Coretti accomodava i guanciali dietro alle spalle di sua madre, raggiustava le coperte delletto, riattizzava il fuoco, cacciava il gatto dal cassettone. - Vi occorre altro, mamma? - domandòpoi, ripigliando la tazza. - Li avete presi i due cucchiaini di siroppo? Quando non ce ne sarà più daròuna scappata dallo speziale. Le legna sono scaricate. Alle quattro metterò la carne al fuoco, comeavete detto, e quando passerà la donna del burro le darò quegli otto soldi. Tutto andrà bene, non vidate pensiero.- Grazie, figliuolo, - rispose la donna; - povero figliuolo, va'! Egli pensa a tutto.Volle che pigliassi un pezzo di zucchero, e poi Coretti mi mostrò un quadretto, il ritratto infotografia di suo padre, vestito da soldato, con la medaglia al valore, che guadagnò nel '66, nelquadrato del principe Umberto; lo stesso viso del figliuolo, con quegli occhi vivi e quel sorriso cosìallegro. Tornammo nella cucina. - Ho trovato la cosa, - disse Coretti, e aggiunse sul quaderno: sifanno anche i finimenti dei cavalli. - Il resto lo farò stasera, starò levato fino a più tardi. Felice teche hai tutto il tempo per studiare e puoi ancora andare a passeggio!E sempre gaio e lesto, rientrato in bottega, cominciò a mettere dei pezzi di legno sul cavalletto e asegarli per mezzo, e diceva: - Questa è ginnastica! Altro che la spinta delle braccia avanti. Voglioche mio padre trovi tutte queste legna segate quando torna a casa: sarà contento. Il male è che dopoaver segato faccio dei t e degli l, che paion serpenti, come dice il maestro. Che ci ho da fare? Glidirò che ho dovuto menar le braccia. Quello che importa è che la mamma guarisca presto, questo sì.Oggi sta meglio, grazie al cielo. La grammatica la studierò domattina al canto del gallo. Oh! ecco lacarretta coi ceppi! Al lavoro.Una carretta carica di ceppi si fermò davanti alla bottega. Coretti corse fuori a parlar con l'uomo poitornò. - Ora non posso più tenerti compagnia, - mi disse; - a rivederci domani. Hai fatto bene avenirmi a trovare. Buona passeggiata! Felice te.
E strettami la mano, corse a pigliar il primo ceppo, e ricominciò a trottare fra il carro e la bottega,col viso fresco come una rosa sotto al suo berretto di pel di gatto, e vispo che metteva allegrezza avederloFelice te! egli mi disse. Ah no, Coretti, no: sei tu il più felice, tu perché studi e lavori di più, perchései più utile a tuo padre e a tua madre, perché sei più buono, cento volte più buono e più bravo dime, caro compagno mio.`,
}
