export const chapter_16 = {
	name: '10, giovedì',
	header: 'La maestra di mio fratello',
	text: `Il figliuolo del carbonaio fu scolaro della maestra Delcati che è venuta oggi a trovar mio fratellomalaticcio, e ci ha fatto ridere a raccontarci che la mamma di quel ragazzo, due anni fa, le portò acasa una grande grembialata di carbone, per ringraziarla, che aveva dato la medaglia al figliuolo; es'ostinava, povera donna, non voleva riportarsi il carbone a casa, e piangeva quasi, quando dovettetornarsene col grembiale pieno. Anche d'un'altra buona donna, ci ha detto, che le portò un mazzettodi fiori molto pesante, e c'era dentro un gruzzoletto di soldi. Ci siamo molto divertiti a sentirla, ecosì mio fratello trangugiò la medicina, che prima non voleva. Quanta pazienza debbono avere conquei ragazzi della prima inferiore, tutti sdentati come vecchietti, che non pronunziano l'erre e l'esse,e uno tosse, l'altro fila sangue dal naso, chi perde gli zoccoli sotto il banco, e chi bela perché s'èpunto con la penna, e chi piange perché ha comprato un quaderno numero due invece di numerouno.
	Cinquanta in una classe, che non san nulla, con quei manini di burro, e dover insegnare ascrivere a tutti!
	Essi portano in tasca dei pezzi di regolizia, dei bottoni, dei turaccioli di boccetta, delmattone tritato, ogni specie di cose minuscole, e bisogna che la maestra li frughi; ma nascondon glioggetti fin nelle scarpe. E non stanno attenti: un moscone che entra per la finestra, mette tuttisottosopra, e l'estate portano in iscuola dell'erba e dei maggiolini, che volano in giro o cascano neicalamai e poi rigano i quaderni d'inchiostro. La maestra deve far la mamma con loro, aiutarli avestirsi, fasciare le dita punte, raccattare i berretti che cascano, badare che non si scambino icappotti, se no poi gnaulano e strillano. Povere maestre! E ancora vengono le mamme a lagnarsi:come va, signorina, che il mio bambino ha perso la penna? com'è che il mio non impara niente?perché non dà la menzione al mio, che sa tanto? perché non fa levar quel chiodo dal banco che hastracciato i calzoni al mio Piero? Qualche volta s'arrabbia coi ragazzi la maestra di mio fratello, equando non ne può più, si morde un dito, per non lasciar andare una pacca; perde la pazienza, mapoi si pente, e carezza il bimbo che ha sgridato; scaccia un monello di scuola, ma si ribeve lelacrime, e va in collera coi parenti che fan digiunare i bimbi per castigo.
	È giovane e grande lamaestra Delcati, e vestita bene, bruna e irrequieta, che fa tutto a scatto di molla, e per un nulla sicommove, e allora parla con grande tenerezza. - Ma almeno i bimbi le si affezionano? - le ha dettomia madre. - Molti sì, - ha risposto, - ma poi, finito l'anno, la maggior parte non ci guardan più.Quando sono coi maestri, si vergognano quasi d'essere stati da noi, da una maestra. Dopo due annidi cure, dopo che s'è amato tanto un bambino, ci fa tristezza separarci da lui, ma si dice: - Oh di
quello lì son sicura; quello lì mi vorrà bene. - Ma passano le vacanze, si rientra alla scuola, glicorriamo incontro: - O bambino, bambino mio! - E lui volta il capo da un'altra parte. - Qui lamaestra s'è interrotta. - Ma tu non farai così piccino? - ha detto poi, alzandosi con gli occhi umidi, ebaciando mio fratello, - tu non la volterai la testa dall'altra parte, non è vero? non la rinnegherai latua povera amica.`,
}
