export const chapter_24 = {
	name: 'I poveri',
	header: '29, martedì',
	text: `Dare la vita per il proprio paese, come il ragazzo lombardo, è una grande virtù, ma tu non trascurarele virtù piccole, figliuolo.
	Questa mattina, camminando davanti a me quando tornavamo dallascuola, passasti accanto a una povera, che teneva fra le ginocchia un bambino stentito e smorto, eche ti domandò l'elemosina.
	Tu la guardasti e non le desti nulla, e pure ci avevi dei soldi in tasca.Senti, figliuolo. Non abituarti a passare indifferente davanti alla miseria che tende la mano, e tantomeno davanti a una madre che chiede un soldo per il suo bambino. Pensa che forse quel bambinoaveva fame! pensa allo strazio di quella povera donna. Te lo immagini il singhiozzo disperato di tuamadre, quando un giorno ti dovesse dire. - Enrico, oggi non posso darti nemmen del pane? -Quand'io do un soldo a un mendico, ed egli mi dice. - Dio conservi la salute a lei e alle sue creature!- tu non puoi comprendere la dolcezza che mi danno al cuore quelle parole, la gratitudine che sentoper quel povero.
	Mi par davvero che quel buon augurio debba conservarsi in buona salute per moltotempo, e ritorno a casa contento. e penso: Oh! quel povero m'ha reso assai più di quanto gli ho dato!Ebbene, fa ch'io senta qualche volta quel buon augurio provocato, meritato da te, togli tratto trattoun soldo dalla tua piccola borsa per lasciarlo cadere nella mano d'un vecchio senza sostegno, d'unamadre senza pane, d'un bimbo senza madre. I poveri amano l'elemosina dei ragazzi perché non liumilia, e perché i ragazzi, che han bisogno di tutti, somigliano a loro. vedi che ce n'è sempre intornoalle scuole, dei poveri.
	L'elemosina d'un uomo è un atto di carità, ma quella d'un fanciullo è insiemeun atto di carità e una carezza, capisci? È come se dalla sua mano cadessero insieme un soldo e unfiore. Pensa che a te non manca nulla, ma che a loro manca tutto; che mentre tu vuoi esser felice, aloro basta di non morire. Pensa che è un orrore che in mezzo a tanti palazzi, per le vie dove passancarrozze e bambini vestiti di velluto, ci siano delle donne, dei bimbi che non hanno da mangiare.Non aver da mangiare, Dio mio! Dei ragazzi come te, buoni come te, intelligenti come te, che inmezzo a una grande città non han da mangiare, come belve perdute in un deserto!
	Oh mai più,Enrico, non passare mai più davanti a una madre che méndica senza metterle un soldo nella mano!
	TUA MADRE`,
}
