export const chapter_21 = {
	name: '23, mercoledì',
	header: 'Il protettore di Nelli',
	text: `Anche Nelli, ieri, guardava i soldati, povero gobbino, ma con un'aria così, come se pensasse: - Ionon potrò esser mai un soldato! - Egli è buono, studia; ma è così magrino e smorto, e respira afatica.
	Porta sempre un lungo grembiale di tela nera lucida. Sua madre è una signora piccola abionda, vestita di nero, e vien sempre a prenderlo al finis, perché non esca nella confusione, con glialtri; e lo accarezza. I primi giorni, perché ha quella disgrazia d'esser gobbo, molti ragazzi lobeffavano e gli picchiavan sulla schiena con gli zaini; ma egli non si rivoltava mai, e non diceva mainulla a sua madre, per non darle quel dolore di sapere che suo figlio era lo zimbello dei compagni;lo schernivano, ed egli piangeva e taceva, appoggiando la fronte sul banco.
	Ma una mattina saltò suGarrone e disse: - Il primo che tocca Nelli gli do uno scapaccione che gli faccio far tre giravolte! -Franti non gli badò, lo scapaccione partì, l'amico fece le tre giravolte, e dopo d'allora nessuno toccòpiù Nelli. Il maestro gli mise Garrone vicino, nello stesso banco. Si sono fatti amici. Nelli s'èaffezionato molto a Garrone.
	Appena entra nella scuola, cerca subito se c'è Garrone. Non va mai viasenza dire: - Addio, Garrone. - E così fa Garrone con lui. Quando Nelli lascia cascar la penna o unlibro sotto il banco, subito, perché non faccia fatica a chinarsi, Garrone si china e gli porge il libro ola penna; e poi l'aiuta a rimetter la roba nello zaino, e a infilarsi il cappotto.
	Per questo Nelli gli vuolbene, e lo guarda sempre, e quando il maestro lo loda è contento, come se lodasse lui. Ora bisognache Nelli, finalmente, abbia detto tutto a sua madre, e degli scherni dei primi giorni e di quello chegli facevan patire, e poi del compagno che lo difese e che gli ha posto affetto, perché, ecco quelloche accadde questa mattina. Il maestro mi mandò a portare al Direttore il programma della lezione,mezz'ora prima del finis, ed io ero nell'ufficio quando entrò una signora bionda e vestita di nero, la
mamma di Nelli, la quale disse: - Signor Direttore, c'è nella classe del mio figliuolo un ragazzo chesi chiama Garrone? - C'è, - rispose il Direttore. - Vuol aver la bontà di farlo venire un momento qui,che gli ho da dire una parola? - Il Direttore chiamò il bidello e lo mandò in iscuola, e dopo unminuto ecco lì Garrone sull'uscio con la sua testa grossa e rapata, tutto stupito. Appena lo vide, lasignora gli corse incontro, gli gettò le mani sulle spalle e gli diede tanti baci sulla testa dicendo: -Sei tu, Garrone, l'amico del mio figliuolo, il protettore del mio povero bambino, sei tu, caro, bravoragazzo, sei tu! - Poi frugò in furia nelle tasche e nella borsa, e non trovando nulla, si staccò dalcollo una catenella con una crocina, e la mise al collo di Garrone, sotto la cravatta, e gli disse: -Prendila, portala per mia memoria, caro ragazzo, per memoria della mamma di Nelli, che tiringrazia e ti benedice.`,
}
