export const chapter_26 = {
	name: '5, lunedì',
	header: 'Vanità',
	text: `Ieri andai a far la passeggiata per il viale di Rivoli con Votini e suo padre. Passando per via DoraGrossa, vedemmo Stardi, quello che tira calci ai disturbatori, fermo impalato davanti a una vetrinadi librario, cogli occhi fissi sopra una carta geografica; e chi sa da quanto tempo era là, perché eglistudia anche per la strada: ci rese a mala pena il saluto, quel rusticone.
	Votini era vestito bene,anche troppo: aveva gli stivali di marocchino trapunti di rosso, un vestito con ricami e nappine diseta, un cappello di castoro bianco e l'orologio. E si pavoneggiava. Ma la sua vanità doveva capitarmale questa volta. Dopo aver corso un bel pezzo su per il viale, lasciandoci molto addietro suopadre, che andava adagio, ci fermammo a un sedile di pietra, accanto a un ragazzo vestitomodestamente, che pareva stanco, e pensava, col capo basso.
	Un uomo, che doveva essere suopadre, andava e veniva sotto gli alberi, leggendo la gazzetta. Ci sedemmo. Votini si mise tra me e ilragazzo. E subito si ricordò d'essere vestito bene, e volle farsi ammirare e invidiare dal suo vicino.Alzò un piede e mi disse: - Hai visto i miei stivali da ufficiale? - Lo disse per farli guardar daquell'altro. Ma quegli non gli badò.Allora abbassò il piede, e mi mostrò le sue nappine di seta, e mi disse, guardando di sott'occhio ilragazzo, che quelle nappine di seta non gli piacevano, e che le volea far cambiare in bottonid'argento.
	Ma il ragazzo non guardò neppure le nappine.Votini allora si mise a far girare sulla punta dell'indice il suo bellissimo cappello di castoro bianco.Ma il ragazzo, pareva che lo facesse per punto, non degnò d'uno sguardo nemmeno il cappello.Votini, che si cominciava a stizzire, tirò fuori l'orologio l'aperse, mi fece veder le rote. Ma queglinon voltò la testa. - È d'argento dorato? - gli domandai. - No, - rispose, - è d'oro. - Ma non sarà tuttod'oro, - dissi, - ci sarà anche dell'argento. - Ma no! - egli ribatté; - e per costringere il ragazzo aguardare gli mise l'orologio davanti al viso e gli disse: - Di' tu, guarda, non è vero che è tutto d'oro?Il ragazzo rispose secco: - Non lo so.- Oh! oh! - esclamò Votini, pien di rabbia, - che superbia!Mentre diceva questo, sopraggiunse suo padre, che sentì: guardò un momento fisso quel ragazzo,poi disse bruscamente al figliuolo: - Taci; - e chinatosi al suo orecchio soggiunse: - È cieco.Votini balzò in piedi, con un fremito, e guardò il ragazzo nel viso.
	Aveva le pupille vitree, senzaespressione, senza sguardo.Votini rimase avvilito, senza parola, con gli occhi a terra. Poi balbettò: - Mi rincresce... non losapevo.Ma il cieco, che aveva capito tutto, disse con un sorriso buono e malinconico: - Oh! non fa nulla.Ebbene, è vano; ma non ha mica cattivo cuore Votini.
	Per tutta la passeggiata non rise più.`,
}
