export const chapter_29 = {
	name: '16, venerdì',
	header: 'Una palla di neve',
	text: `E sempre nevica, nevica. Seguì un brutto caso, questa mattina, con la neve, all'uscir dalla scuola. Unbranco di ragazzi, appena sboccati sul Corso, si misero a tirar palle, con quella neve acquosa, che fale palle sode e pesanti come pietre.
	Molta gente passava sul marciapiedi. Un signore gridò: -Smettete, monelli! - e proprio in quel punto si udì un grido acuto dall'altra parte della strada, e sivide un vecchio che aveva perduto il cappello e barcollava, coprendosi il viso con le mani, e accantoa lui un ragazzo che gridava: - Aiuto! Aiuto! - Subito accorse gente da ogni parte.
	Era stato colpitoda una palla in un occhio.
	Tutti i ragazzi si sbandarono fuggendo come saette. Io stavo davanti allabottega del libraio, dov'era entrato mio padre, e vidi arrivar di corsa parecchi miei compagni che simescolarono fra gli altri vicini a me, e finsero di guardar le vetrine: c'era Garrone, con la sua solitapagnotta in tasca, Coretti, il muratorino, e Garoffi, quello dei francobolli.
	Intanto s'era fatta follaintorno al vecchio, e una guardia ed altri correvano qua e là minacciando e domandando: - Chi è?chi è stato? Sei tu? Dite chi è stato! - e guardavan le mani ai ragazzi, se le avevan bagnate di neve.Garoffi era accanto a me: m'accorsi che tremava tutto, e che avea il viso bianco come un morto. -Chi è? Chi è stato? - continuava a gridare la gente. - Allora intesi Garrone che disse piano a Garoffi:- Su, vatti a presentare; sarebbe una vigliaccheria lasciar agguantare qualcun altro. - Ma io non l'hofatto apposta! - rispose Garoffi, tremando come una foglia. - Non importa fa il tuo dovere, - ripetéGarrone. - Ma io non ho coraggio! - Fatti coraggio, t'accompagno io. - E la guardia e gli altrigridavan sempre più forte: - Chi è? Chi è stato? Un occhiale in un occhio gli han fatto entrare!L'hanno accecato! Briganti! - Io credetti che Garoffi cascasse in terra. - Vieni, - gli disserisolutamente Garrone, - io ti difendo, - e afferratolo per un braccio lo spinse avanti, sostenendolo,come un malato. La gente vide e capì subito, e parecchi accorsero coi pugni alzati.
	Ma Garrone sifece in mezzo, gridando: - Vi mettete in dieci uomini contro un ragazzo? - Allora quelli ristettero, euna guardia civica pigliò Garoffi per mano e lo condusse, aprendo la folla, a una bottega di pastaio,dove avevano ricoverato il ferito. Vedendolo, riconobbi subito il vecchio impiegato, che sta alquarto piano di casa nostra, col suo nipotino. Era adagiato sur una seggiola, con un fazzoletto sugliocchi. - Non l'ho fatto apposta! - diceva singhiozzando Garoffi, mezzo morto dalla paura, - non l'hofatto apposta! - Due o tre persone lo spinsero violentemente nella bottega, gridando: - La fronte aterra! Domanda perdono! - e lo gettarono a terra. Ma subito due braccia vigorose lo rimisero in piedie una voce risoluta disse: - No, signori! - Era il nostro Direttore, che avea visto tutto. - Poiché haavuto il coraggio di presentarsi, - soggiunse- nessuno ha il diritto di avvilirlo. Tutti stettero zitti. -Domanda perdono, - disse il Direttore a Garoffi. Garoffi, scoppiando in pianto, abbracciò leginocchia del vecchio, e questi, cercata con la mano la testa di lui, gli carezzò i capelli.
	Allora tuttidissero: - Va', ragazzo, va', torna a casa! - E mio padre mi tirò fuori della folla e mi disse stradafacendo: - Enrico, in un caso simile, avresti il coraggio di fare il tuo dovere, di andar a confessare latua colpa? - Io gli risposi di sì. Ed egli: - Dammi la tua parola di ragazzo di cuore e d'onore che lofaresti. - Ti do la mia parola, padre mio!`,
}
