// Глава адаптирована
export const chapter_22 = {
	name: 'CHAPITRE XXII',
	header: 'Les contrebandiers',
	text: `Dantès n’avait pas passé un jour à bord qu’il avait déjà compris à qui il avait affaire. Le patron de “La Jeune-Amélie” – c’était le nom de la tartane – parlait presque toutes les langues de la Méditerranée. Cela lui permettait de communiquer facilement avec les autres navires et les gens qu’il rencontrait sur les quais, des hommes sans nom ni patrie qui vivent de ressources mystérieuses. Dantès comprit vite qu’il était à bord d’un navire de contrebandiers.
Le patron l’avait donc accueilli avec une certaine méfiance. Il était connu de tous les douaniers de la côte, et il pensait que Dantès pouvait être un espion des douanes. Mais la manière brillante dont Dantès avait manœuvré le navire l’avait entièrement convaincu. Puis, en voyant la fumée du canon du château d’If, il avait eu l’idée que son nouvel homme était un prisonnier important, ce qui l’inquiétait beaucoup moins qu’un douanier. La tranquillité parfaite de sa recrue avait fini par le rassurer.
Edmond avait donc l’avantage de savoir qui était son patron, sans que son patron sache qui il était. Il restait ferme face aux questions de l’équipage, répétant son histoire d’un naufrage près de Malte, une île qu’il connaissait bien. Le Génois, pourtant très malin, se laissa tromper par la douceur d’Edmond, son expérience de la mer et, surtout, sa parfaite dissimulation. Et puis, peut-être que le Génois était de ces gens d’esprit qui ne croient que ce qu’ils ont intérêt à croire.
C’est dans cette situation qu’ils arrivèrent à Livourne.
Edmond allait y faire une nouvelle expérience : savoir s’il se reconnaîtrait lui-même après quatorze ans sans s’être vu. Il avait un souvenir assez précis du jeune homme qu’il était ; il allait voir ce qu’était devenu l’homme.
Son vœu de ne pas se couper les cheveux ni la barbe était accompli. Il connaissait un barbier à Livourne et alla chez lui. Le barbier fut étonné de voir cet homme à la longue chevelure et à la barbe noire et épaisse, qui ressemblait à un personnage d’un tableau du Titien. À cette époque, ce n’était pas la mode. Aujourd’hui, un barbier serait seulement surpris qu’un homme avec de si beaux atouts veuille s’en priver.
Le barbier se mit au travail sans faire de remarque. Quand l’opération fut terminée, qu’Edmond sentit son menton rasé de près et ses cheveux réduits à une longueur normale, il demanda un miroir et se regarda.
Il avait alors trente-trois ans. Ces quatorze années de prison avaient profondément changé son visage. Le visage rond et rieur du jeune homme heureux avait disparu. Son visage, devenu ovale, s’était allongé. Sa bouche souriante avait pris des lignes fermes, qui marquaient la résolution. Ses sourcils s’étaient arqués sous une ride unique et pensive. Ses yeux étaient empreints d’une profonde tristesse, d’où jaillissaient parfois de sombres éclairs de haine. Son teint, longtemps privé de lumière, avait pris cette couleur mate qui donne une beauté aristocratique. La science profonde qu’il avait acquise avait ajouté une auréole d’intelligence sur son visage. De plus, sa taille, naturellement haute, s’était épaissie ; il avait acquis la vigueur d’un corps dont la force est concentrée.
Quant à sa voix, les prières, les sanglots et les malédictions l’avaient changée. Elle était devenue tantôt d’une douceur étrange, tantôt rude et presque rauque. Ses yeux, habitués à la pénombre, avaient acquis la faculté de distinguer les objets dans la nuit, comme ceux du loup.
Edmond sourit en se voyant. Il était impossible que son meilleur ami – s’il lui en restait un – le reconnaisse. Il ne se reconnaissait pas lui-même.
Le patron de “La Jeune-Amélie”, qui voulait garder un homme de la valeur d’Edmond, lui proposa une avance sur ses futurs bénéfices. Edmond accepta et s’acheta une tenue complète de marin : un pantalon blanc, une chemise rayée et un bonnet phrygien. C’est ainsi vêtu qu’il reparut devant le patron, qui eut du mal à reconnaître dans ce marin élégant l’homme nu et mourant qu’il avait recueilli. Convaincu par sa bonne mine, il renouvela ses propositions d’engagement. Mais Dantès, qui avait ses propres projets, n’accepta que pour trois mois.
L’équipage de “La Jeune-Amélie” était très actif. Huit jours après, le navire était rempli de marchandises de contrebande : tissus, poudre anglaise, tabac… Il fallait faire sortir tout cela de Livourne, port franc, et le débarquer en Corse, d’où d’autres spéculateurs se chargeraient de le faire passer en France.
On partit. Edmond fendit de nouveau cette mer d’azur qu’il avait tant vue dans les rêves de sa prison. Il laissa la Gorgone à sa droite, la Pianosa à sa gauche, et s’avança vers la Corse.
Le lendemain matin, le patron trouva Dantès sur le pont, regardant avec une expression étrange un amas de rochers granitiques que le soleil levant inondait de lumière rose : c’était l’île de Monte-Cristo.
“La Jeune-Amélie” la laissa à tribord et continua sa route. Dantès songeait qu’il n’aurait qu’à sauter à la mer pour être en une demi-heure sur cette terre promise. Mais que ferait-il là, sans outils pour trouver le trésor, sans armes pour le défendre ? Et que diraient les marins ? Il fallait attendre. Heureusement, Dantès avait appris à attendre.
D’ailleurs, cette richesse n’était-elle pas un rêve, né dans l’esprit malade du pauvre abbé ? Pourtant, la lettre du cardinal Spada était étrangement précise. Et Dantès se la répétait sans cesse, mot pour mot.
Le soir vint. L’île disparut dans l’obscurité, mais lui, avec sa vue habituée à l’ombre de sa prison, continua sans doute de la voir, car il resta le dernier sur le pont.
Le lendemain, près d’Aleria, après avoir échangé des signaux avec des feux sur la côte, le chargement fut transféré sur quatre barques en pleine nuit. L’opération se passa sans problème. Chaque homme de l’équipage reçut cent livres toscanes, soit environ quatre-vingts francs. L’expédition n’était pas finie, il fallait maintenant aller recharger le navire en Sardaigne. Cette seconde opération fut aussi une réussite. La nouvelle cargaison, des cigares et du vin, était pour le duché de Lucques.
Là, ils eurent des problèmes avec les douanes. Un douanier fut tué, et deux matelots blessés. Dantès était l’un d’eux ; une balle lui avait traversé l’épaule. Il était presque heureux de cette blessure. Elle lui avait appris comment il faisait face au danger et à la souffrance. Il avait ri au danger, et en recevant le coup, il avait pensé : “Douleur, tu n’es pas un mal.” La vue du douanier mort ne lui avait produit qu’une légère impression. Son cœur était en train de se pétrifier.
Jacopo, le matelot qui l’avait sauvé, s’était précipité sur lui, l’avait soigné comme un excellent camarade. Le monde n’était donc pas si méchant, puisqu’un homme qui n’avait rien à attendre de lui montrait une telle affection.
Grâce à des herbes vendues par de vieilles femmes sardes, sa blessure guérit vite. Edmond offrit à Jacopo sa part des bénéfices, mais celui-ci refusa avec indignation. Edmond se prit d’affection pour Jacopo, qui, de son côté, avait instinctivement deviné la supériorité de cet homme et se contentait de l’amitié qu’il lui accordait.
Pendant les longues journées en mer, Edmond, une carte marine à la main, devint l’instituteur de Jacopo, comme l’abbé Faria l’avait été pour lui. Il lui montrait les côtes, lui expliquait la boussole, lui apprenait à lire les étoiles. Et quand Jacopo demandait : “À quoi bon apprendre tout ça ?”, Edmond répondait : “Qui sait ? Tu seras peut-être capitaine un jour. Ton compatriote Bonaparte est bien devenu empereur !” Nous avons oublié de dire que Jacopo était Corse.
Deux mois et demi passèrent. Edmond était devenu un caboteur aussi habile qu’il était autrefois un hardi marin. Il connaissait tous les contrebandiers et leurs signes secrets. Il était passé vingt fois devant son île de Monte-Cristo, mais sans jamais trouver l’occasion d’y débarquer.
Il prit donc une résolution : dès la fin de son engagement, il louerait une barque (il avait maintenant amassé une centaine de piastres) et, sous un prétexte quelconque, il se rendrait à l’île de Monte-Cristo pour y faire ses recherches en toute liberté.
Mais il flottait encore dans l’hésitation lorsque le patron, qui voulait le garder à son service, l’emmena un soir dans une taverne de Livourne où se réunissaient les meilleurs contrebandiers.
Cette fois, il était question d’une grosse affaire : un navire chargé de tapis turcs et d’étoffes du Levant. Il fallait trouver un terrain neutre pour faire l’échange, puis tenter de faire entrer la marchandise en France. La prime était énorme.
Le patron de “La Jeune-Amélie” proposa comme lieu de débarquement l’île de Monte-Cristo. Elle était déserte, sans soldats ni douaniers, comme si Mercure, le dieu des commerçants et des voleurs, l’avait placée là pour eux.
À ce nom, Dantès tressaillit de joie. Il se leva pour cacher son émotion et fit un tour dans la taverne enfumée. Quand il se rapprocha, la décision était prise : on ferait escale à Monte-Cristo. L’expédition partirait la nuit suivante.
Edmond, consulté, confirma que l’île offrait toutes les sécurités possibles et que les grandes entreprises, pour réussir, devaient être menées rapidement. Rien ne fut donc changé au plan. On appareillerait le lendemain soir.`,
}
