export const chapter_11 = {
	header: 'Nachwort',
	text: `Franz Kafkas Haltung zu seinem eigenen Werk und zu jeder Veröffentlichung war genauso eigenartig und tief wie alle anderen Ausdrucksformen seines Lebens. Die Probleme, die er in diesem Zusammenhang hatte, sind sehr ernst zu nehmen. Sie müssen deshalb auch ein Leitfaden für jede Veröffentlichung aus seinem Nachlass sein. Um dies besser zu verstehen, soll das Folgende dienen:

Fast alles, was Kafka veröffentlicht hat, habe ich ihm mit List und Überredung abgerungen. Das widerspricht nicht der Tatsache, dass er oft, in langen Phasen seines Lebens, durch sein Schreiben (er nannte es allerdings immer nur „Kritzeln“) sehr glücklich war. Wer ihn jemals im kleinen Kreis seine eigene Prosa vorlesen hörte – mit mitreißendem Feuer und einem Rhythmus, den kein Schauspieler je erreichen wird – der spürte sofort die echte, unbändige Schaffensfreude und Leidenschaft, die hinter diesem Werk stand. Dass er es trotzdem ablehnte, hatte verschiedene Gründe. Einerseits führten ihn traurige Erlebnisse zur Selbstsabotage und damit auch zu einer nihilistischen Haltung gegenüber seinem eigenen Werk. Andererseits legte er an sein Werk (ohne dies je auszusprechen) den höchsten religiösen Maßstab an, dem es, aus vielen Wirrungen entstanden, nicht entsprechen konnte. Dass sein Werk trotzdem vielen Menschen hätte helfen können, die nach Glauben, Natur und seelischer Gesundheit streben, durfte ihm nichts bedeuten. Er war mit unerbittlichem Ernst auf der Suche nach dem richtigen Weg für sich selbst und musste zunächst sich selbst, nicht anderen, Rat geben.

So erkläre ich mir Kafkas negative Haltung zu seinem eigenen Werk. Er sprach oft von den „falschen Händen, die sich einem während des Schreibens entgegenstrecken“. Er sagte auch, dass ihn das Geschriebene und erst recht das Veröffentlichte bei der weiteren Arbeit stören würde. Es gab viele Widerstände zu überwinden, bevor ein Buch von ihm erschien. Trotzdem hatte er an den fertigen, schönen Büchern und gelegentlich auch an ihrer Wirkung eine echte Freude. Es gab Zeiten, in denen er sich selbst und sein Werk mit wohlwollenderen Blicken betrachtete, nie ganz ohne Ironie, aber mit einer freundlichen Ironie. Hinter dieser Ironie verbarg sich das ungeheure Pathos eines Menschen, der kompromisslos nach dem Höchsten strebte.

In Franz Kafkas Nachlass wurde kein Testament gefunden. In seinem Schreibtisch lag jedoch zwischen vielen anderen Papieren ein zusammengefalteter, mit Tinte geschriebener Zettel mit meiner Adresse. Der Zettel hatte folgenden Wortlaut:

„Liebster Max, meine letzte Bitte: Alles, was sich in meinem Nachlass an Tagebüchern, Manuskripten, Briefen (fremden und eigenen), Gezeichnetem und so weiter findet (also im Bücherschrank, Wäscheschrank, Schreibtisch, zu Hause und im Büro, oder wohin auch immer etwas gebracht wurde und dir auffällt), restlos und ungelesen zu verbrennen. Ebenso alles Geschriebene oder Gezeichnete, das du oder andere, die du in meinem Namen darum bitten sollst, haben. Briefe, die man dir nicht geben will, soll man sich wenigstens verpflichten, selbst zu verbrennen.

Dein Franz Kafka.“


Bei genauerem Suchen fand sich auch noch ein mit Bleistift geschriebenes, vergilbtes Blatt, das offenbar älter war. Darauf stand:

„Lieber Max, vielleicht stehe ich diesmal doch nicht mehr auf. Nach einem Monat Lungenfieber ist es ziemlich wahrscheinlich, dass eine Lungenentzündung kommt. Und nicht einmal das Niederschreiben wird sie abwehren, obwohl es eine gewisse Macht hat.

Für diesen Fall also mein letzter Wille zu allem, was ich geschrieben habe:

Von allem, was ich geschrieben habe, gelten nur die Bücher: ‚Das Urteil‘, ‚Der Heizer‘, ‚Die Verwandlung‘, ‚In der Strafkolonie‘, ‚Ein Landarzt‘ und die Erzählung ‚Ein Hungerkünstler‘. (Die paar Exemplare der ‚Betrachtung‘ können bleiben, ich will niemandem die Mühe des Einstampfens machen, aber neu gedruckt darf daraus nichts werden.) Wenn ich sage, dass jene fünf Bücher und die Erzählung gelten, meine ich nicht, dass ich wünsche, sie mögen neu gedruckt und für die Zukunft überliefert werden. Im Gegenteil, sollten sie ganz verloren gehen, entspricht das meinem eigentlichen Wunsch. Aber da sie nun schon einmal da sind, hindere ich niemanden daran, sie zu behalten, wenn er Lust dazu hat.

Dagegen ist alles andere, was an Geschriebenem von mir existiert (in Zeitschriften Gedrucktes, im Manuskript oder in Briefen), ausnahmslos zu verbrennen. Dies gilt, soweit es erreichbar ist oder durch Bitten von den Empfängern zu erhalten ist (die meisten kennst du ja, hauptsächlich handelt es sich um .….….., vergiss besonders nicht die paar Hefte, die .…. hat). All dies ist ausnahmslos, am liebsten ungelesen, zu verbrennen. (Ich verbiete dir nicht, hineinzuschauen, aber am liebsten wäre es mir, wenn du es nicht tust. Jedenfalls darf niemand anderer hineinschauen.) Ich bitte dich, dies möglichst bald zu tun.

Franz“


Wenn ich mich diesen so klar ausgesprochenen Anweisungen widersetze und die zerstörerische Tat, die mein Freund von mir verlangt, nicht ausführe, so habe ich hierfür die triftigsten Gründe.

Einige davon kann ich nicht öffentlich diskutieren. Aber auch die, die ich mitteilen kann, sind meiner Meinung nach ausreichend, um meine Entscheidung zu verstehen.

Der Hauptgrund: Als ich 1921 meinen Beruf wechselte, erzählte ich meinem Freund, dass ich mein Testament gemacht hätte. Darin hatte ich ihn gebeten, bestimmte Dinge zu vernichten und anderes durchzusehen. Daraufhin zeigte mir Kafka von außen den mit Tinte geschriebenen Zettel, der später in seinem Schreibtisch gefunden wurde, und sagte: „Mein Testament wird ganz einfach sein – die Bitte an dich, alles zu verbrennen.“ Ich erinnere mich auch noch genau an meine Antwort: „Falls du mir im Ernst so etwas zumuten solltest, sage ich dir schon jetzt, dass ich deine Bitte nicht erfüllen werde.“ Das ganze Gespräch wurde in einem scherzhaften Ton geführt, wie es bei uns üblich war, aber mit einem heimlichen Ernst, den wir immer beim anderen voraussetzten. Wäre ihm seine eigene Verfügung unbedingter und letzter Ernst gewesen, hätte Franz, überzeugt von meiner Ablehnung, einen anderen Testamentsvollstrecker bestimmen müssen.

Ich bin ihm nicht dankbar, dass er mich in diesen schweren Gewissenskonflikt gestürzt hat. Er musste ihn voraussehen, denn er kannte meine fanatische Verehrung für jedes seiner Worte. Diese Verehrung hat mich in den 22 Jahren unserer ungetrübten Freundschaft unter anderem dazu veranlasst, nicht den kleinsten Zettel und keine Ansichtskarte von ihm wegzuwerfen. Das „ich bin nicht dankbar“ möge man übrigens nicht falsch verstehen! Was wiegt ein noch so schwerer Gewissenskonflikt im Vergleich zu dem unendlichen Segen, den ich dem Freund verdanke, der das eigentliche Rückgrat meiner ganzen geistigen Existenz war!

Weitere Gründe: Die Anweisung auf dem Bleistiftblatt hat Franz selbst nicht befolgt. Er hat später ausdrücklich erlaubt, dass Teile der ‚Betrachtung‘ in einer Zeitung nachgedruckt und drei weitere Novellen veröffentlicht werden. Diese hat er selbst mit dem „Hungerkünstler“ zusammengefügt und dem Verlag „Die Schmiede“ übergeben. Beide Anweisungen stammen außerdem aus einer Zeit, in der die selbstkritischen Tendenzen meines Freundes ihren Höhepunkt erreicht hatten. In seinem letzten Lebensjahr hat sein ganzes Dasein jedoch eine unerwartete, neue, glückliche und positive Wendung genommen, die diesen Selbsthass und Nihilismus aufhebt. Mein Entschluss, den Nachlass zu veröffentlichen, wird übrigens durch die Erinnerung an all die erbitterten Kämpfe erleichtert, mit denen ich jede einzelne Veröffentlichung von Kafka erzwungen und oft genug erbettelt habe. Und dennoch war er nachträglich mit diesen Veröffentlichungen versöhnt und relativ zufrieden. Schließlich entfallen bei einer posthumen Veröffentlichung einige Motive. Zum Beispiel, dass die Veröffentlichung die weitere Arbeit stören könnte oder dass sie die Schatten persönlich peinlicher Lebensphasen heraufbeschwören könnte. Wie sehr für Kafka die Nichtveröffentlichung mit dem Problem seiner Lebensführung zusammenhing (ein Problem, das zu unserem unermesslichen Schmerz jetzt nicht mehr stört), geht aus vielen Gesprächen und aus folgendem Brief an mich hervor: „… Die Romane lege ich nicht bei. Warum die alten Anstrengungen wieder aufwärmen? Nur deshalb, weil ich sie bisher nicht verbrannt habe? … Wenn ich das nächste Mal komme, geschieht es hoffentlich. Welchen Sinn hat es, solche ‚sogar‘ künstlerisch misslungenen Arbeiten aufzuheben? Den, dass man hofft, dass sich aus diesen Stücken ein Ganzes zusammensetzen wird, eine Art Berufungsinstanz, an deren Brust ich schlagen kann, wenn ich in Not bin. Ich weiß, dass das nicht möglich ist, dass von dort keine Hilfe kommt. Was soll ich also mit den Sachen? Sollen die, die mir nicht helfen konnten, als sie entstanden sind, mir jetzt helfen, wo sie fertig sind und ein eigenes, erstarrtes Leben führen? Aber ich will sie ja nicht aufheben, ich will sie verbrennen.“

Ich spüre sehr wohl, dass ein Restzweifel bleibt, der besonders feinfühlige Menschen die Veröffentlichung verbieten würde. Ich halte es aber für meine Pflicht, dieser sehr schmeichelhaften Verlockung der Feinfühligkeit zu widerstehen. Entscheidend ist dabei natürlich nichts von dem bisher Gesagten, sondern einzig und allein die Tatsache, dass Kafkas Nachlass die wundervollsten Schätze enthält – auch im Vergleich zu seinem eigenen Werk das Beste, was er geschrieben hat. Ehrlicherweise muss ich zugeben, dass diese eine Tatsache des literarischen und ethischen Werts ausgereicht hätte, um meine Entscheidung eindeutig zu bestimmen – selbst wenn ich gegen die Kraft von Kafkas letztem Willen keinen Einwand gehabt hätte.

Leider ist Franz Kafka bei einem Teil seines Vermächtnisses sein eigener Testamentsvollstrecker geworden. Ich fand in seiner Wohnung zehn große Quarthefte – nur ihre Deckel, der Inhalt war vollständig vernichtet. Außerdem hat er (zuverlässigen Berichten zufolge) mehrere Schreibblöcke verbrannt. In der Wohnung fand sich nur eine Sammlung von etwa hundert Aphorismen über religiöse Fragen, ein autobiografischer Versuch, der vorläufig unveröffentlicht bleibt, und ein Haufen ungeordneter Papiere, die ich jetzt sichte. Ich hoffe, dass sich in diesen Papieren manche vollendete oder nahezu vollendete Erzählung finden wird. Außerdem wurde mir eine (unvollendete) Tier-Novelle und ein Skizzenbuch übergeben.

Der kostbarste Teil des Vermächtnisses sind also die Werke, die dem Zorn des Autors rechtzeitig entzogen und in Sicherheit gebracht wurden. Das sind drei Romane. ‚Der Heizer‘, die bereits veröffentlichte Erzählung, bildet das erste Kapitel eines Romans, der in Amerika spielt. Von diesem existiert auch das Schlusskapitel, sodass er keine wesentliche Lücke aufweisen dürfte. Dieser Roman befindet sich bei einer Freundin des Verstorbenen. Die beiden anderen – „Das Schloss“ und „Der Prozess“ – habe ich 1920 und 1923 zu mir genommen, was mir heute ein wahrer Trost ist. Erst diese Werke werden zeigen, dass die eigentliche Bedeutung Franz Kafkas in der großen epischen Form liegt. Bisher konnte man ihn mit einigem Recht für einen Spezialisten, einen Meister der Kleinkunst halten.

Mit diesen Werken, die etwa vier Bände einer Nachlassausgabe füllen dürften, sind die Ausstrahlungen von Kafkas zauberhafter Persönlichkeit aber bei weitem nicht erschöpft. Auch wenn an eine Herausgabe der Briefe vorläufig nicht zu denken ist – jeder einzelne besitzt dieselbe Natürlichkeit und Intensität wie Kafkas literarisches Werk – so wird man doch in einem kleinen Kreis rechtzeitig damit beginnen, alles zu sammeln, was als Äußerung dieses einzigartigen Menschen in Erinnerung geblieben ist. Um nur ein Beispiel zu nennen: Wie viele der Werke, die ich jetzt zu meiner bitteren Enttäuschung in Kafkas Wohnung nicht mehr gefunden habe, hat mir mein Freund vorgelesen oder zumindest teilweise vorgelesen und teilweise ihren Plan erzählt! Wie unvergessliche, originelle und tiefe Gedanken hat er mir mitgeteilt! Soweit mein Gedächtnis und meine Kräfte reichen, soll nichts verloren gehen.

Das Manuskript des Romans „Der Prozess“ habe ich im Juni 1920 an mich genommen und gleich damals geordnet. Das Manuskript trägt keinen Titel. Doch Kafka hat dem Roman im Gespräch stets den Titel „Der Prozess“ gegeben. Die Einteilung in Kapitel sowie die Kapitelüberschriften stammen von Kafka. Bei der Anordnung der Kapitel war ich auf mein Gefühl angewiesen. Da mir mein Freund aber einen großen Teil des Romans vorgelesen hatte, konnte sich mein Gefühl bei der Ordnung der Papiere auf Erinnerungen stützen. Franz Kafka hat den Roman als unvollendet betrachtet. Vor dem Schlusskapitel, das vorhanden ist, sollten noch einige Phasen des geheimnisvollen Prozesses geschildert werden. Da der Prozess aber nach der mündlichen Äußerung des Dichters niemals bis zur höchsten Instanz vordringen sollte, war der Roman in einem gewissen Sinne überhaupt unvollendbar, das heißt, er hätte unendlich fortgesetzt werden können. Die vollendeten Kapitel, zusammen mit dem abrundenden Schlusskapitel, lassen jedenfalls sowohl den Sinn als auch die Gestalt des Werkes sehr klar hervortreten. Wer nicht darauf hingewiesen wird, dass der Dichter selbst an dem Werk noch weiterarbeiten wollte (er unterließ es, weil er sich einer anderen Lebensatmosphäre zuwandte), wird kaum eine Lücke spüren. Meine Arbeit an dem großen Papierbündel, das dieser Roman seinerzeit darstellte, beschränkte sich darauf, die vollendeten von den unvollendeten Kapiteln zu trennen. Die unvollendeten hebe ich für den Schlussband der Nachlassausgabe auf; sie enthalten nichts Wesentliches für den Handlungsverlauf. Eines dieser Fragmente wurde vom Dichter selbst unter dem Titel „Ein Traum“ in den Band „Ein Landarzt“ aufgenommen. Die vollendeten Kapitel sind hier zusammengefügt und geordnet. Von den unvollendeten habe ich nur eines, das offenbar nahezu vollendet ist, mit einer leichten Umstellung von vier Zeilen als Kapitel 8 hier eingefügt. Im Text habe ich selbstverständlich nichts geändert. Ich habe nur die offensichtlichen Schreibfehler korrigiert und die Zeichensetzung nach meinem Gefühl ergänzt, wo sie fehlte.

Max Brod.`,
}