export const chapter_2 = {
	name: 'ZWEITES KAPITEL',
	header: 'Erste untersuchung',
	text: `K. war telefonisch benachrichtigt worden, dass am nächsten Sonntag eine kleine Untersuchung in seiner Angelegenheit stattfinden würde. Man machte ihn darauf aufmerksam, dass diese Untersuchungen nun regelmäßig, wenn auch vielleicht nicht jede Woche, so doch häufiger aufeinanderfolgen würden. Es liege einerseits im allgemeinen Interesse, den Prozess rasch zu Ende zu führen, andererseits aber müssten die Untersuchungen in jeder Hinsicht gründlich sein und doch wegen der damit verbundenen Anstrengung niemals allzu lange dauern. Deshalb habe man diese Methode der schnell aufeinanderfolgenden, aber kurzen Untersuchungen gewählt. Die Bestimmung des Sonntags als Untersuchungstag habe man deshalb vorgenommen, um K. in seiner beruflichen Arbeit nicht zu stören. Man setze voraus, dass er damit einverstanden sei, wollte er einen anderen Termin wünschen, so würde man ihm, so gut wie möglich, entgegenkommen. Die Untersuchungen wären beispielsweise auch in der Nacht möglich, aber da wäre K. wohl nicht frisch genug. Jedenfalls werde man es, solange K. nichts einwende, beim Sonntag belassen. Es sei selbstverständlich, dass er bestimmt erscheinen müsse, darauf müsse man ihn wohl nicht erst aufmerksam machen. Es wurde ihm die Nummer des Hauses genannt, in dem er sich einfinden solle, es war ein Haus in einer entlegenen Vorstadtstraße, in der K. noch niemals gewesen war.

K. hängte, als er diese Meldung erhalten hatte, ohne zu antworten, den Hörer auf; er war gleich entschlossen, am Sonntag hinzugehen, es war gewiss notwendig, der Prozess kam in Gang und er musste sich dem entgegenstellen, diese erste Untersuchung sollte auch die letzte sein. Er stand noch nachdenklich beim Apparat, da hörte er hinter sich die Stimme des Direktor-Stellvertreters, der telefonieren wollte, dem K. aber den Weg versperrte. „Schlechte Nachrichten?“ fragte der Direktor-Stellvertreter beiläufig, nicht um etwas zu erfahren, sondern um K. vom Apparat wegzubringen. „Nein, nein,“ sagte K., trat beiseite, ging aber nicht weg. Der Direktor-Stellvertreter nahm den Hörer und sagte, während er auf die Telefonverbindung wartete, über den Hörer hinweg: „Eine Frage, Herr K.? Möchten Sie mir am Sonntag früh das Vergnügen machen, einen Ausflug auf meinem Segelboot mitzumachen. Es wird eine größere Gesellschaft sein, gewiss auch Ihre Bekannten darunter. Unter anderem Staatsanwalt Hesterer. Wollen Sie kommen? Kommen Sie doch!“ K. versuchte, darauf zu achten, was der Direktor-Stellvertreter sagte. Es war nicht unwichtig für ihn, denn diese Einladung des Direktor-Stellvertreters, mit dem er sich niemals sehr gut verstanden hatte, bedeutete einen Versöhnungsversuch von dessen Seite und zeigte, wie wichtig K. in der Bank geworden war und wie wertvoll seine Freundschaft oder zumindest seine Neutralität dem zweithöchsten Beamten der Bank erschien. Diese Einladung war eine Demütigung des Direktor-Stellvertreters, auch wenn sie nur in Erwartung der Telefonverbindung über den Hörer hinweg gesagt wurde. Aber K. musste ihn ein zweites Mal demütigen, er sagte: „Vielen Dank! Aber ich habe leider am Sonntag keine Zeit, ich habe schon eine Verpflichtung.“ „Schade,“ sagte der Direktor-Stellvertreter und wandte sich dem Telefongespräch zu, das gerade hergestellt worden war. Es war kein kurzes Gespräch, aber K. blieb in seiner Zerstreutheit die ganze Zeit über...

Am Sonntag war trübes Wetter. K. war sehr müde, da er wegen eines Stammtischtreffens bis spät in die Nacht im Gasthaus geblieben war, er hätte fast verschlafen. Eilig, ohne Zeit zu haben, nachzudenken und die verschiedenen Pläne, die er während der Woche ausgedacht hatte, zusammenzustellen, kleidete er sich an und lief, ohne zu frühstücken, in die ihm genannte Vorstadt. Seltsamerweise traf er, obwohl er wenig Zeit hatte umherzublicken, die drei in seine Angelegenheit verwickelten Beamten, Rabensteiner, Kullich und Kaminer. Die ersten beiden fuhren in einer Straßenbahn quer über K.s Weg, Kaminer aber saß auf der Terrasse eines Cafés und beugte sich gerade, als K. vorbeikam, neugierig über die Brüstung. Alle sahen ihm wohl nach und wunderten sich, wie ihr Vorgesetzter lief; es war eine Art Trotz, der K. davon abgehalten hatte, zu fahren, er verabscheute jede, selbst die geringste fremde Hilfe in dieser seiner Sache, auch wollte er niemanden in Anspruch nehmen und dadurch auch nur im Entferntesten einweihen, schließlich hatte er aber auch nicht die geringste Lust, sich durch übermäßige Pünktlichkeit vor der Untersuchungskommission zu erniedrigen. Allerdings lief er jetzt, um nur möglichst um 9 Uhr einzutreffen, obwohl er nicht einmal für eine bestimmte Stunde bestellt war.

Er hatte gedacht, das Haus schon von Weitem an irgendeinem Zeichen, das er sich selbst nicht genau vorgestellt hatte, oder an einer besonderen Bewegung vor dem Eingang zu erkennen. Aber die Juliusstraße, in der es sein sollte und an deren Beginn K. einen Augenblick stehen blieb, enthielt auf beiden Seiten fast ganz einförmige Häuser, hohe graue Mietshäuser, die von armen Leuten bewohnt wurden. Jetzt am Sonntagmorgen waren die meisten Fenster besetzt, Männer in Hemdsärmeln lehnten dort und rauchten oder hielten kleine Kinder vorsichtig und zärtlich an den Fensterrand. Andere Fenster waren hoch mit Bettwäsche gefüllt, über der flüchtig der zerzauste Kopf einer Frau erschien. Man rief sich über die Straße zu, ein solcher Zuruf verursachte gerade über K. ein großes Gelächter. In regelmäßigen Abständen befanden sich in der langen Straße kleine, unter dem Straßenniveau liegende, durch ein paar Treppen erreichbare Läden mit verschiedenen Lebensmitteln. Dort gingen Frauen ein und aus oder standen auf den Stufen und unterhielten sich. Ein Obsthändler, der seine Waren zu den Fenstern hinauf anpries, hätte, ebenso unaufmerksam wie K., mit seinem Karren diesen fast umgeworfen. Gerade begann ein in besseren Stadtvierteln ausgedientes Grammophon schrecklich zu spielen.

K. ging tiefer in die Straße hinein, langsam, als hätte er nun schon Zeit oder als sähe ihn der Untersuchungsrichter aus irgendeinem Fenster und wüsste also, dass sich K. eingefunden habe. Es war kurz nach 9 Uhr. Das Haus lag ziemlich weit, es war fast ungewöhnlich groß, besonders die Toreinfahrt war hoch und breit. Sie war offenbar für Lastwagen bestimmt, die zu den verschiedenen Lagerhäusern gehörten, die jetzt verschlossen den großen Hof umgaben und Aufschriften von Firmen trugen, von denen K. einige aus dem Bankgeschäft kannte. Gegen seine sonstige Gewohnheit, sich mit all diesen Äußerlichkeiten genauer zu befassen, blieb er auch ein wenig am Eingang des Hofes stehen. In seiner Nähe auf einer Kiste saß ein barfüßiger Mann und las eine Zeitung. Auf einem Handkarren schaukelten zwei Jungen. Vor einer Pumpe stand ein schwächliches junges Mädchen in einem Nachthemd und blickte, während das Wasser in ihre Kanne strömte, auf K. hin. In einer Ecke des Hofes war zwischen zwei Fenstern eine Leine gespannt, auf der die zum Trocknen bestimmte Wäsche schon hing. Ein Mann stand unten und leitete die Arbeit durch ein paar Zurufe.

K. wandte sich der Treppe zu, um zum Untersuchungszimmer zu kommen, blieb dann aber wieder stehen, denn außer dieser Treppe sah er im Hof noch drei verschiedene Treppenhäuser und überdies schien ein kleiner Durchgang am Ende des Hofes noch in einen zweiten Hof zu führen. Er ärgerte sich, dass man ihm die Lage des Zimmers nicht genauer beschrieben hatte, es war doch eine seltsame Nachlässigkeit oder Gleichgültigkeit, mit der man ihn behandelte, er beabsichtigte, das sehr laut und deutlich festzustellen. Schließlich stieg er doch die erste Treppe hinauf und spielte in Gedanken mit einer Erinnerung an die Äußerung des Wächters Willem, dass das Gericht von der Schuld angezogen werde, woraus eigentlich folgte, dass das Untersuchungszimmer an der Treppe liegen musste, die K. zufällig wählte.

Er störte beim Hinaufgehen viele Kinder, die auf der Treppe spielten und ihn, wenn er durch ihre Reihe schritt, böse ansahen. „Wenn ich das nächste Mal wieder herkommen sollte,“ sagte er sich, „muss ich entweder Süßigkeiten mitnehmen, um sie für mich zu gewinnen, oder einen Stock, um sie zu schlagen.“ Knapp vor dem ersten Stockwerk musste er sogar einen Moment warten, bis eine Murmel ihren Weg beendet hatte, zwei kleine Jungen mit den verschlagenen Gesichtern erwachsener Gauner hielten ihn unterdessen an den Hosenbeinen fest; hätte er sie abschütteln wollen, hätte er ihnen wehtun müssen und er fürchtete ihr Geschrei.

Im ersten Stockwerk begann die eigentliche Suche. Da er ja nicht nach der Untersuchungskommission fragen konnte, erfand er einen Tischler Lanz – der Name fiel ihm ein, weil der Hauptmann, der Neffe von Frau Grubach, so hieß – und wollte nun in allen Wohnungen nachfragen, ob hier ein Tischler Lanz wohne, um so die Möglichkeit zu bekommen, in die Zimmer hineinzusehen. Es zeigte sich aber, dass das meistens ohne Weiteres möglich war, denn fast alle Türen standen offen und die Kinder liefen ein und aus. Es waren in der Regel kleine, einfenstrige Zimmer, in denen auch gekocht wurde. Manche Frauen hielten Säuglinge im Arm und arbeiteten mit der freien Hand am Herd. Halbwüchsige, scheinbar nur mit Schürzen bekleidete Mädchen liefen am fleißigsten hin und her. In allen Zimmern waren die Betten noch in Gebrauch, es lagen dort Kranke oder noch Schlafende oder Leute, die sich dort in Kleidern ausstreckten. An den Wohnungen, deren Türen geschlossen waren, klopfte K. an und fragte, ob hier ein Tischler Lanz wohne. Meistens öffnete eine Frau, hörte die Frage an und wandte sich ins Zimmer zu jemandem, der sich aus dem Bett erhob. „Der Herr fragt, ob ein Tischler Lanz hier wohnt.“ „Tischler Lanz?“ fragte der aus dem Bett. „Ja,“ sagte K., obwohl sich hier die Untersuchungskommission zweifellos nicht befand und daher seine Aufgabe beendet war. Viele glaubten, es liege K. sehr viel daran, den Tischler Lanz zu finden, dachten lange nach, nannten einen Tischler, der aber nicht Lanz hieß, oder einen Namen, der mit Lanz eine ganz entfernte Ähnlichkeit hatte, oder sie fragten bei Nachbarn oder begleiteten K. zu einer weit entfernten Tür, wo ihrer Meinung nach ein derartiger Mann möglicherweise in Untermiete wohne oder wo jemand sei, der bessere Auskunft als sie selbst geben könne. Schließlich musste K. kaum mehr selbst fragen, sondern wurde auf diese Weise durch die Stockwerke gezogen. Er bedauerte seinen Plan, der ihm zuerst so praktisch erschienen war. Vor dem fünften Stock...

K. glaubte, in eine Versammlung einzutreten. Ein Gedränge der verschiedensten Leute – niemand kümmerte sich um den Eintretenden – füllte ein mittelgroßes, zweifenstriges Zimmer, das knapp unter der Decke von einer Galerie umgeben war, die ebenfalls vollständig besetzt war und wo die Leute nur gebückt stehen konnten und mit Kopf und Rücken an die Decke stießen. K., dem die Luft zu stickig war, trat wieder hinaus und sagte zu der jungen Frau, die ihn wahrscheinlich falsch verstanden hatte: „Ich habe nach einem Tischler, einem gewissen Lanz gefragt.“ „Ja,“ sagte die Frau, „gehen Sie bitte hinein.“ K. wäre ihr vielleicht nicht gefolgt, wenn die Frau nicht auf ihn zugegangen wäre, die Türklinke ergriffen und gesagt hätte: „Nach Ihnen muss ich schließen, es darf niemand mehr hinein.“ „Sehr vernünftig,“ sagte K., „aber es ist schon jetzt zu voll.“ Dann ging er aber doch wieder hinein.

Zwischen zwei Männern hindurch, die sich unmittelbar bei der Tür unterhielten – der eine machte mit beiden weit ausgestreckten Händen die Bewegung des Geldzählens, der andere sah ihm scharf in die Augen – griff eine Hand nach K. Es war ein kleiner, rotwangiger Junge. „Kommen Sie, kommen Sie,“ sagte er. K. ließ sich von ihm führen, es zeigte sich, dass in dem chaotischen Gedränge doch ein schmaler Weg frei war, der möglicherweise zwei Parteien trennte; dafür sprach auch, dass K. in den ersten Reihen rechts und links kaum ein ihm zugewandtes Gesicht sah, sondern nur die Rücken von Leuten, die ihre Reden und Bewegungen nur an Leute ihrer Partei richteten. Die meisten waren schwarz angezogen, in alten, langen und lose herabhängenden Sonntagsanzügen. Nur diese Kleidung irritierte K., sonst hätte er das Ganze für eine politische Versammlung gehalten.

Am anderen Ende des Saales, zu dem K. geführt wurde, stand auf einem sehr niedrigen, ebenfalls überfüllten Podest ein kleiner Tisch, der quer aufgestellt war, und hinter ihm, nahe am Rand des Podests, saß ein kleiner, dicker, keuchender Mann, der sich gerade mit einem hinter ihm Stehenden – dieser hatte den Ellbogen auf die Sessellehne gestützt und die Beine gekreuzt – unter großem Gelächter unterhielt. Manchmal warf er den Arm in die Luft, als karikiere er jemanden. Der Junge, der K. führte, hatte Mühe, seine Meldung zu machen. Zweimal hatte er schon auf den Zehenspitzen stehend etwas auszurichten versucht, ohne von dem Mann oben beachtet worden zu sein. Erst als einer der Leute oben auf dem Podest auf den Jungen aufmerksam machte, wandte sich der Mann ihm zu und hörte herabgebeugt seinen leisen Bericht an. Dann zog er seine Uhr und sah schnell zu K. hin. „Sie hätten vor einer Stunde und fünf Minuten erscheinen sollen,“ sagte er. K. wollte etwas antworten, aber er hatte keine Zeit, denn kaum hatte der Mann ausgesprochen, erhob sich in der rechten Saalhälfte ein allgemeines Murren. „Sie hätten vor einer Stunde und fünf Minuten erscheinen sollen,“ wiederholte nun der Mann mit erhobener Stimme und sah nun auch schnell in den Saal hinunter. Sofort wurde auch das Murren stärker und legte sich, da der Mann nichts mehr sagte, nur allmählich. Es war jetzt im Saal viel stiller als bei K.s Eintritt. Nur die Leute auf der Galerie hörten nicht auf, ihre Bemerkungen zu machen. Sie schienen, soweit man oben im Halbdunkel, Dunst und Staub etwas unterscheiden konnte, schlechter angezogen zu sein als die unten. Manche hatten Kissen mitgebracht, die sie zwischen den Kopf und die Zimmerdecke gelegt hatten, um sich nicht den Kopf zu stoßen.

K. hatte sich entschlossen, mehr zu beobachten als zu reden, infolgedessen verzichtete er auf die Verteidigung wegen seines angeblichen Zuspätkommens und sagte nur: „Mag ich zu spät gekommen sein, jetzt bin ich hier.“ Beifall, wieder aus der rechten Saalhälfte, folgte. „Leicht zu gewinnende Leute,“ dachte K. und war nur gestört durch die Stille in der linken Saalhälfte, die gerade hinter ihm lag und aus der sich nur ganz vereinzeltes Händeklatschen erhoben hatte. Er dachte nach, was er sagen könnte, um alle auf einmal oder, wenn das nicht möglich sein sollte, zumindest zeitweilig auch die anderen zu gewinnen.

„Ja,“ sagte der Mann, „aber ich bin nicht mehr verpflichtet, Sie jetzt zu verhören“ – wieder das Murren, diesmal aber missverständlich, denn der Mann fuhr fort, indem er den Leuten mit der Hand abwinkte – „ich will es jedoch ausnahmsweise heute noch tun. Eine solche Verspätung darf sich aber nicht mehr wiederholen. Und nun treten Sie vor!“ Irgendjemand sprang vom Podest herunter, so dass für K. ein Platz frei wurde, auf den er hinaufstieg. Er stand eng an den Tisch gedrückt, das Gedränge hinter ihm war so groß, dass er ihm Widerstand leisten musste, wenn er nicht den Tisch des Untersuchungsrichters und vielleicht auch diesen selbst vom Podest stoßen wollte.

Der Untersuchungsrichter kümmerte sich aber nicht darum, sondern saß bequem genug auf seinem Sessel und griff, nachdem er dem Mann hinter ihm ein abschließendes Wort gesagt hatte, nach einem kleinen Notizbuch, dem einzigen Gegenstand auf seinem Tisch. Es war wie ein Schulheft, alt, durch vieles Blättern ganz aus der Form geraten. „Also,“ sagte der Untersuchungsrichter, blätterte in dem Heft und wandte sich im Ton einer Feststellung an K., „Sie sind Maler?“ „Nein,“ sagte K. „sondern Prokurist einer großen Bank.“ Dieser Antwort folgte bei der rechten Partei ein Gelächter, das so herzlich war, dass K. mitlachen musste. Die Leute stützten sich mit den Händen auf ihre Knie und schüttelten sich vor Lachen. Es lachten sogar einzelne auf der Galerie. Der wütend gewordene Untersuchungsrichter, der wahrscheinlich gegen die Leute unten machtlos war, versuchte, es der Galerie heimzuzahlen, sprang auf, drohte der Galerie, und seine sonst wenig auffallenden Augenbrauen zogen sich buschig, schwarz und groß über seinen Augen zusammen.

Die linke Saalhälfte war aber noch immer still, die Leute standen dort in Reihen, hatten ihre Gesichter dem Podest zugewandt und hörten den Worten, die oben gewechselt wurden, ebenso ruhig zu wie dem Lärm der anderen Partei, sie duldeten sogar, dass einzelne aus ihren Reihen mit der anderen Partei hie und da gemeinsam agierten. Die Leute der linken Partei, die übrigens weniger zahlreich war, mochten im Grunde ebenso unbedeutend sein wie die der rechten Partei, aber die Ruhe ihres Verhaltens ließ sie bedeutungsvoller erscheinen. Als K. jetzt zu reden begann, war er überzeugt, in ihrem Sinne zu sprechen.

„Ihre Frage, Herr Untersuchungsrichter, ob ich Maler bin – vielmehr, Sie haben gar nicht gefragt, sondern es mir direkt unterstellt – ist bezeichnend für die ganze Art des Verfahrens, das gegen mich geführt wird. Sie können einwenden, dass es ja überhaupt kein Verfahren ist, und da haben Sie völlig Recht, denn es ist ja nur ein Verfahren, wenn ich es als solches anerkenne. Aber ich erkenne es also für den Augenblick an, gewissermaßen aus Mitleid. Man kann sich nicht anders als mitleidig dazu verhalten, wenn man es überhaupt beachten will. Ich sage nicht, dass es ein unordentliches Verfahren ist, aber ich möchte Ihnen diese Bezeichnung zur Selbsterkenntnis angeboten haben.“

K. unterbrach sich und sah in den Saal hinunter. Was er gesagt hatte, war scharf, schärfer als er es beabsichtigt hatte, aber doch richtig. Es hätte hier oder dort Beifall verdient, aber es war alles still, man wartete offenbar gespannt auf das Folgende, es bereitete sich vielleicht in der Stille ein Ausbruch vor, der allem ein Ende machen würde. Störend war, dass sich jetzt die Tür am Ende des Saales öffnete, die junge Wäscherin, die ihre Arbeit wahrscheinlich beendet hatte, eintrat und trotz aller Vorsicht, die sie anwandte, einige Blicke auf sich zog. Nur der Untersuchungsrichter machte K. unmittelbare Freude, denn er schien von den Worten sofort getroffen zu sein. Er hatte bisher stehend zugehört, denn er war von K.s Ansprache überrascht worden, während er sich zur Galerie aufgerichtet hatte. Jetzt in der Pause setzte er sich allmählich, als sollte es nicht bemerkt werden. Wahrscheinlich, um seine Miene zu beruhigen, nahm er wieder das Notizbuch vor.

„Es hilft nichts,“ fuhr K. fort, „auch Ihr Notizbuch, Herr Untersuchungsrichter, bestätigt, was ich sage.“ Zufrieden damit, nur seine ruhigen Worte in der fremden Versammlung zu hören, wagte es K. sogar, kurzerhand das Notizbuch dem Untersuchungsrichter wegzunehmen und es mit den Fingerspitzen, als scheue er sich davor, an einem mittleren Blatt hochzuheben, so dass beiderseits die eng beschriebenen, fleckigen, gelbrandigen Blätter hinunterhingen. „Das sind die Akten des Untersuchungsrichters,“ sagte er und ließ das Notizbuch auf den Tisch fallen. „Lesen Sie darin ruhig weiter, Herr Untersuchungsrichter, vor diesem Schuldenbuch fürchte ich mich wahrhaftig nicht, obwohl es mir unzugänglich ist, denn ich kann es nur mit zwei Fingerspitzen anfassen und nicht in die Hand nehmen.“ Es konnte nur ein Zeichen tiefer Demütigung sein oder es musste zumindest so aufgefasst werden, dass der Untersuchungsrichter nach dem Notizbuch, wie es auf den Tisch gefallen war, griff, es ein wenig zu ordnen versuchte und es wieder vornahm, um darin zu lesen.

Die Gesichter der Leute in der ersten Reihe waren so gespannt auf K. gerichtet, dass er einen Moment lang zu ihnen hinuntersah. Es waren durchweg ältere Männer, einige waren weißbärtig. Waren vielleicht sie die Entscheidenden, die die ganze Versammlung beeinflussen konnten, die sich auch durch die Demütigung des Untersuchungsrichters nicht aus der Regungslosigkeit bringen ließ, in die sie seit K.s Rede versunken war.

„Was mir geschehen ist,“ fuhr K. fort, etwas leiser als früher, und suchte immer wieder die Gesichter der ersten Reihe ab, was seiner Rede einen etwas unruhigen Ausdruck gab, „was mir geschehen ist, ist ja nur ein einzelner Fall und als solcher nicht sehr wichtig, da ich es nicht sehr schwer nehme, aber es ist das Zeichen eines Verfahrens, wie es bei vielen angewendet wird. Für diese stehe ich hier ein, nicht für mich.“

Er hatte unwillkürlich seine Stimme erhoben. Irgendwo klatschte jemand mit erhobenen Händen und rief: „Bravo! Warum denn nicht? Bravo! Und wieder Bravo!“ Die in der ersten Reihe griffen hie und da in ihre Bärte, keiner kümmerte sich um den Ausruf. Auch K. maß ihm keine Bedeutung bei, war aber doch ermutigt; er hielt es jetzt gar nicht mehr für nötig, dass alle Beifall klatschten, es genügte, wenn die Allgemeinheit über die Sache nachzudenken begann und nur manchmal einer durch Überzeugung gewonnen wurde.

„Ich will keinen rednerischen Erfolg,“ sagte K. aus dieser Überlegung heraus, „er dürfte mir auch nicht erreichbar sein. Der Herr Untersuchungsrichter spricht wahrscheinlich viel besser, es gehört ja zu seinem Beruf. Was ich will, ist nur die öffentliche Besprechung eines öffentlichen Missstandes. Hören Sie: Ich bin vor etwa zehn Tagen verhaftet worden, über die Tatsache der Verhaftung selbst lache ich, aber das gehört jetzt nicht hierher. Ich wurde früh im Bett überrascht, vielleicht hatte man – es ist nach dem, was der Untersuchungsrichter sagte, nicht ausgeschlossen – den Befehl, irgendeinen Maler, der ebenso unschuldig ist wie ich, zu verhaften, aber man wählte mich. Das Nebenzimmer war von zwei groben Wächtern besetzt. Wenn ich ein gefährlicher Räuber wäre, hätte man keine besseren Vorkehrungen treffen können. Diese Wächter waren überdies demoralisiertes Pack, sie redeten ununterbrochen auf mich ein, sie wollten sich bestechen lassen, sie wollten mir unter Vorwänden Wäsche und Kleider herauslocken, sie wollten Geld, um mir angeblich ein Frühstück zu bringen, nachdem sie mein eigenes Frühstück vor meinen Augen schamlos aufgegessen hatten. Nicht genug damit. Ich wurde in ein drittes Zimmer vor den Aufseher geführt. Es war das Zimmer einer Dame, die ich sehr schätze, und ich musste zusehen, wie dieses Zimmer meinetwegen, aber ohne meine Schuld durch die Anwesenheit der Wächter und des Aufsehers gewissermaßen verunreinigt wurde. Es war nicht leicht, ruhig zu bleiben. Es gelang mir aber, und ich fragte den Aufseher vollständig ruhig – wenn er hier wäre, müsste er es bestätigen – warum ich verhaftet sei. Was antwortete nun dieser Aufseher, den ich jetzt noch vor mir sehe, wie er auf dem Sessel der erwähnten Dame als ein Ausdruck stumpfsinnigster Arroganz sitzt? Meine Herren, er antwortete im Grunde nichts, vielleicht wusste er wirklich nichts, er hatte mich verhaftet und war damit zufrieden. Er hat sogar noch mehr getan und in das Zimmer jener Dame drei nie...

Als K. sich hier unterbrach und zum stillen Untersuchungsrichter hinsah, glaubte er zu bemerken, dass dieser gerade mit einem Blick jemandem in der Menge ein Zeichen gab. K. lächelte und sagte: „Gerade gibt hier neben mir der Herr Untersuchungsrichter jemandem von Ihnen ein geheimes Zeichen. Es sind also Leute unter Ihnen, die von hier oben gesteuert werden. Ich weiß nicht, ob das Zeichen jetzt Zischen oder Beifall bewirken sollte, und verzichte dadurch, dass ich die Sache vorzeitig verrate, ganz bewusst darauf, die Bedeutung des Zeichens zu erfahren. Es ist mir vollständig gleichgültig, und ich ermächtige den Herrn Untersuchungsrichter öffentlich, seine bezahlten Angestellten dort unten statt mit geheimen Zeichen laut mit Worten zu befehligen, indem er etwa einmal sagt: Jetzt zischt, und das nächste Mal: Jetzt klatscht.“

In Verlegenheit oder Ungeduld rückte der Untersuchungsrichter auf seinem Sessel hin und her. Der Mann hinter ihm, mit dem er sich schon früher unterhalten hatte, beugte sich wieder zu ihm, sei es, um ihm im Allgemeinen Mut zuzusprechen oder um ihm einen besonderen Rat zu geben. Unten unterhielten sich die Leute leise, aber lebhaft. Die zwei Parteien, die früher so entgegengesetzte Meinungen gehabt zu haben schienen, vermischten sich, einzelne Leute zeigten mit dem Finger auf K., andere auf den Untersuchungsrichter. Der neblige Dunst im Zimmer war äußerst lästig, er verhinderte sogar eine genauere Beobachtung der weiter Entfernten. Besonders für die Galeriebesucher musste er störend sein, sie waren gezwungen, allerdings unter scheuen Seitenblicken zum Untersuchungsrichter, leise Fragen an die Versammlungsteilnehmer zu stellen, um sich genauer zu informieren. Die Antworten wurden im Schutz der vorgehaltenen Hände ebenso leise gegeben.

„Ich bin gleich fertig,“ sagte K. und schlug, da keine Glocke vorhanden war, mit der Faust auf den Tisch. Im Schrecken darüber fuhren die Köpfe des Untersuchungsrichters und seines Ratgebers augenblicklich auseinander: „Mir steht die ganze Sache fern, ich beurteile sie daher ruhig, und Sie können, vorausgesetzt, dass Ihnen an diesem angeblichen Gericht etwas gelegen ist, großen Vorteil davon haben, wenn Sie mir zuhören. Ihre gegenseitigen Besprechungen dessen, was ich vorbringe, bitte ich Sie, auf später zu verschieben, denn ich habe keine Zeit und werde bald gehen.“

Sofort war es still, so sehr beherrschte K. die Versammlung bereits. Man schrie nicht mehr durcheinander wie am Anfang, man klatschte nicht einmal mehr Beifall, aber man schien schon überzeugt oder auf dem besten Wege dazu.

„Es besteht kein Zweifel,“ sagte K. sehr leise, denn ihn freute das angespannte Lauschen der ganzen Versammlung, in dieser Stille entstand ein Sausen, das aufregender war als der ekstatischste Beifall, „es besteht kein Zweifel, dass hinter allen Äußerungen dieses Gerichts, in meinem Fall also hinter der Verhaftung und der heutigen Untersuchung, eine große Organisation steckt. Eine Organisation, die nicht nur bestechliche Wächter, alberne Aufseher und Untersuchungsrichter, die im günstigsten Fall bescheiden sind, beschäftigt, sondern die weiterhin jedenfalls eine Richterschaft hoher und höchster Instanz unterhält, mit dem zahllosen, unumgänglichen Gefolge von Dienern, Schreibern, Gendarmen und anderen Hilfskräften, vielleicht sogar Henkern, ich scheue vor dem Wort nicht zurück. Und der Sinn dieser großen Organisation, meine Herren? Er besteht darin, dass unschuldige Personen verhaftet werden und gegen sie ein sinnloses und meistens, wie in meinem Fall, ergebnisloses Verfahren eingeleitet wird. Wie ließe sich bei dieser Sinnlosigkeit des Ganzen die schlimmste Korruption der Beamtenschaft vertuschen? Das ist unmöglich, das brächte auch der höchste Richter nicht einmal für sich selbst zustande. Darum versuchen die Wächter, den Verhafteten die Kleider vom Leib zu stehlen, darum brechen Aufseher in fremde Wohnungen ein, darum sollen Unschuldige, statt verhört zu werden, lieber vor ganzen Versammlungen entwürdigt werden. Die Wächter haben nur von Lagerorten erzählt, in die man das Eigentum der Verhafteten bringt, ich wollte einmal diese Lagerorte sehen, in denen das mühsam erarbeitete Vermögen der Verhafteten verdirbt, soweit es nicht von diebischen Lagerbeamten gestohlen wird.“

K. wurde durch einen Schrei vom Ende des Saales unterbrochen, er schattete die Augen ab, um hinsehen zu können, denn das trübe Tageslicht machte den Dunst weißlich und blendete. Es handelte sich um die Wäscherin, die K. gleich bei ihrem Eintritt als eine erhebliche Störung erkannt hatte. Ob sie jetzt schuldig war oder nicht, konnte man nicht erkennen. K. sah nur, dass ein Mann sie in einen Winkel bei der Tür gezogen hatte und dort an sich drückte. Aber nicht sie schrie, sondern der Mann, er hatte den Mund weit aufgerissen und blickte zur Decke. Ein kleiner Kreis hatte sich um beide gebildet, die Galeriebesucher in der Nähe schienen darüber begeistert, dass der Ernst, den K. in die Versammlung gebracht hatte, auf diese Weise unterbrochen wurde. K. wollte unter dem ersten Eindruck gleich hinlaufen, auch dachte er, allen würde daran gelegen sein, dort Ordnung zu schaffen und zumindest das Paar aus dem Saal zu weisen, aber die ersten Reihen vor ihm blieben ganz fest, keiner rührte sich und keiner ließ K. durch. Im Gegenteil, man hinderte ihn, und irgendeine Hand – er hatte keine Zeit, sich umzudrehen – fasste ihn hinten am Kragen, alte Männer hielten den Arm vor, K. dachte nicht eigentlich mehr an das Paar, ihm war, als werde seine Freiheit eingeschränkt, als mache man mit der Verhaftung ernst, und er sprang rücksichtslos vom Podest hinunter. Nun stand er Auge in Auge dem Gedränge gegenüber. Hatte er die Leute nicht richtig beurteilt? Hatte er seiner Rede zu viel Wirkung zugetraut? Hatte man sich verstellt, solange er gesprochen hatte, und hatte man jetzt, da er zu den Schlussfolgerungen kam, die Verstellung satt? Was für Gesichter rings um ihn! Kleine, schwarze Äuglein huschten hin und her, die Wangen hingen herab wie bei Betrunkenen, die langen Bärte waren steif und schütter, und wenn man hineingriff, so war es, als bilde man bloß Krallen, nicht als griffe man an Bärte. Unter den Bärten aber – und das war die eigentliche Entdeckung, die K. machte – schimmerten am Rockkragen Abzeichen...`,
}
