export const chapter_10 = {
	name: 'Zehntes kapitel',
	header: 'ENDE',
	text: `Am Abend vor seinem 31. Geburtstag – es war gegen 21 Uhr, eine stille Zeit auf den Straßen – kamen zwei Herren in K.s Wohnung. Sie trugen lange Mäntel, waren blass und dicklich und hatten Zylinder auf, die wie festgewachsen aussahen. Nach einer kurzen, formellen Geste an der Wohnungstür wiederholte sich dasselbe in größerem Maß vor K.s Zimmer. Obwohl ihm der Besuch nicht angekündigt war, saß K., ebenfalls schwarz gekleidet, in einem Sessel nahe der Tür. Er zog langsam neue, enge Handschuhe an, als würde er Gäste erwarten. Er stand sofort auf und blickte die Herren neugierig an. „Sie sind also für mich da?“, fragte er. Die Herren nickten, und einer deutete mit seinem Zylinderhut auf den anderen. K. musste sich eingestehen, dass er einen anderen Besuch erwartet hatte. Er ging zum Fenster und schaute noch einmal auf die dunkle Straße hinaus. Fast alle Fenster auf der gegenüberliegenden Straßenseite waren ebenfalls dunkel, viele Vorhänge waren zugezogen. In einem beleuchteten Fenster spielten kleine Kinder hinter einem Gitter. Sie konnten sich noch nicht von der Stelle bewegen und versuchten, mit den Händen nacheinander zu greifen. „Man schickt mir alte, unbedeutende Schauspieler“, sagte sich K. und schaute sich um, um sich noch einmal zu vergewissern. „Man will es sich mit mir leicht machen.“ K. drehte sich plötzlich zu ihnen um und fragte: „An welchem Theater spielen Sie?“ – „Theater?“, fragte der eine Herr mit zuckenden Mundwinkeln und sah den anderen um Rat an. Der andere verhielt sich wie ein Stummer, der mit seinem Körper kämpft. „Sie sind nicht darauf vorbereitet, dass man Ihnen Fragen stellt“, sagte sich K. und holte seinen Hut.

Schon auf der Treppe wollten die Herren K. unterhaken, aber K. wehrte ab: „Erst auf der Straße, ich bin nicht krank.“ Doch direkt vor dem Haustor hakten sie sich bei ihm ein, auf eine Weise, die K. noch nie erlebt hatte. Ihre Schultern drückten sich eng an seine. Ihre Arme waren nicht angewinkelt, sondern sie umschlangen K.s Arme in voller Länge. Unten packten sie seine Hände mit einem geübten, festen Griff, dem man nicht widerstehen konnte. K. ging steif und aufrecht zwischen ihnen. Die drei bildeten eine so enge Einheit, dass, wenn man einen von ihnen niedergeschlagen hätte, alle gefallen wären. Es war eine Einheit, wie sie fast nur leblose Dinge bilden können.

Unter den Laternen versuchte K. öfter, seine Begleiter genauer anzusehen, was bei dieser Enge schwierig war. In der Dämmerung seines Zimmers war das kaum möglich gewesen. „Vielleicht sind es Tenöre“, dachte er, als er ihr schweres Doppelkinn sah. Die Sauberkeit ihrer Gesichter widerte ihn an. Man konnte sich bildlich vorstellen, wie eine Hand ihre Augenwinkel gesäubert, ihre Oberlippe gerieben und die Falten am Kinn geglättet hatte.

Als K. das bemerkte, blieb er stehen, und die anderen blieben ebenfalls stehen. Sie standen am Rand eines leeren Platzes, der mit Grünanlagen geschmückt war. „Warum hat man ausgerechnet Sie geschickt!“, rief er mehr, als dass er fragte. Die Herren wussten anscheinend keine Antwort. Sie warteten mit herabhängenden freien Armen, wie Krankenpfleger, die einem Kranken eine Pause gönnen. „Ich gehe nicht weiter“, sagte K. versuchsweise. Darauf mussten die Herren nicht antworten. Es reichte, dass sie ihren Griff nicht lockerten und versuchten, K. von der Stelle zu heben, aber K. wehrte sich. „Ich werde nicht mehr viel Kraft brauchen, aber die, die ich habe, werde ich jetzt einsetzen“, dachte er. Er dachte an Fliegen, die mit zerreißenden Beinchen vom Leimstreifen loskommen wollen. „Die Herren werden es schwer haben.“

In diesem Moment kam Fräulein Bürstner über eine kleine Treppe aus einer tiefer gelegenen Gasse auf den Platz. Es war nicht ganz sicher, ob sie es war, aber die Ähnlichkeit war groß. Aber für K. war es auch nicht wichtig, ob es wirklich Fräule-in Bürstner war. Ihm wurde sofort die Sinnlosigkeit seines Widerstands bewusst. Es war nicht heldenhaft, Widerstand zu leisten, den Herren Schwierigkeiten zu machen und zu versuchen, den letzten Schein von Leben zu genießen. Er ging weiter, und die Freude, die er den Herren damit machte, übertrug sich ein wenig auf ihn selbst. Sie ließen es nun zu, dass er die Richtung bestimmte. Er wählte den Weg, den das Fräulein vor ihnen nahm. Nicht, weil er sie einholen oder möglichst lange sehen wollte, sondern um die Mahnung, die sie für ihn darstellte, nicht zu vergessen. „Das Einzige, was ich jetzt tun kann“, sagte er sich – und der gleichmäßige Rhythmus seiner Schritte und der seiner Begleiter bestätigte seine Gedanken – „ist, bis zum Ende einen klaren und ruhigen Verstand zu bewahren. Ich wollte immer mit zwanzig Händen in die Welt greifen, und das für einen Zweck, der nicht gutzuheißen war. Das war falsch. Soll ich jetzt zeigen, dass mich nicht einmal der einjährige Prozess etwas gelehrt hat? Soll ich als begriffsstutziger Mensch gehen? Soll man von mir sagen können, dass ich am Anfang des Prozesses aufhören und an seinem Ende wieder anfangen will? Ich will nicht, dass man das sagt. Ich bin dankbar dafür, dass man mir auf diesem Weg diese halb stummen, verständnislosen Herren mitgegeben hat und dass man es mir überlassen hat, mir selbst das Nötige zu sagen.“

Das Fräulein war inzwischen in eine Seitengasse abgebogen, aber K. brauchte sie nicht mehr und überließ sich seinen Begleitern. Alle drei gingen nun in vollem Einverständnis über eine Brücke im Mondschein. Die Herren folgten jeder kleinen Bewegung von K. bereitwillig. Als er sich ein wenig zum Geländer drehte, drehten auch sie sich mit der ganzen Front dorthin. Das Wasser, das im Mondlicht glänzte und zitterte, teilte sich um eine kleine Insel. Darauf türmten sich Bäume und Sträucher wie eine dichte Masse. Unter ihnen, jetzt unsichtbar, verliefen Kieswege mit bequemen Bänken, auf denen sich K. in manchen Sommern ausgestreckt hatte. „Ich wollte gar nicht stehen bleiben“, sagte er zu seinen Begleitern, beschämt über ihre Nachgiebigkeit. Der eine schien dem anderen hinter K.s Rücken einen leisen Vorwurf wegen des missverständlichen Stehenbleibens zu machen, dann gingen sie weiter.

Sie gingen durch einige ansteigende Gassen, in denen hier und da Polizisten standen oder gingen, mal in der Ferne, mal ganz in der Nähe. Einer mit einem buschigen Schnurrbart, die Hand am Säbelgriff, trat absichtlich nahe an die verdächtige Gruppe heran. Die Herren blieben stehen, der Polizist schien schon den Mund zu öffnen, da zog K. die Herren mit aller Kraft vorwärts. Öfter drehte er sich vorsichtig um, um zu sehen, ob der Polizist ihnen folgte. Als sie aber eine Ecke zwischen sich und dem Polizisten hatten, fing K. an zu rennen. Die Herren mussten trotz Atemnot ebenfalls mitlaufen.

So kamen sie schnell aus der Stadt hinaus, die an dieser Stelle fast ohne Übergang in Felder überging. Ein kleiner, verlassener und öder Steinbruch lag in der Nähe eines Hauses, das noch ganz städtisch wirkte. Hier blieben die Herren stehen. Entweder war dieser Ort von Anfang an ihr Ziel gewesen, oder sie waren zu erschöpft, um weiterzulaufen. Jetzt ließen sie K. los, der stumm wartete. Sie nahmen ihre Zylinderhüte ab und wischten sich mit Taschentüchern den Schweiß von der Stirn, während sie sich im Steinbruch umsahen. Überall lag der Mondschein mit seiner natürlichen Ruhe, die keinem anderen Licht zu eigen ist.

Nachdem sie sich höflich darüber ausgetauscht hatten, wer die nächsten Aufgaben übernehmen sollte – die Herren schienen die Aufträge gemeinsam erhalten zu haben – ging der eine zu K. und zog ihm den Mantel, die Weste und schließlich das Hemd aus. K. fröstelte unwillkürlich, woraufhin ihm der Herr einen leichten, beruhigenden Klaps auf den Rücken gab. Dann legte er die Kleider sorgfältig zusammen, als ob man sie später noch brauchen würde, wenn auch nicht sofort. Um K. nicht einfach nur in der kühlen Nachtluft stehen zu lassen, nahm er ihn unter den Arm und ging ein wenig mit ihm auf und ab, während der andere Herr im Steinbruch nach einer passenden Stelle suchte. Als er sie gefunden hatte, winkte er, und der andere Herr führte K. dorthin. Es war nahe an der Felswand, dort lag ein abgebrochener Felsbrocken. Die Herren setzten K. auf den Boden, lehnten ihn an den Stein und betteten seinen Kopf darauf. Trotz aller Mühe, die sie sich gaben, und trotz K.s Entgegenkommen blieb seine Haltung sehr gezwungen und unnatürlich. Der eine Herr bat den anderen daher, ihm das Hinlegen von K. für einen Moment allein zu überlassen, aber auch das machte es nicht besser. Schließlich ließen sie K. in einer Haltung zurück, die nicht einmal die beste der bisher ausprobierten war. Dann öffnete der eine Herr seinen Mantel und zog aus einer Scheide an seinem Gürtel ein langes, dünnes, beidseitig geschliffenes Fleischermesser. Er hielt es hoch und prüfte die Schärfe im Licht. Wieder begannen die widerlichen Höflichkeiten. Einer reichte das Messer über K. hinweg dem anderen, dieser reichte es wieder über K. zurück. K. wusste jetzt genau, dass es seine Pflicht gewesen wäre, das Messer selbst zu nehmen und es sich in den Körper zu rammen, als es über ihm schwebte. Aber er tat es nicht, sondern drehte seinen noch freien Hals und sah sich um. Er konnte sich nicht vollständig bewähren und den Behörden alle Arbeit abnehmen. Die Verantwortung dafür lag bei dem, der ihm die letzte Kraft dafür genommen hatte.

Aber an K.s Kehle legten sich die Hände des einen Herrn, während der andere ihm das Messer ins Herz stieß und zweimal dort drehte. Mit brechenden Augen sah K. noch, wie die Herren, nahe vor seinem Gesicht, Wange an Wange gelehnt, die Entscheidung beobachteten. „Wie ein Hund!“, sagte er. Es war, als sollte die Scham ihn überleben.`,
}
