export const chapter_11 = {
	header: 'NACHWORT',
	text: `Eigenartig und tief wie alle Lebensäußerungen Franz Kafkas war auch seine Stellungnahme seinem eigenen Werk und jeder Publikation gegenüber. Die Probleme, die er bei Behandlung dieser Angelegenheit austrug und die daher auch Richtschnur jeder Veröffentlichung aus seinem Nachlaß bleiben müssen, können in ihrem Ernst gar nicht überschätzt werden. Zu ihrer wenigstens annäherungsweisen Beurteilung diene das Folgende:

Fast alles, was Kafka veröffentlicht hat, ist ihm von mir mit List und Überredungskunst abgenommen worden. Damit steht nicht im Widerspruch, daß er oftmals, in langen Lebensperioden, seines Schreibens wegen (er sprach freilich stets nur von einem „Kritzeln“) viel Glück empfunden hat. Wer ihn nur je in kleinem Kreise seine eigne Prosa mit hinreißendem Feuer, mit einem Rhythmus, dessen Lebendigkeit kein Schauspieler je erreichen wird, vorlesen hören durfte, der fühlte auch unmittelbar die echte unbändige Schaffenslust und Leidenschaft, die hinter diesem Werke stand. Daß er es trotzdem verwarf, hatte seinen Grund zunächst in gewissen traurigen Erlebnissen, die ihn zur Selbstsabotage, daher auch zum Nihilismus dem eignen Werk gegenüber führten; unabhängig davon aber auch in der Tatsache, daß er an dieses Werk (freilich ohne dies je auszusprechen) [403]den höchsten religiösen Maßstab anlegte, dem es allerdings, aus vielerlei Wirrnissen entrungen, nicht entsprechen konnte. Daß sein Werk trotzdem vielen, die zum Glauben, zur Natur, zur vollkommenen Seelengesundheit hinstreben, ein starker Helfer hätte werden können, durfte ihm nichts bedeuten, der mit dem unerbittlichsten Ernst für sich selbst auf der Suche nach dem rechten Wege war und zunächst sich selbst, nicht andern Rat zu geben hatte.

So deute ich für meine Person die negative Stellungnahme Kafkas zu seinem eignen Werk. Er sprach oft von den „falschen Händen, die sich einem während des Schreibens entgegenstrecken“ — auch davon, daß ihn das Geschriebene und gar das Veröffentlichte in der weitern Arbeit beirre. Es gab viele Widerstände zu überwinden, ehe ein Band von ihm erschien. Nichtsdestoweniger hat er an den fertigen schönen Büchern und gelegentlich auch an ihren Wirkungen eine rechte Freude gehabt, und es gab Zeiten, wo er wie sich selbst so auch sein Werk mit gleichsam wohlwollendern Blicken, nie ganz ohne Ironie, jedoch mit freundlicher Ironie musterte; mit einer Ironie, hinter der sich das ungeheure Pathos des kompromißlos nach dem Höchsten Strebenden verbarg.

In Franz Kafkas Nachlaß hat sich kein Testament vorgefunden. In seinem Schreibtisch lag unter vielem andern Papier ein zusammengefalteter, mit Tinte geschriebener Zettel mit meiner Adresse. Der Zettel hat folgenden Wortlaut:

Liebster Max, meine letzte Bitte: Alles, was sich in meinem Nachlaß (also im Buchkasten, Wäscheschrank, [404]Schreibtisch, zu Hause und im Bureau, oder wohin sonst irgend etwas vertragen worden sein sollte und Dir auffällt) an Tagebüchern, Manuskripten, Briefen, fremden und eignen, Gezeichnetem und so weiter findet, restlos und ungelesen zu verbrennen, ebenso alles Geschriebene oder Gezeichnete, das Du oder andre, die Du in meinem Namen darum bitten sollst, haben. Briefe, die man Dir nicht übergeben will, soll man wenigstens selbst zu verbrennen sich verpflichten.

Dein Franz Kafka.


Bei genauerm Suchen fand sich auch noch ein mit Bleistift geschriebenes, vergilbtes, offenbar älteres Blatt. Es sagt:

Lieber Max, vielleicht stehe ich diesmal doch nicht mehr auf, das Kommen der Lungenentzündung ist nach dem Monat Lungenfieber genug wahrscheinlich, und nicht einmal, daß ich es niederschreibe, wird sie abwehren, trotzdem es eine gewisse Macht hat.

Für diesen Fall also mein letzter Wille hinsichtlich alles von mir Geschriebenen:

Von allem, was ich geschrieben habe, gelten nur die Bücher: Urteil, Heizer, Verwandlung, Strafkolonie, Landarzt und die Erzählung: Hungerkünstler. (Die paar Exemplare der ‚Betrachtung‘ mögen bleiben, ich will niemandem die Mühe des Einstampfens machen, aber neu gedruckt darf nichts daraus werden.) Wenn ich sage, daß jene fünf Bücher und die Erzählung gelten, so meine ich damit nicht, daß ich den Wunsch habe, sie mögen neu gedruckt und künftigen Zeiten überliefert werden, im Gegenteil, sollten sie ganz verlorengehn, entspricht dieses [405]meinem eigentlichen Wunsch. Nur hindere ich, da sie schon einmal da sind, niemanden daran, sie zu erhalten, wenn er dazu Lust hat.

Dagegen ist alles, was sonst an Geschriebenem von mir vorliegt (in Zeitschriften Gedrucktes, im Manuskript oder in Briefen) ausnahmslos, soweit es erreichbar oder durch Bitten von den Adressaten zu erhalten ist (die meisten Adressaten kennst Du ja, in der Hauptsache handelt es sich um .….….., vergiß besonders nicht paar Hefte, die .…. hat) — alles dieses ist ausnahmslos, am liebsten ungelesen (doch wehre ich Dir nicht hineinzuschaun, am liebsten wäre es mir allerdings, wenn Du es nicht tust, jedenfalls aber darf niemand andrer hineinschauen) — alles dieses ist ausnahmslos zu verbrennen, und dies möglichst bald zu tun bitte ich Dich

Franz


Wenn ich diesen so kategorisch ausgesprochenen Verfügungen gegenüber dennoch ablehne, die herostratische Tat auszuführen, die mein Freund von mir verlangt, so habe ich hierzu die allertriftigsten Gründe.

Einige davon entziehen sich öffentlicher Diskussion. Doch auch die, welche ich mitteilen kann, sind meiner Ansicht nach durchaus hinreichend zum Verständnis meines Entschlusses.

Der Hauptgrund: als ich 1921 meinen Beruf wechselte, sagte ich meinem Freunde, daß ich mein Testament gemacht hätte, in dem ich ihn bäte, dieses und jenes zu vernichten, andres durchzusehn und so fort. Darauf sagte Kafka und zeigte mir den mit Tinte geschriebenen Zettel, den man dann in seinem Schreibtisch vorgefunden hat, von [406]außen: „Mein Testament wird ganz einfach sein — die Bitte an dich, alles zu verbrennen.“ Ich entsinne mich auch noch ganz genau der Antwort, die ich damals gab: „Falls du mir im Ernste so etwas zumuten solltest, so sage ich dir schon jetzt, daß ich deine Bitte nicht erfüllen werde.“ Das ganze Gespräch wurde in jenem scherzhaften Ton geführt, der unter uns üblich war, jedoch mit dem heimlichen Ernst, den wir dabei stets einer bei dem andern voraussetzten. Von dem Ernst meiner Ablehnung überzeugt, hätte Franz einen andern Testamentsexekutor bestimmen müssen, wenn ihm seine eigne Verfügung unbedingter und letzter Ernst gewesen wäre.

Ich bin ihm nicht dankbar, mich in diesen schweren Gewissenskonflikt gestürzt zu haben, den er voraussehen mußte, denn er kannte die fanatische Verehrung, die ich jedem seiner Worte entgegenbrachte, und die mich in den 22 Jahren unsrer niemals getrübten Freundschaft (unter anderm) veranlaßte, auch nicht das kleinste Zettelchen, keine Ansichtskarte, die von ihm kam, wegzuwerfen. — Das „ich bin nicht dankbar“ möge übrigens nicht mißverstanden werden! Was wiegt ein noch so schwerer Gewissenskonflikt gegenüber dem unendlichen Segen, den ich dem Freunde verdanke, der das eigentliche Rückgrat meiner ganzen geistigen Existenz war!

Weitere Gründe: die Ordre des Bleistiftblatts ist von Franz selbst nicht befolgt worden, denn er hat später ausdrücklich die Erlaubnis gegeben, daß Teile der ‚Betrachtung‘ in einer Zeitung nachgedruckt, und daß drei weitere Novellen veröffentlicht würden, die er selbst mit dem „Hungerkünstler“ vereinigt und dem Verlag Die Schmiede [407]übergeben hat. Beide Verfügungen stammen ferner aus einer Zeit, wo die selbstkritischen Tendenzen meines Freundes den Höhepunkt erreicht hatten. In seinem letzten Lebensjahre aber hat sein ganzes Dasein eine unvorhergesehene, neue, glückliche, positive Wendung genommen, die diesen Selbsthaß und Nihilismus derogiert. — Mein Entschluß, den Nachlaß zu veröffentlichen, wird übrigens durch die Erinnerung an all die erbitterten Kämpfe erleichtert, mit dem ich jede einzelne Veröffentlichung von Kafka erzwungen und oft genug erbettelt habe. Und dennoch war er nachträglich mit diesen Veröffentlichungen ausgesöhnt und relativ zufrieden. — Schließlich entfällt bei einer postumen Veröffentlichung eine Reihe von Motiven, zum Beispiel, daß Veröffentlichung weitere Arbeit beirren könnte, daß sie die Schatten persönlich peinlicher Lebensperioden aufrief. Wie sehr für Kafka die Nichtveröffentlichung mit dem Problem seiner Lebensführung zusammenhing (ein Problem, das zu unserem unermeßlichen Schmerz jetzt nicht mehr stört), geht wie aus vielen Gesprächen aus folgendem Brief an mich hervor: „… Die Romane lege ich nicht bei. Warum die alten Anstrengungen aufrühren? Nur deshalb, weil ich sie bisher nicht verbrannt habe? … Wenn ich nächstens komme, geschieht es hoffentlich. Worin liegt der Sinn des Aufhebens solcher „sogar“ künstlerisch mißlungener Arbeiten? Darin, daß man hofft, daß sich aus diesen Stückchen ein Ganzes zusammensetzen wird, irgendeine Berufungsinstanz, an deren Brust ich werde schlagen können, wenn ich in Not bin. Ich weiß, daß das nicht möglich ist, daß von dort keine Hilfe kommt. Was soll ich also mit den Sachen? Sollen die, die mir nicht helfen können, [408]mir auch noch schaden, wie es, dieses Wissen vorausgesetzt, sein muß?“

Ich fühle sehr wohl, daß ein Rest bleibt, der besonders zartsinnigen Menschen die Publikation verbieten würde. Ich halte es aber für meine Pflicht, dieser sehr einschmeichelnden Verlockung des Zartsinns zu widerstehn. Entscheidend ist dabei natürlich nichts von dem bisher Vorgebrachten, sondern einzig und allein die Tatsache, daß der Nachlaß Kafkas die wundervollsten Schätze, auch an seinem eignen Werk gemessen das Beste, was er geschrieben hat, enthält. Ehrlicherweise muß ich eingestehn, daß diese eine Tatsache des literarischen und ethischen Werts genügt hätte (selbst wenn ich gegen die Kraft der letztwilligen Verfügungen Kafkas gar keinen Einwand hätte) — meine Entscheidung mit einer Präzision, der ich nichts entgegenzusetzen hätte, eindeutig zu bestimmen.

Leider ist Franz Kafka an einem Teil seines Vermächtnisses sein eigner Exekutor geworden. Ich fand in seiner Wohnung zehn große Quarthefte — nur ihre Deckel, den Inhalt vollständig vernichtet. Ferner hat er (zuverlässigem Bericht zufolge) mehrere Schreibblocks verbrannt. In der Wohnung fand sich nur ein Konvolut (etwa hundert Aphorismen über religiöse Fragen), ein autobiographischer Versuch, der vorläufig unveröffentlicht bleibt, und ein Haufen ungeordneter Papiere, die ich jetzt sichte. Ich hoffe, daß sich in diesen Papieren manche vollendete oder nahezu vollendete Erzählung finden wird. Ferner wurde mir eine (unvollendete) Tier-Novelle und ein Skizzenbuch übergeben.

Der kostbarste Teil des Vermächtnisses besteht mithin in den Werken, die dem Grimm des Autors rechtzeitig entzogen [409]und in Sicherheit gebracht worden sind. Es sind dies drei Romane. ‚Der Heizer‘, die schon veröffentlichte Erzählung, bildet das erste Kapitel des einen Romans, der in Amerika spielt, und von dem auch das Schlußkapitel existiert, so daß er keine wesentliche Lücke aufweisen dürfte. Dieser Roman befindet sich bei einer Freundin des Toten; die beiden andern — „Das Schloß“ und den „Prozeß“ habe ich 1920 und 1923 zu mir gebracht, was mir heute ein wahrer Trost ist. Erst diese Werke werden zeigen, daß die eigentliche Bedeutung Franz Kafkas, den man bisher mit einigem Recht für einen Spezialisten, einen Meister der Kleinkunst halten konnte, in der großen epischen Form liegt.

Mit diesen Werken, die etwa vier Bände einer Nachlaßausgabe füllen dürften, sind aber die Ausstrahlungen von Kafkas zauberhafter Persönlichkeit bei weitem nicht erschöpft. Kann auch vorläufig an eine Herausgabe der Briefe nicht gedacht werden, von denen jeder einzelne dieselbe Natürlichkeit und Intensität besitzt wie Kafkas literarisches Werk, so wird man doch in einem kleinen Kreise rechtzeitig daran gehen, alles zu sammeln, was als Äußerung dieses einzigartigen Menschen in Erinnerung geblieben ist. Um nur ein Beispiel anzuführen: wie viele der Werke, die jetzt zu meiner bittern Enttäuschung in Kafkas Wohnung nicht mehr vorgefunden wurden, hat mir mein Freund vorgelesen oder wenigstens teilweise vorgelesen, teilweise ihren Plan erzählt! Wie unvergeßliche, ganz originelle, ganz tiefe Gedanken hat er mir mitgeteilt! Soweit mein Gedächtnis, soweit meine Kräfte reichen, soll nichts verlorengehen.

Das Manuskript des Romans „Der Prozeß“ habe ich im [410]Juni 1920 an mich genommen und gleich damals geordnet. Das Manuskript trägt keinen Titel. Doch hat Kafka dem Roman im Gespräch stets den Titel „Der Prozeß“ gegeben. Die Einteilung in Kapitel sowie die Kapitelüberschriften rühren von Kafka her. Bezüglich der Anordnung der Kapitel war ich auf mein Gefühl angewiesen. Doch da mir mein Freund einen großen Teil des Romans vorgelesen hatte, konnte sich mein Gefühl bei der Ordnung der Papiere auf Erinnerungen stützen. — Franz Kafka hat den Roman als unvollendet betrachtet. Vor dem Schlußkapitel, das vorliegt, sollten noch einige Stadien des geheimnisvollen Prozesses geschildert werden. Da aber der Prozeß nach der vom Dichter mündlich geäußerten Ansicht niemals bis zur höchsten Instanz vordringen sollte, war in einem gewissen Sinne der Roman überhaupt unvollendbar, d. h. in infinitum fortsetzbar. Die vollendeten Kapitel, mit dem abrundenden Schlußkapitel zusammengenommen, lassen jedenfalls sowohl den Sinn wie die Gestalt des Werkes mit einleuchtendster Klarheit hervortreten, und wer nicht darauf aufmerksam gemacht wird, daß der Dichter selbst an dem Werke noch weiterzuarbeiten gedachte (er unterließ es, weil er sich einer andern Lebensatmosphäre zuwandte) —, wird kaum seine Lücke fühlen. — Meine Arbeit an dem großen Papierbündel, das seinerzeit dieser Roman darstellte, beschränkte sich darauf, die vollendeten von den unvollendeten Kapiteln zu sondern. Die unvollendeten lasse ich für den Schlußband der Nachlaßausgabe zurück, sie enthalten nichts für den Gang der Handlung Wesentliches. Eines dieser Fragmente wurde vom Dichter selbst unter dem Titel „Ein Traum“ in den Band „Ein Landarzt“ aufgenommen. [411]Die vollendeten Kapitel sind hier vereinigt und geordnet. Von den unvollendeten habe ich nur eines, das offenbar nahezu vollendet ist, mit einer leichten Umstellung von vier Zeilen als Kapitel 8 hier eingereiht. — Im Text habe ich selbstverständlich nichts geändert. Ich habe nur die zahlreichen Abkürzungen transkribiert (z. B. statt F. B. „Fräulein Bürstner“ — statt T. „Titorelli“ voll ausgeschrieben) und einige kleine Versehen berichtigt, die offensichtlich nur deshalb in dem Manuskript stehen geblieben sind, weil es der Dichter einer definitiven Durchsicht nicht unterworfen hat.

Max Brod.`,
}
