export const publicFolderFilesUrls = {
	icons: {
		editButtonIcon: '/icons/editButtonIcon.svg',
		githubButtonIcon: '/icons/githubButtonIcon.svg',
		googleButtonIcon: '/icons/googleButtonIcon.svg',
		plusButtonIcon: '/icons/plusButtonIcon.svg',
		trashButtonIcon: '/icons/trashButtonIcon.svg',
		walletButtonIcon: '/icons/walletButtonIcon.svg',
		yandexButtonIcon: '/icons/yandexButtonIcon.svg',
		fullScreenButtonIcon: '/icons/fullScreenButtonIcon.svg',
		warningTriangle: '/icons/warningTriangle.svg',
		copyButtonIcon: '/icons/copyButtonIcon.svg',
		actionButtonIcon: '/icons/actionButtonIcon.svg',
		checkMark: '/icons/checkMark.svg',
	},
	images: {
		common: {
			camera: 'Camera.svg',
			logo: 'logo.svg',
			navArrowLeft: 'navArrowLeft.svg',
			navArrowRight: 'navArrowRight.svg',
		},
	},
	mainPage: {
		headVideo: '/mainPage/headVideo.mp4',
		headVideoPoster: '/mainPage/headVideoPoster.png',
		aboutBooksVideo: '/mainPage/aboutBooks.mp4',
		aboutBooksVideoPoster: '/mainPage/aboutBooksPoster.jpg',
		aboutVideosVideo: '/mainPage/aboutVideos.mp4',
		aboutVideosVideoPoster: '/mainPage/aboutVideosPoster.jpg',
		girlOnArmchair: '/mainPage/girlOnArmchair.webp',
		anyDevices: '/mainPage/anyDevices.svg',
		bookCover_1: '/mainPage/book-1.webp',
		bookCover_2: '/mainPage/book-2.webp',
		videoCover_1: '/mainPage/video-3.webp',
		videoCover_2: '/mainPage/video-4.webp',
		sign_1: '/mainPage/sign-1.svg',
		sign_2: '/mainPage/sign-2.svg',
		sign_3: '/mainPage/sign-3.svg',
		sign_4: '/mainPage/sign-4.svg',
		sign_5: '/mainPage/sign-5.svg',
		sign_6: '/mainPage/sign-6.svg',
	},
}
