export const publicFolderFilesUrls = {
	icons: {
		editButtonIcon: '/icons/editButtonIcon.svg',
		githubButtonIcon: '/icons/githubButtonIcon.svg',
		googleButtonIcon: '/icons/googleButtonIcon.svg',
		plusButtonIcon: '/icons/plusButtonIcon.svg',
		trashButtonIcon: '/icons/trashButtonIcon.svg',
		walletButtonIcon: '/icons/walletButtonIcon.svg',
		yandexButtonIcon: '/icons/yandexButtonIcon.svg',
		fullScreenButtonIcon: '/icons/fullScreenButtonIcon.svg',
		warningTriangleIcon: '/icons/warningTriangleIcon.svg',
		copyButtonIcon: '/icons/copyButtonIcon.svg',
		actionButtonIcon: '/icons/actionButtonIcon.svg',
		checkMarkIcon: '/icons/checkMarkIcon.svg',
		sendMessageIcon: '/icons/sendMessageIcon.svg',
		stopGenerationIcon: '/icons/stopGenerationIcon.svg',
		addIcon: '/icons/addIcon.svg',
	},
	images: {
		common: {
			camera: 'Camera.svg',
			logo: 'logo.svg',
			navArrowLeft: 'navArrowLeft.svg',
			navArrowRight: 'navArrowRight.svg',
		},
	},
	mainPage: {
		anyDevices: '/mainPage/anyDevices.svg',
		sherlockHolmes: '/mainPage/sherlockHolmes.png',
		ironMan: '/mainPage/ironMan.png',
		roundPlay: '/mainPage/roundPlay.svg',
		roundArrow: '/mainPage/roundArrow.svg',
		roundArrowWhite: '/mainPage/roundArrowWhite.svg',
		booksCovers: [
			'/mainPage/booksCovers/1.jpg',
			'/mainPage/booksCovers/2.jpg',
			'/mainPage/booksCovers/3.webp',
			'/mainPage/booksCovers/4.jpg',
			'/mainPage/booksCovers/5.jpg',
			'/mainPage/booksCovers/6.webp',
			'/mainPage/booksCovers/7.jpg',
			'/mainPage/booksCovers/8.webp',
			'/mainPage/booksCovers/9.jpg',
			'/mainPage/booksCovers/10.jpg',
			'/mainPage/booksCovers/11.jpg',
			'/mainPage/booksCovers/12.jpg',
			'/mainPage/booksCovers/13.webp',
			'/mainPage/booksCovers/14.jpg',
			'/mainPage/booksCovers/15.jpg',
			'/mainPage/booksCovers/16.webp',
			'/mainPage/booksCovers/17.jpg',
			'/mainPage/booksCovers/18.jpg',
			'/mainPage/booksCovers/20.jpg',
			'/mainPage/booksCovers/21.png',
			'/mainPage/booksCovers/22.webp',
			'/mainPage/booksCovers/23.jpeg',
			'/mainPage/booksCovers/24.jpg',
		],
	},
}
