export const chapter_53 = {
	name: 'Chapter LIII',
	header: 'And last',
	text: `The stories of those in this tale are nearly at an end. The little that remains to be told is simple and brief.

Within three months, Rose Fleming and Harry Maylie were married in the village church where the young clergyman would begin his work. On that same day, they moved into their new and happy home.

Mrs. Maylie went to live with her son and daughter-in-law. There, for the rest of her tranquil days, she enjoyed the greatest happiness that age can know: seeing the joy of those on whom she had poured all the love and care of her life.

After a full investigation, it appeared that the remaining property held by Monks—which had never brought prosperity to him or his mother—would amount to little more than three thousand pounds for both him and Oliver if divided equally. According to his father's will, Oliver should have received everything. However, Mr. Brownlow did not want to deny the elder son a chance to redeem himself and live an honest life. He proposed this division, and his young ward gladly agreed.

Monks, still using that false name, took his share of the money and moved to a distant part of the New World. There, he quickly wasted it and returned to his old ways. After a long imprisonment for a new act of fraud and deception, he finally died in prison from his old illness. Far from home, the last main members of Fagin's gang also met their end.

Mr. Brownlow adopted Oliver as his son. He, Oliver, and the old housekeeper moved to a house within a mile of the parsonage where his dear friends lived. This fulfilled the last wish of Oliver’s warm and earnest heart, creating a small community that was as close to perfect happiness as one can find in this ever-changing world.

Soon after the young people’s marriage, the good doctor returned to Chertsey. Missing his old friends, he would have been unhappy, if his nature allowed such feelings, and would have become irritable, if only he knew how. For a few months, he just hinted that the air no longer suited him. Then, realizing the place was truly not the same for him, he left his business to his assistant, rented a small cottage near his young friend’s village, and felt better at once. There, he took up gardening, fishing, and carpentry with his usual enthusiastic energy. He soon became known throughout the neighborhood as a great expert in all these areas.

Before moving, the doctor had formed a strong friendship with Mr. Grimwig, which the eccentric gentleman warmly returned. Now, Mr. Grimwig visits him many times a year. On these visits, Mr. Grimwig enthusiastically joins in with gardening, fishing, and carpentry, doing everything in his own unique and unusual way, while always insisting his method is the correct one. On Sundays, he always criticizes the sermon directly to the young clergyman, but later confides to Mr. Losberne that he thought it was excellent, though it is best not to say so. Mr. Brownlow has a favorite running joke of teasing him about his old prediction about Oliver, reminding him of the night they waited with the watch. But Mr. Grimwig insists he was mostly right, pointing out that Oliver, in fact, did not return that night, which always makes him laugh and lifts his spirits.

Mr. Noah Claypole received a pardon for testifying against Fagin. Finding his old profession unsafe, he was, for a time, unsure how to earn a living without too much effort. He soon found his calling as an informer, which provided a comfortable income. His method is simple: once a week, he and a well-dressed Charlotte walk about during church services. The lady faints near the door of a pub that is illegally open, and the gentleman asks for a bit of brandy to revive her. The next day, he reports the pub owner and collects half the fine. Sometimes Mr. Claypole faints himself, with the same profitable result.

Mr. and Mrs. Bumble lost their jobs and slowly fell into extreme poverty and misery. They ended up as paupers in the same workhouse where they had once acted as masters. Mr. Bumble has been heard to say that in his downfall, he lacks even the energy to be thankful he is separated from his wife.

Mr. Giles and Brittles are still at their old jobs, though Giles is now bald and Brittles is quite gray. They sleep at the parsonage but share their time so equally among its residents, Oliver, Mr. Brownlow, and Mr. Losberne, that the villagers still cannot figure out which household they truly belong to.

Appalled by Sikes’s crime, Master Charles Bates began to wonder if an honest life was not, after all, the best. Convinced that it was, he left his past behind, determined to start a new, better life. He struggled and suffered for a time, but his cheerful nature and good intentions helped him succeed. After working as a farmer's helper and a carrier's boy, he is now the happiest young grazier in all of Northamptonshire.

And now, the hand writing these words hesitates as it nears the end of its task, wishing to weave the thread of these adventures a little longer.

I wish I could stay a while longer with these characters, and share their happiness by describing it. I would show you Rose Maylie in the full bloom of her youth, casting a soft, gentle light on the path of all who knew her. I would paint her as the heart of the fireside circle and the summer gathering. I would follow her through the warm fields at noon, and hear her sweet, low voice on a moonlit evening walk. I would watch her acts of kindness and charity, and the tireless way she managed her home with a smile. I would show her and her dead sister’s child, happy in their love, spending hours talking about the friends they had lost. I would bring back the happy little faces that gathered around her knee and listen to their cheerful chatter. I would recall her clear laugh and the sympathetic tear in her soft blue eyes. All these moments, looks, and smiles—I wish I could recall every one.

It is not necessary to describe how Mr. Brownlow, day by day, filled the mind of his adopted son with knowledge, growing more attached to him as the boy's character grew and showed promise of all he hoped he would be. Nor is it needed to tell how he saw in Oliver new traces of his old friend, stirring sweet and sad memories in his heart. Or how the two orphans, tested by hardship, learned from it lessons of mercy, mutual love, and gratitude to God who had protected them. I have said that they were truly happy. For without deep affection, a kind heart, and gratitude to that Being whose law is Mercy and whose nature is Benevolence to all living things, happiness can never be truly found.

Near the altar of the old village church stands a white marble tablet that bears a single word: “AGNES.” There is no coffin in that tomb, and may it be many years before another name is carved above it. But if the spirits of the dead ever return to earth to visit places made holy by the love of those they left behind—a love that extends beyond the grave—I believe the spirit of Agnes sometimes lingers in that quiet corner. I believe this, even though that corner is in a church, and even though she was weak and made mistakes.`,
}
