import { Logger } from '@nestjs/common'
import { DEFAULT_FLASH_AI_MODEL } from 'types/AIModels'
import { dryText } from 'utils/stringUtils'
import { LlmAdapterService } from 'infrastructure/llmProviderAdapter/LlmAdapter.service'
import { formatSrtTimeMs } from './srtFormat'

// ─── Types ──────────────────────────────────────────────────────────────────

type WordTiming = {
	/** The word or punctuation token (e.g. "Hello", "world", "?") */
	word: string
	/** Absolute start time in milliseconds from the beginning of the video */
	startMs: number
}

type SentenceBoundary = {
	text: string
	startMs: number
	endMs: number
}

/** Вид YouTube-субтитров: авто-сгенерированные или загруженные вручную. */
export type YoutubeSubtitlesType = 'auto' | 'manual'

const logger = new Logger('YoutubeVttToSrt')

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Определяет вид YouTube-субтитров по содержимому VTT.
 *
 * Авто-сгенерированные субтитры содержат встроенные пословные таймкоды вида
 * `<HH:MM:SS.mmm>` внутри строк; ручные — это обычный WebVTT без таких маркеров.
 */
export function detectYoutubeSubtitlesType(vtt: string): YoutubeSubtitlesType {
	return /<(\d{2}:\d{2}:\d{2}\.\d{3})>/.test(vtt) ? 'auto' : 'manual'
}

/**
 * Конвертирует YouTube VTT (любого вида) в SRT.
 *
 * Ручные субтитры уже разбиты на фразы с правильной пунктуацией и регистром,
 * поэтому конвертируются детерминированно. Авто-сгенерированные — «набегающий»
 * VTT с пословными таймкодами, их перегруппировывает в предложения LLM.
 *
 * @param vtt — сырой VTT, который вернул YouTube API
 * @param llmAdapter — адаптер LLM для группировки слов в предложения (авто-путь)
 * @returns SRT-строка (может быть пустой, если в VTT нет речевых блоков)
 */
export async function convertYoutubeVttToSrt(vtt: string, llmAdapter: LlmAdapterService): Promise<string> {
	const type = detectYoutubeSubtitlesType(vtt)
	return type === 'manual' ? convertManualVttToSrt(vtt) : convertAutoGeneratedVttToSrt(vtt, llmAdapter)
}

// ─── Manual subtitles (plain WebVTT) ────────────────────────────────────────

/**
 * Конвертирует «ручные» YouTube-субтитры (обычный WebVTT без пословных
 * таймкодов) напрямую в SRT.
 *
 * Такие субтитры уже разбиты на фразы с правильной пунктуацией и регистром,
 * поэтому им не нужен LLM-проход. Каждый блок `HH:MM:SS.mmm --> HH:MM:SS.mmm`
 * становится одним cue: маркеры реплик (`- `) убираются, звуковые аннотации
 * (`[applause]`, `[chuckling]`) отбрасываются, а строки склеиваются в одну.
 */
function convertManualVttToSrt(vtt: string): string {
	const normalized = vtt.replace(/\r\n?/g, '\n').trim()
	const blocks = normalized.split(/\n{2,}/)

	const cues: { startMs: number; endMs: number; text: string }[] = []

	for (const block of blocks) {
		const lines = block
			.split('\n')
			.map((l) => l.trim())
			.filter((l) => l.length > 0)

		if (lines.length < 2) continue

		const tsMatch = lines[0].match(/^(\d{2}):(\d{2}):(\d{2})\.(\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2})\.(\d{3})/)
		if (!tsMatch) continue

		const cueText = dryText(
			lines
				.slice(1)
				.map((l) => l.replace(/^-+\s*/, '').trim())
				.join(' ')
				.replace(/\[.*?]/g, ' '),
		)
		if (!cueText) continue

		cues.push({
			startMs: hmsToMs(tsMatch[1], tsMatch[2], tsMatch[3], tsMatch[4]),
			endMs: hmsToMs(tsMatch[5], tsMatch[6], tsMatch[7], tsMatch[8]),
			text: cueText,
		})
	}

	if (cues.length === 0) return ''

	const srtLines: string[] = []
	cues.forEach((cue, idx) => {
		srtLines.push(String(idx + 1))
		srtLines.push(`${formatSrtTimeMs(cue.startMs)} --> ${formatSrtTimeMs(cue.endMs)}`)
		srtLines.push(cue.text)
		srtLines.push('')
	})

	return srtLines.join('\n').trimEnd() + '\n'
}

// ─── Auto-generated subtitles (word-timed VTT) ──────────────────────────────

/**
 * Системный промпт для группировки пословных таймингов в предложения через LLM.
 *
 * LLM получает чистый JSON-массив пар {w, t} (слово + абсолютные миллисекунды
 * от начала видео). Возвращает границы предложений — единственная семантическая
 * задача; все таймкоды уже предоставлены.
 */
const WORDS_TO_SENTENCES_SYSTEM_PROMPT = `You are a precise subtitle formatter. Group words with timestamps into grammatically correct sentences.

INPUT: JSON array of {"w": "word_or_punctuation", "t": start_milliseconds}

RULES:
1. Group consecutive words into complete sentences, using punctuation (. ! ?) and meaning as boundaries. Aim for one sentence per subtitle. Keep sentences reasonably short: if a sentence would exceed ~12 words, split it at a natural pause or meaning boundary.
2. For each sentence set:
   - "startMs" = the "t" value of the sentence's FIRST word
   - "endMs" = the "t" value of the sentence's LAST word + 300 ms
3. Rebuild "text" as clean, correctly punctuated prose:
   - Join words with single spaces.
   - Capitalize the first letter of each sentence.
   - Apply correct capitalization for the input language (e.g. the pronoun "I" and proper nouns in English).
   - Restore contractions and apostrophes where they belong (e.g. "im" -> "I'm", "dont" -> "don't", "youre" -> "you're").
   - End every sentence with a terminal punctuation mark (. ! ?).
4. The input is typically lowercase with no punctuation. Infer correct capitalization and punctuation from meaning. Do not paraphrase, add, or remove words — only fix casing, spacing, contractions, and punctuation.

OUTPUT: valid JSON only, no explanations:
{"sentences": [{"startMs": 400, "endMs": 4480, "text": "When did recognizing rights become something radical?"}, ...]}`

/**
 * Конвертирует авто-сгенерированный VTT (с пословными таймкодами) в SRT.
 *
 * Пайплайн: извлечь пословные тайминги → сгруппировать слова в предложения
 * через LLM → детерминированно дочистить текст и устранить перекрытия/зазоры
 * между предложениями → отформатировать в SRT.
 */
async function convertAutoGeneratedVttToSrt(vtt: string, llmAdapter: LlmAdapterService): Promise<string> {
	const wordTimings = parseVttToWordTimings(vtt)
	logger.log(`Extracted ${wordTimings.length} word timings from YouTube VTT`)

	const chunks = splitWordTimingsIntoChunks(wordTimings)
	if (chunks.length > 1) {
		logger.log(
			`Splitting ${wordTimings.length} word timings into ${chunks.length} LLM chunks ` +
				`(max ${MAX_WORDS_PER_CHUNK} words per chunk)`,
		)
	}

	const sentences: SentenceBoundary[] = []
	for (const chunk of chunks) {
		sentences.push(...(await groupWordsToSentences(chunk, llmAdapter)))
	}

	const normalized = normalizeSentenceEndTimes(
		sentences.map((s) => ({ ...s, text: normalizeSentenceText(s.text) })).filter((s) => s.text.length > 0),
	)
	const srt = buildSrtFromSentences(normalized)

	logger.log(`Built SRT with ${normalized.length} sentence(s) from YouTube VTT`)
	return srt
}

/**
 * Группирует пословные тайминги одного чанка в предложения через LLM.
 *
 * Возвращает сырые границы предложений в том порядке, в котором их вернул
 * LLM (порядок по времени). Нормализация текста и таймкодов выполняется
 * позже, уже по объединённому списку всех чанков.
 */
async function groupWordsToSentences(
	wordTimings: WordTiming[],
	llmAdapter: LlmAdapterService,
): Promise<SentenceBoundary[]> {
	const llmResult = await llmAdapter.generate({
		model: DEFAULT_FLASH_AI_MODEL,
		responseFormat: 'json_object',
		messages: [
			{ role: 'system', content: WORDS_TO_SENTENCES_SYSTEM_PROMPT },
			{ role: 'user', content: JSON.stringify(wordTimings) },
		],
	})

	logger.log(
		'LLM sentence grouping done ' +
			`(input=${llmResult.inputTokens} tokens, output=${llmResult.outputTokens} tokens)`,
	)

	const parsed = JSON.parse(llmResult.content) as { sentences: SentenceBoundary[] }
	return parsed.sentences
}

// ─── Private: parseVttToWordTimings helpers ─────────────────────────────────

/**
 * Parse raw YouTube VTT into a flat array of word-timing pairs.
 *
 * Algorithm:
 * 1. Skip headers (WEBVTT, Kind:, Language:, NOTE) and snapshot blocks.
 * 2. For each "building" block, capture the block start time.
 * 3. Split the text line by `<HH:MM:SS.mmm>` markers.
 * 4. The first word(s) use the block start time; each subsequent segment
 *    inherits the preceding timestamp.
 * 5. Strip `<c>` / `</c>` styling tags.
 * 6. Clean each word token: decode HTML entities and drop bracketed annotations.
 */
function parseVttToWordTimings(vtt: string): WordTiming[] {
	const words: WordTiming[] = []
	const lines = vtt.split('\n')
	let blockStartMs = 0

	for (const rawLine of lines) {
		const line = rawLine.trim()
		if (!line) continue

		// Skip headers & metadata
		if (
			line === 'WEBVTT' ||
			/^(Kind|Language):/i.test(line) ||
			line.startsWith('NOTE') ||
			/^(align|position):/i.test(line)
		) {
			continue
		}

		// Capture block timestamp
		const blockTsMatch = line.match(/^(\d{2}):(\d{2}):(\d{2})\.(\d{3})\s*-->/)
		if (blockTsMatch) {
			blockStartMs = hmsToMs(blockTsMatch[1], blockTsMatch[2], blockTsMatch[3], blockTsMatch[4])
			continue
		}

		// Skip plain-text lines (snapshots — they duplicate building-block text)
		if (!/<(\d{2}:\d{2}:\d{2}\.\d{3})>/.test(line)) continue

		// Extract word timestamps
		const cleaned = line.replace(/<\/?c[^>]*>/g, '')
		const parts = cleaned.split(/(<\d{2}:\d{2}:\d{2}\.\d{3}>)/)

		// First segment = word(s) before any timestamp → use block start
		let currentMs = blockStartMs

		for (const part of parts) {
			if (!part) continue

			const tsMatch = part.match(/^<(\d{2}):(\d{2}):(\d{2})\.(\d{3})>$/)
			if (tsMatch) {
				currentMs = hmsToMs(tsMatch[1], tsMatch[2], tsMatch[3], tsMatch[4])
				continue
			}

			// Extract individual words from this segment
			const textWords = part
				.trim()
				.split(/\s+/)
				.filter((w) => w.length > 0)
			for (const word of textWords) {
				const clean = cleanWordToken(word)
				if (clean === null) continue
				words.push({ word: clean, startMs: currentMs })
			}
		}
	}

	return words
}

function hmsToMs(h: string, m: string, s: string, ms: string): number {
	return Number(h) * 3_600_000 + Number(m) * 60_000 + Number(s) * 1_000 + Number(ms)
}

/** Common named HTML entities found in YouTube VTT (e.g. `&nbsp;` inside music markers). */
const HTML_ENTITIES: Record<string, string> = {
	nbsp: ' ',
	amp: '&',
	lt: '<',
	gt: '>',
}

/**
 * Decode HTML entities (`&nbsp;`, `&amp;`, numeric `&#123;`) into plain text.
 * Unknown entities are left unchanged.
 */
function decodeHtmlEntities(text: string): string {
	return text.replace(/&(#x?[0-9a-fA-F]+|[a-zA-Z]+);/g, (match, entity: string) => {
		if (entity[0] === '#') {
			const isHex = entity[1] === 'x' || entity[1] === 'X'
			const code = Number.parseInt(entity.slice(isHex ? 2 : 1), isHex ? 16 : 10)
			if (Number.isNaN(code) || code < 0 || code > 0x10ffff) return match
			return String.fromCodePoint(code)
		}
		return HTML_ENTITIES[entity] ?? match
	})
}

/**
 * Clean a single word token extracted from YouTube VTT.
 *
 * Drops YouTube's bracketed annotations (`[Music]`, `[Applause]`, `[ __ ]`,
 * `[&nbsp;__&nbsp;]`) which carry no speech, and decodes HTML entities in the
 * remaining text. Returns `null` when the token has no speech content.
 */
function cleanWordToken(rawWord: string): string | null {
	const decoded = decodeHtmlEntities(rawWord)

	// A token that is entirely a bracketed annotation carries no speech.
	if (decoded.startsWith('[') && decoded.endsWith(']')) return null

	// Defensive: strip any bracket annotations glued to real words.
	const cleaned = decoded
		.replace(/\[.*?]/g, ' ')
		.replace(/\s+/g, ' ')
		.trim()

	// Drop tokens with no letter or digit (leftover `[`, `]`, `__`, punctuation).
	if (!/[A-Za-zÀ-ÖØ-öø-ÿ0-9]/.test(cleaned)) return null

	return cleaned
}

// ─── Private: chunking word timings for the LLM ─────────────────────────────

/**
 * Максимум слов на один LLM-вызов при конвертации YouTube VTT → SRT.
 *
 * Видео ~10 минут — это примерно 1500 слов и надёжно разбирается одним вызовом.
 * Более длинные видео нарезаются на чанки не больше этого размера; каждый разрез
 * делается по самой большой паузе между словами в хвостовом окне, поэтому он
 * редко попадает в середину предложения. Значение подобрано эмпирически и легко
 * тюнится после замера реального качества на длинных роликах.
 */
const MAX_WORDS_PER_CHUNK = 2500

/**
 * На сколько слов от жёсткого лимита отступаем назад в поисках хорошей паузы.
 * Задаёт минимальный размер чанка: MAX_WORDS_PER_CHUNK − LOOKBACK_WORDS.
 */
const LOOKBACK_WORDS = 400

/**
 * Нарезает плоский список пословных таймингов на чанки для LLM.
 *
 * Правила:
 * - Если слов не больше {@link MAX_WORDS_PER_CHUNK} — возвращает один чанк
 *   (текущее поведение для коротких видео).
 * - Иначе каждый чанк имеет длину в диапазоне [MAX − LOOKBACK, MAX] слов.
 * - Точку разреза ищем в хвостовом окне последних {@link LOOKBACK_WORDS} слов
 *   и выбираем границу с самой большой паузой между словами — это почти всегда
 *   конец мысли/предложения, а не середина.
 */
function splitWordTimingsIntoChunks(wordTimings: WordTiming[]): WordTiming[][] {
	if (wordTimings.length <= MAX_WORDS_PER_CHUNK) return [wordTimings]

	const chunks: WordTiming[][] = []
	let start = 0

	while (start < wordTimings.length) {
		const hardEnd = Math.min(start + MAX_WORDS_PER_CHUNK, wordTimings.length)

		// Последний чанк — берём остаток целиком, разрезать не нужно.
		if (hardEnd >= wordTimings.length) {
			chunks.push(wordTimings.slice(start))
			break
		}

		// Выбираем разрез в окне [hardEnd − LOOKBACK_WORDS, hardEnd]:
		// границу с самой большой паузой между соседними словами.
		// `start + 1` гарантирует прогресс, даже если константы изменят.
		const lookbackStart = Math.max(start + 1, hardEnd - LOOKBACK_WORDS)
		let cut = hardEnd
		let bestGap = Number.NEGATIVE_INFINITY
		for (let k = lookbackStart; k <= hardEnd; k++) {
			const gap = wordTimings[k].startMs - wordTimings[k - 1].startMs
			if (gap > bestGap) {
				bestGap = gap
				cut = k
			}
		}

		chunks.push(wordTimings.slice(start, cut))
		start = cut
	}

	return chunks
}

// ─── Private: buildSrtFromSentences helpers ─────────────────────────────────

function buildSrtFromSentences(sentences: SentenceBoundary[]): string {
	const lines: string[] = []

	sentences.forEach((sentence, idx) => {
		lines.push(String(idx + 1))
		lines.push(`${formatSrtTimeMs(sentence.startMs)} --> ${formatSrtTimeMs(sentence.endMs)}`)
		lines.push(sentence.text)
		lines.push('')
	})

	return lines.join('\n').trimEnd() + '\n'
}

/**
 * Compute final `endMs` for each sentence boundary that the LLM returned.
 *
 * The LLM provides `startMs` accurately (first word's timestamp), but
 * `endMs` is approximate. We tighten it so consecutive sentences don't
 * overlap and don't have large gaps.
 */
function normalizeSentenceEndTimes(sentences: SentenceBoundary[]): SentenceBoundary[] {
	if (sentences.length === 0) return sentences

	return sentences.map((s, i) => {
		let endMs: number
		if (i < sentences.length - 1) {
			// End = next sentence start − 50 ms gap
			endMs = Math.max(s.startMs + 100, sentences[i + 1].startMs - 50)
		} else {
			// Last sentence: use LLM's endMs but ensure minimum duration
			endMs = Math.max(s.startMs + 500, s.endMs)
		}
		return { ...s, endMs }
	})
}

/**
 * Deterministic safety net for sentence text returned by the LLM.
 *
 * The LLM normalizes casing and punctuation, but this guarantees the basics
 * even when the LLM misses: flatten whitespace, strip any bracket annotations
 * that slipped through, capitalize the first letter, and ensure a terminal
 * punctuation mark.
 */
function normalizeSentenceText(text: string): string {
	let t = text
		.replace(/\[.*?]/g, ' ')
		.replace(/[\r\n]+/g, ' ')
		.replace(/\s+/g, ' ')
		.trim()

	if (!t) return t

	t = t.charAt(0).toUpperCase() + t.slice(1)

	if (!/[.!?…]["'”’)]*$/.test(t)) {
		t += '.'
	}

	return t
}
