// ─── Search params ────────────────────────────────────────────────────────────

export type SearchVideosParams = {
	query: string
	limit: number
	pageToken?: string
}

// ─── YouTube API response types ───────────────────────────────────────────────

export type YoutubeSearchResponse = {
	kind: string
	etag: string
	nextPageToken?: string
	prevPageToken?: string
	pageInfo: {
		totalResults: number
		resultsPerPage: number
	}
	items: YoutubeSearchItem[]
}

export type YoutubeSearchItem = {
	kind: string
	etag: string
	id: {
		kind: string
		videoId: string
	}
	snippet: {
		publishedAt: string
		channelId: string
		title: string
		description: string
		channelTitle: string
		thumbnails: YoutubeThumbnails
	}
}

export type YoutubeVideosResponse = {
	kind: string
	etag: string
	pageInfo: {
		totalResults: number
		resultsPerPage: number
	}
	items: YoutubeVideoItem[]
}

export type YoutubeVideoItem = {
	id: string
	snippet: {
		channelId: string
		title: string
		channelTitle: string
		defaultAudioLanguage?: string
		thumbnails: YoutubeThumbnails
	}
	statistics: {
		viewCount?: string
	}
	contentDetails: {
		duration: string
	}
	player: {
		embedWidth: number
		embedHeight: number
	}
}

export type YoutubeChannelsResponse = {
	items: {
		id: string
		snippet: {
			thumbnails: YoutubeThumbnails
		}
	}[]
}

export type YoutubeThumbnails = {
	default?: { url: string; width: number; height: number }
	medium?: { url: string; width: number; height: number }
	high?: { url: string; width: number; height: number }
	standard?: { url: string; width: number; height: number }
	maxres?: { url: string; width: number; height: number }
}

// ─── Unified output ───────────────────────────────────────────────────────────

// ─── Subtitles ─────────────────────────────────────────────────────────────────

export type YoutubeCaptionInfo = {
	ext: string
	url: string
	name: string
}

export type YoutubeSubtitleResult = {
	language: string
	isAutoGenerated: boolean
	content: string
}

// ─── Unified output ───────────────────────────────────────────────────────────

export type YoutubeVideoData = {
	videoId: string
	title: string
	channelName: string
	channelLogoUrl: null | string
	thumbnailUrl: string
	viewCount: number
	/** Длительность в секундах, распарсенная из ISO 8601 */
	durationSec: number
	defaultAudioLanguage: null | string
	/** Соотношение сторон в CSS-формате: "1280 / 720" */
	ratio: string
}
